PublicMapping/districtbuilder

- doc/arch/adr-01-backend-framework.md
Combined ADRs for backend framework & DB management.
Closes #5  
Closes #14
> Backend ADR

- doc/arch/adr-02-district-data-storage.md
ADR for storage of district data
Closes #8
> Add district data storage ADR

- src/manage/README.md
- src/manage/package.json
- src/manage/src/commands/process-geojson.ts
- src/manage/src/lib/cmd.js
- src/manage/yarn.lock
Adds output of separate vector tiles file pyramids per geolevel to ingest script
```
src/manage [ ./bin/run process-geojson ~/Downloads/DE.geojson -o output -l block,tract,county                                             feature/mvm/topojson-to-vector-tiles ] 2:55 PM 
Reading base GeoJSON: /home/mike/Downloads/DE.geojson... done                                                                                                                            
GeoJSON contains 24115 features                                                                                                                                                         
Converting to topojson with base geolevel: block …
```
> Update ingest script to also output vector tiles

- package.json
- src/client/App.tsx
- src/client/screens/HomeScreen.tsx
- src/client/screens/ProjectScreen.tsx
- yarn.lock
Sets up some basic routing with a couple pages. Also has a link from one page to the other for both cases.
Also noticed `yarn format` wasn't applying to sub-directories, so made a small change there.
- Load up http://localhost:3003
- Verify there is a skeleton home page with a link to an example project page
- Click on the link
- Verify the old map page is showing up here, and that the id from the URL parameter is showing up on the page
- Manually modify the URL to try a different id
- Add a trailing slash and ensure the page still shows as normal
Closes #59
> Set up routing for home and project page

- src/manage/Dockerfile
- src/manage/README.md
- src/manage/package.json
- src/manage/src/commands/publish-region.ts
- src/manage/src/lib/dbUtils.ts
- src/manage/tsconfig.json
- src/manage/yarn.lock
- src/server/src/chambers/entities/chamber.entity.ts
- src/server/src/region-configs/entities/region-config.entity.ts
The `process-geojson` command generates a set of static data for a region. A new command has been created: `publish-region`, which pushes this data to S3 and inserts a row into the `region-config` table.
* I noticed that there were a couple problems with the Dockerfile that caused `process-geojson` to fail. This has been addressed here.
* The most difficult part of this task by far was getting database access to work in a good way within the CLI. I tried many ways to get this to work, such as using Nest in standalone mode, but unfortunately it doesn't appear that Nest and oclif can function well together. The implementation I finally got to work here uses `typeorm` directly, in a specific way (calling `createConnection` within the oclif `run` function, and using that to get the …
> Add command for publishing a set of static data

- package.json
- src/client/App.tsx
- src/client/components/FieldErrors.tsx
- src/client/screens/LoginScreen.tsx
- src/client/theme.ts
- tslint.json
- yarn.lock
Adds [`theme-ui`](https://theme-ui.com/) and uses it to componentize the login screen
- Go to the login screen
- attempt to login with a missing user or incorrect password to see errors
- verify login still works correctly
Closes #93
> Add theme-ui and componentize login screen

- Jenkinsfile
- deployment/terraform/app.tf
- deployment/terraform/cdn.tf
- deployment/terraform/certificate.tf
- deployment/terraform/dns.tf
- deployment/terraform/firewall.tf
- deployment/terraform/storage.tf
- deployment/terraform/task-definitions/app.json.tmpl
- deployment/terraform/variables.tf
- scripts/update
- src/server/.dockerignore
- src/server/Dockerfile
- src/server/package.json
- src/server/yarn.lock
Configures and deploys the application to Fargate in the staging environment.
Migrations have been applied to the staging database.
There are some minor formatting fixes in this PR, you may want to hide whitespace in the diff.
- Run a Terraform plan and verify that infrastructure is up to date:
```#bash
docker-compose -f docker-compose.ci.yml terraform scripts/infra plan
```
- Verify that the application is functional at https://staging.districtbuilder.azavea.com
Closes #71
> Deploy staging application

- src/server/migrations/1590169690909-ForgotPasswordTypes.ts
> Update migration to handle projects already existing

- src/client/components/Map.tsx
> fix labels on project screen

- src/shared/functions.ts
Save as larger geounit when all values are the same
This is relevant when the following happens:
- Entire non-base geounit (eg. county or blockgroup) is selected and assigned to a district
- One geounit within it is reassigned to a different district
- Then it is later reassigned back to the original district
This change makes it so that instead of saving the data for that
geolevel as an array containing all the same value, it contains just the
value itself.
This keeps our district definitions maximally compact and also makes it
easier to identify unassigned geounits which will be relevant for future
feature work.
Should represent no functional change
* Choose an intermediate geolevel (tract/blockgroup)
* Use rectangle tool to select the entire state (all geounits) and assign that to a …
> Save as larger geounit when all values are the same

- src/manage/package.json
- src/manage/yarn.lock
- src/server/package.json
- src/server/yarn.lock
- yarn.lock
I merged all the latest Dependabot updates into this branch and gave the app a general test to ensure it's still functioning.
Ensure it passes CI
> Dependabot updates

- src/client/components/Loading.tsx
- src/client/components/ProjectSidebar.tsx
- src/client/components/map/Map.tsx
- src/client/components/map/index.ts
- src/client/screens/ActivateAccountScreen.tsx
- src/client/screens/ProjectScreen.tsx
- src/client/theme.ts
Adds a spinner component
Theme UI has a spinner component, so I am using that.
- Make a change to the map and "Accept"
- You should see a spinner in place of the "Accept" button (previously, this showed the text "Loading ..."
Closes #194
> Add spinner

- src/client/components/map/Map.tsx
Adds zoom buttons to map.
- Open project
- You should see zoom buttons on the map in the top right
Closes #223
> Add zoom buttons

- src/client/screens/CreateProjectScreen.tsx
> Redirect to project page after creating a new project

- src/client/api.ts
- src/client/screens/HomeScreen.tsx
- src/client/screens/RegistrationScreen.tsx
- src/server/src/auth/controllers/auth.controller.ts
- yarn.lock
- Redirect to main home screen on registration
- Show an alert that the user needs to verify their email address on the home screen
- With a link to resend the verification email
- This is just using the default `<Alert>` styling, I haven't made any attempt to match the wireframes as the whole Home screen needs a design pass
- The copy could use a look by @tgilcrest 
- Register a new user
- Observe the alert banner
- Try using the "Resend email" button
- Verifying your email should make the banner go away
Closes #246
> Redirect to main home screen on registration

- src/client/components/map/Map.tsx
- src/client/components/map/index.ts
> Show geounit boundaries only for selected geolevel and those above it

- README.md
Document how to get set up with data for development.
Currently this is only documented in past PRs via testing instructions. It would be nice to have the commands handy as a reference and for spinning up new developers.
> Document how to get set up with data for development

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
Add a checklist to the pull request template as a reminder to update the `CHANGELOG` for each change made to the code base. In addition, initialize the `CHANGELOG.md` file.
The PR checklist from Histo was used as a base for this one. It was paired down to focus on the `CHANGELOG` specific steps.
Review the PR template checklist to see if there are any additional items that would benefit the project.
> Add project CHANGELOG and associated PR checklist

- src/client/components/map/index.ts
Replace var with const. Could have sworn I did this already, but maybe lost it fixing a merge conflict.
> Fix linting issue

- src/client/components/MapHeader.tsx
This hotfix should clear up the linter warning.
> Remove unused block of code

- src/client/components/map/MapTooltip.tsx
- Use the rectangle select on the project screen
Closes #324
> Fix displaying demographics in rectangle select tooltip

- src/client/App.tsx
- src/client/screens/HomeScreen.tsx
Redirect to login page if not logged in
Also redirect to login page after logging out.
* While logged out, go to the home page
* Ensure you are redircted to the login page
* Log in and then log back out
* Ensure you are redircted to the login page
Closes #296
> Redirect to login page if not logged in

- src/manage/yarn.lock
- src/server/package.json
- src/server/yarn.lock
There were a few dependabot PRs hanging out. I pulled them down, tested them out, and combined them into this PR.
Already tested locally. Good to merge when CI passes.
> Recent dependabot updates

- src/client/App.css
- src/client/components/ProjectHeader.tsx
Remove placeholder buttons
- Confirm that there are no buttons in the top right of the header
Closes #373
> Remove placeholder buttons

- src/client/components/map/AdvancedEditingModal.tsx
- src/client/theme.ts
Update copy and style modal. 
- Create new project
- Zoom in, select block mode to trigger this modal
- Confirm that the modal opens as expected and looks similar to the screenshot
Closes #384
> Update blocks modal style and copy

- src/client/api.ts
- src/client/screens/CreateProjectScreen.tsx
This sorts the region config dropdown by name. Previously it was unsorted.
- Browse to the create map page
- Verify that the region config dropdown has items sorted alphabetically by name
> Sort region config selection dropdown

- CHANGELOG.md
- src/client/actions/districtDrawing.ts
- src/client/components/ProjectSidebar.tsx
- src/client/reducers/districtDrawing.ts
- src/client/reducers/projectData.ts
- src/client/screens/ProjectScreen.tsx
- src/client/types.d.ts
This addresses the following:
1) The spinner wasn't showing after pressing Accept
2) "Saved" was showing even before anything was saved
3) "Saved" was showing after pressing cancel, which could be confusing
- Load the map page
- Verify that a spinner is shown initially in the sidebar, but then no "Saved" text is shown
- After saving, you should see "Saved" text
- After canceling, you should not see "Saved" text
Closes #444
> Fix saved notification

- src/client/App.tsx
- src/client/screens/CreateProjectScreen.tsx
- src/client/screens/ForgotPasswordScreen.tsx
- src/client/screens/HomeScreen.tsx
- src/client/screens/LoginScreen.tsx
- src/client/screens/RegistrationScreen.tsx
- src/client/screens/StartProjectScreen.tsx
- src/client/theme.ts
- src/client/types.d.ts
- src/server/migrations/1605289114325-region_config_hidden.ts
- src/server/src/region-configs/entities/region-config.entity.ts
- src/shared/entities.d.ts
This adds a new front-end page at `/start-project` that will automatically create a new project with the provided query parameters, and will redirect to login/registration with an informative message and then redirect back after if needed.
@tgilcrest @jfrankl let me know if the styling/copy on the login/registration alerts should be changed
- Run migrations: `scripts/migration`
- Hide Dane County (or another region config you want to test) by running the following in `scripts/dbshell`: `UPDATE region_config SET hidden = TRUE WHERE name = 'Dane County';`
- Try out a `/start-project` URL without correct query parameters or with invalid parameters - you should see an error page
- Try out `/start-project?numberOfDistricts=...&name=...&regionConfigId=...` with valid parameters while logged in. …
> Create map link

- CHANGELOG.md
- package.json
- src/client/actions/projects.ts
- src/client/api.ts
- src/client/components/DeleteProjectModal.tsx
- src/client/components/ProjectListFlyout.tsx
- src/client/reducers/projects.ts
- src/client/screens/HomeScreen.tsx
- src/client/theme.ts
- src/server/migrations/1608566772477-archive_project.ts
- src/server/src/projects/entities/project.entity.ts
- src/server/src/projects/entities/update-project.dto.ts
- src/shared/entities.d.ts
- yarn.lock
Adds option to project list flyout component to delete that map, after confirming with a modal.
Projects are not actually deleted, but marked with an `archived` flag, in anticipation of a potential unarchive feature.
- Delete a project from the home screen
Closes #120
> Delete maps from home screen

- .gitignore
- CHANGELOG.md
- src/client/actions.ts
- src/client/actions/organizationJoin.ts
- src/client/api.ts
- src/client/components/AuthComponents.tsx
- src/client/components/JoinOrganizationModal.tsx
- src/client/reducers.ts
- src/client/reducers/organizationJoin.ts
- src/client/screens/OrganizationScreen.tsx
- src/server/migrations/1613488436888-organization_users.ts
- src/server/src/organizations/controllers/organizations.controller.ts
- src/server/src/organizations/entities/organization.entity.ts
- src/server/src/organizations/entities/organizationUser.dto.ts
- src/server/src/organizations/organizations.module.ts
- src/server/src/users/entities/user.entity.ts
- src/shared/constants.ts
- src/shared/entities.d.ts
Allows users to join and leave an organization. If a user attempts to join an organization before they are logged in, they are redirected to a modal asking them to sign up.
- Add new API endpoint for joining organization
- Connect frontend to backend
- Add new redux module for organizationJoin
- Add API endpoint for leaving organization
- Show JoinOrganization modal for unauthenticated users when attempting to join an organization
- Update `AuthModalContent` to support reuse as part of the OrganizationJoin workflow
- Format and lint
Before Join - logged in
After join - user in org
Before join - unauthenticated user
Before join - prompt to login
- Per @tgilcrest 's comment on #226 , we are still waiting for updated copy to be used in `AuthModalContent`. Additionally, we will need to wire …
> Allow users to join an organization

- src/server/src/projects/controllers/projects.controller.ts
Fixes formatting error induced by #614 
- `./scripts/yarn client lint`
- `./scripts/yarn server lint`
> Fix formatting

- CHANGELOG.md
- src/client/App.tsx
- src/client/api.ts
- src/client/components/AuthComponents.tsx
- src/client/components/JoinOrganizationModal.tsx
- src/client/components/OrganizationDropdown.tsx
- src/client/components/RegisterContent.tsx
- src/client/components/SiteHeader.tsx
- src/client/screens/ActivateAccountScreen.tsx
- src/client/screens/HomeScreen.tsx
- src/client/screens/OrganizationScreen.tsx
- src/client/screens/RegistrationScreen.tsx
- src/server/src/auth/auth.module.ts
- src/server/src/auth/controllers/auth.controller.ts
- src/server/src/auth/entities/register.dto.ts
- src/server/src/auth/services/auth.service.ts
- src/server/src/users/controllers/users.controller.ts
- src/shared/entities.d.ts
When a new user attempts to sign up for an account and join an organization from an organization's page, they are automatically added to the Organization as an 'unverified user'. If an unverified user views their organization's page before confirming their email, they are prompted to confirm their email.
- Ensure that you are not logged in with an existing user account
- Navigate to an organization page (e.g., http://localhost:3003/o/mikes-maps)
- Click 'Join Organization' and fill in credentials not associated with an existing user
Closes #586 & #609
> Add verify and join org link to verification email

- src/client/components/FeaturedProjectCard.tsx
- src/client/components/MenuButton.styles.tsx
- src/client/components/ProjectHeader.tsx
- src/client/index.css
- src/client/screens/OrganizationScreen.tsx
- src/client/theme.ts
Cleans up formatting for the organization page.
- Added color the the featured maps
- Go to an organization page
- Join and unjoin the organization
- Make sure the page looks like the screenshot and generally seems okay, doesn't appear to have any missing styles
Fixes #645
> Style cleanup for organization page

- src/client/components/ProjectHeader.tsx
- src/client/screens/HomeScreen.tsx
This reverts commit 7a2be27cc2716386572d4b3a9207789c51dddc48 from the release branch
> Revert "Comment out import and evaluate buttons"

- src/client/screens/OrganizationScreen.tsx
Moves click handler of Leave Organization to actually be on the `Button` element
Closes #716
> Move leave organization click handler to correct location

- src/client/components/ProjectSidebar.tsx
> Fix lint error

- src/client/components/ConfirmJoinOrganization.tsx
I forgot to finalize the copy on the org join modal so I'm updating it here.
This should look ok, but I haven't provisioned the frontend, so please make any formatting suggestions if it looks weird.
> Update copy on the org join modal

- src/client/components/ProjectSidebar.tsx
> Fix calculation of political lean

- src/client/components/ProjectHeader.tsx
- src/client/components/map/keyboardShortcuts.ts
This reverts commit b0904c526799b3e1ec61ece4bf295d2d062cb54f.
Closes #XXX
> Revert "Disable evaluate mode temporarily"

- src/manage/src/commands/process-geojson.ts
> Allow renaming demographics props in process-geojson

- CHANGELOG.md
- src/client/screens/CreateProjectScreen.tsx
Updates population deviation helper text
- Open create project screen and select a region
Closes #804
> Update population deviation helper text

- CHANGELOG.md
- src/client/App.tsx
Fixes the regression where login did not redirect the user to the home screen
I was surprised how easy this was, only needed to move `QueryParamsProvider` up a level.
- Go to [http://localhost:3003](http://localhost:3003)
- Login with a valid username and password
- Expect: you are successfully redirected to the home screen after login
Closes #889
> Redirect to home screen after successful login

- src/client/components/Field.tsx
- src/client/components/HomeScreenProjectCard.tsx
- src/client/components/MapHeader.tsx
- src/client/components/MenuButton.styles.tsx
- src/client/components/ProjectListFlyout.tsx
- src/client/components/ProjectName.tsx
- src/client/components/ProjectSidebar.tsx
- src/client/components/ProjectSidebarHeader.tsx
- src/client/components/ShareMenu.tsx
- src/client/components/SiteHeader.tsx
- src/client/components/Tour.tsx
- src/client/components/evaluate/detail/Competitiveness.tsx
- src/client/components/evaluate/detail/MajorityRace.tsx
- src/client/components/map/FindMenu.tsx
- src/client/components/map/ProjectDistrictsMap.tsx
- src/client/index.css
- src/client/screens/CreateProjectScreen.tsx
- src/client/screens/HomeScreen.tsx
- src/client/screens/ProjectScreen.tsx
- src/client/screens/PublishedMapsListScreen.tsx
- src/client/theme.ts
Style cleanup across application.
- This PR makes a number of style fixes across the application, be sure to take a look around in every section, specifically
- The home screen (map list)
- Project screen with the sidebar expanded or not expanded
- Evaluate mode, Competitiveness view
- The find button
Fixes #865
> Style cleanup

- src/client/App.tsx
- src/client/components/SiteHeader.tsx
There are unresolved performance issues with the API that powers this
page
Closes #XXX
> Temporarily hide Community Maps page

- src/server/src/projects/controllers/projects.controller.ts
Fix project duplication from project screen
Closes #XXX
> Fix project duplication from project screen

- src/client/components/ProjectReferenceLayers.tsx
We don't support this quite yet, so this copy is incorrect
Closes #1010
> Update copy to remove reference to line data

- CHANGELOG.md
- README.md
This PR adds instructions to the README about verifying account emails.
> Update README with email verification instructions

- CHANGELOG.md
- deployment/README.md
- deployment/configure_pgadmin.md
There was no documentation on releasing new data. This PR adds documentation on both the data quality assurance and release processes and on configuring PG Admin for use with the project.
> Add documentation on releasing new data

- deployment/README.md
- deployment/terraform/app.tf
- deployment/terraform/storage.tf
- docker-compose.ci.yml
- scripts/cibuild
- scripts/cipublish
- scripts/infra
- src/manage/Dockerfile
This is a collection of small tweaks found while looking at the memory issues / me breaking new instances from launching
> Bryanquigley minor fixups
