PublicMapping/districtbuilder

- package.json
- scripts/test
- src/App.css
- src/App.tsx
- src/components/Map.tsx
- src/constants/map.ts
- src/setupTests.ts
- yarn.lock
This PR adds a simple map component using `mapbox-gl-js`, showing 1 layer of Census block groups in PA.
I copied the tiles from the [prototype project](https://github.com/azavea/districtbuilder-2/tree/master/public) and uploaded them to the S3 bucket `global-districtbuilder-dev-us-east-1`. I also copied the what styling I used from the prototype.
I only display the block group layer because that was the only one in the prototype project that seemed to be in vector tile format already.
Closes #10
> Add basic Map component

- src/server/package.json
- src/server/src/app.module.ts
- src/server/src/healthcheck/healthcheck.service.ts
- src/server/src/users/users.module.ts
- src/server/yarn.lock
Adds a healthcheck endpoint that checks for database connectivity.
```
$ curl http://localhost:3005/healthcheck
{"status":"ok","info":{"database":{"status":"up"}},"details":{"database":{"status":"up"}}}
```
This is using the `terminus` healthcheck library, which Nest has an existing integration for (https://docs.nestjs.com/recipes/terminus). This library supports [a few builtin health checks](https://github.com/nestjs/terminus/tree/f62c2b2d9170811ad9221469fd286e0653d6667a/lib/health-indicators) and will also allow us to write our own if necessary.
For now I've only enabled the DB connection check, but I imagine the DNS, disk space or available memory checks could be useful as well.
- http://localhost:3005/healthcheck should return a 200 status and the …
> Add healthcheck endpoint to backend

- scripts/dbshell
- scripts/migration_generate
- src/server/migrations/1580263521268-CreateUserTable.ts
- src/server/ormconfig.js
Spotted a couple problems while doing some testing. This PR has minor fixes for the `dbshell` and `migration_generate` command, properly uses the `.env` file for setting the PostgreSQL database, and fixes a problem with a migration.
- `docker-compose down` to kill all of your containers (or at least just kill your database container)
- `./scripts/setup`
- Verify the application works as expected (maybe add a user and refresh)
- Run `./scripts/dbshell` and verify you can list the tables
> Various minor database-related cleanup

- docker-compose.yml
Upgrade the application to use PostgreSQL 11.5 in the pursuit of being on the most up-to-date version of PostgreSQL supported by RDS for PostgreSQL on AWS.
- Destroy any existing containers (including the database)
```
docker-compose down
```
- Run `update` to ensure the database state is consistent and then `server` to bring the application up
```
./scripts/update
./scripts/server
```
- From your host run the following command, and ensure that a GeoJSON payload is returned
```
curl -s "http://localhost:3005/districts/topology/pa" | python3 -mjson.tool
```
Closes #37
> Upgrade database to PostGIS 2.5 and PostgreSQL 11.5

- Jenkinsfile
- scripts/cipublish
Establishes a `cipublish` script to push container images to ECR. The `cipublish` step will run on `develop`, `release`, `test`, and `hotfix` branches.
The `district-builder-server` ECR repository has been created manually on the District Builder AWS account.
- Verify that the [Jenkins build](http://urbanappsci.internal.azavea.com/job/PublicMapping/job/district-builder-2/job/PR-63/5/) runs the `cipublish` step and successfully pushes an image to the ECR repository.
Closes #36
> Publish container images to ECR

- .gitignore
- Jenkinsfile
- README.md
- deployment/README.md
- deployment/terraform/alarms.tf
- deployment/terraform/config.tf
- deployment/terraform/database.tf
- deployment/terraform/dns.tf
- deployment/terraform/firewall.tf
- deployment/terraform/network.tf
- deployment/terraform/variables.tf
- deployment/terraform/versions.tf
- docker-compose.ci.yml
- scripts/infra
Configures and deploys VPC and RDS resources.
Resolves #45 
AWS resources have been prefixed with `districtbuilder`. #78 has been opened to track renaming old resources to `districtbuilder-classic`.
- Confirm that the [Jenkins build](http://urbanappsci.internal.azavea.com/job/PublicMapping/job/district-builder-2/view/change-requests/job/PR-65/10/) passes and runs the `infra` step successfully.
- Run this command to get a shell in the Terraform container and use the staging Terraform config bucket:
```#bash
docker-compose -f docker-compose.ci.yml run --rm terraform
```
- Run `./scripts/plan` and inspect the Terraform plan output. The command should run successfully but no changes should be necessary.
- SSH into the Bastion host using the `.pem` file in the DistrictBuilder2 directory on our …
> Configure AWS VPC and RDS with Terraform

- docker-compose.yml
- src/client/App.tsx
- src/client/api.ts
- src/client/screens/ActivateAccountScreen.tsx
- src/client/screens/ActivateScreen.tsx
- src/client/screens/HomeScreen.tsx
- src/client/screens/RegistrationScreen.tsx
- src/server/src/auth/services/auth.service.ts
- src/server/src/templates/verify.hbs
Implement user registration
I opted to just use React component state instead of using Redux, instead storing the request state in the component itself. Redux seemed like overkill since the state we want to track is dead simple, we don't care about the success response (just that the request succeeded/failed), and it's hard to imagine any other page needing to know about that state. The advantage of this is we save a bunch of boilerplate, with the potential disadvantage that it's inconsistent with how we do it other places and violates separation of concerns. I'm fine with changing it to do it the Redux/redux-loop way if anyone feels strongly about it.
* Restart server
* Load app in browser and click "Register" link on main page
* Fill out the form with an invalid email and ensure an …
> Register new user account

- src/server/migrations/1587153603370-CreateRegionConfig.ts
- src/server/package.json
- src/server/src/app.module.ts
- src/server/src/region-configs/controllers/region-configs.controller.ts
- src/server/src/region-configs/entities/region-config.entity.ts
- src/server/src/region-configs/region-configs.module.ts
- src/server/src/region-configs/services/region-configs.service.ts
- src/shared/entities.d.ts
Add API endpoints for creating and listing region configs
Creating 3 region configs, two of which are for the same region (in these examples, Virginia):
```
16:00 $ http http://localhost:3003/api/region-configs/ name=Virginia countryCode=US regionCode=VA s3URI=s3://test/ing/1234 'Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNzZlYTk4OS1jYThjLTQyZWYtYjk4My00MWJmZTg4ZjAwMTIiLCJpZCI6ImI3NmVhOTg5LWNhOGMtNDJlZi1iOTgzLTQxYmZlODhmMDAxMiIsIm5hbWUiOiJQZXRlciBDIiwiZW1haWwiOiJwZXRlcmNAYXphdmVhLmNvbSIsImlzRW1haWxWZXJpZmllZFRlc3RpbmcxMjMiOnRydWUsImlhdCI6MTU4NzA1NjEwNSwiZXhwIjoxNTg3MjI4OTA1fQ.1fxUl7Z0lcbruDFgd-p-N4jt5rcYAJaKUv87fV-paDw'
HTTP/1.1 201 Created
Vary: Accept-Encoding
connection: close
content-length: 166
content-type: application/json; charset=utf-8
date: Fri, 17 Apr …
```
> Add API endpoints for creating and listing region configs

- package.json
- src/client/actions.ts
- src/client/actions/auth.ts
- src/client/actions/projects.ts
- src/client/actions/regionConfig.ts
- src/client/actions/user.ts
- src/client/reducers/auth.ts
- src/client/reducers/projects.ts
- src/client/reducers/regionConfig.ts
- src/client/reducers/user.ts
- yarn.lock
This PR brings in the library [`typesafe-actions`](https://github.com/piotrwitek/typesafe-actions) to reduce some repeated boilerplate in creating new Redux actions
N/A
I initially tried using `redux-act`, but ran into issues when combining it with `redux-loop`. `typesafe-actions` let me convert just the action side but stick to largely the same pattern already in place for the reducers, which dealt with the bulk of the boilerplate issues we were encountering.
Closes #95
> Reduce redux boilerplate

- deployment/README.md
- deployment/terraform/app.tf
- deployment/terraform/firewall.tf
- deployment/terraform/iam.tf
- deployment/terraform/storage.tf
- deployment/terraform/task-definitions/app_cli.json.tmpl
- deployment/terraform/variables.tf
- docker-compose.ci.yml
- docker-compose.yml
- scripts/cibuild
- scripts/cipublish
- scripts/infra
- src/manage/.dockerignore
- src/manage/Dockerfile
The following changes were made to support the staging CLI on AWS:
- Add TypeScript build output to `districtbuilder-manage` container image
- Create new ECR repositories
- ECS with Fargate
- Pass environment secrets to the ECS task definition
- Include log aggregation with CloudWatch Logs
Resolves #72 
- Verify that the Terraform plan output is clean
```bash
$ docker-compose -f docker-compose.ci.yml run --rm terraform
bash-5.0# ./scripts/infra plan
. . .
```
- Build and publish the container images
```bash
$ ./scripts/cibuild
. . .
$ ./scripts/cipublish
. . .
```
- See the output of the ECS task that I invoked out-of-band:
https://console.aws.amazon.com/ecs/home?region=us-east-1#/clusters/ecsStagingCluster/tasks/8943a75f-e053-4ea8-9e0a-a04e5cee840c/details
> Add Terraform configuration for staging CLI

- src/client/App.tsx
- src/client/actions.ts
- src/client/actions/auth.ts
- src/client/api.ts
- src/client/reducers.ts
- src/client/reducers/auth.ts
- src/client/screens/ForgotPasswordScreen.tsx
- src/client/screens/LoginScreen.tsx
- src/client/screens/ResetPasswordScreen.tsx
- src/server/migrations/1590169690909-ForgotPasswordTypes.ts
- src/server/src/auth/controllers/auth.controller.ts
- src/server/src/auth/entities/email-verification.entity.ts
- src/server/src/auth/services/auth.service.ts
- src/server/src/templates/passwordreset.hbs
- src/shared/constants.ts
Adds an email-based system for resetting a forgottten password.
- I combined the models for email verification & password registration into 1 model with a type column that differentiates them, which seemed more DRY but is different from how the sample repo I looked at for #74 did things.
- We weren't checking email verification links for expiration (:astonished:) so I added a 1 day expiration for both the password reset email & the initial verification email
- http://localhost:3003/forgot-password
Closes #76
> Forgot password workflow

- src/client/s3.ts
This was actually generating strings starting like https:/s3-buck-name/...
which worked when hosting from localhost but not when from staging
Switching from path.join which is meant for filepaths to url.resolve which
is designed for URIs fixed the issue
Closes #XXX
> Fix converting S3 URIs to HTTP URIs

- deployment/README.md
Documents the process for running migrations as ECS Fargate tasks. Instructions are currently for the `Staging` environment, but a similar approach can be used for the `Production` environment once it exists.
I made a fair bit of progress with both shell scripting using AWS CLI commands, and with adapting https://github.com/azavea/django-ecsmanage to run as a standalone script.
The shell script approach quickly ran into a lot of edge cases around parsing quotes, JSON, and token separators. It became clear that I was in the process of writing a parser so I abandoned that approach.
The `django-ecsmanage` approach was more successful but also ran into problems around parsing out arguments to `ecsmanage` vs. passing them along to ECS. I think this is a viable approach, but it required more …
> Document running RDS migrations using ECS Fargate

- src/server/src/districts/entities/geo-unit-topology.entity.ts
- src/server/src/districts/services/topology.service.ts
This function was scaling in overhead in a greater than linear fashion, making it take an unacceptably long time for larger states and seemingly never complete for PA.
```
$ ./scripts/dbshell
districtbuilder_database_1 is up-to-date
Recreating districtbuilder_server_1 ... done
psql (11.5 (Debian 11.5-3.pgdg90+1))
Type "help" for help.
districtbuilder=# UPDATE project SET districts_definition = '[1,1,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]' WHERE id = '697ab0b7-eb76-4afa-ab92-9d7913ad2ce9';
UPDATE 1
districtbuilder=# \q
$ http :3003/api/projects/697ab0b7-eb76-4afa-ab92-9d7913ad2ce9/export/geojson "Authorization:Bearer $TOKEN" > output.geojson
```
- Using the data file …
> Fix performance of GeoUnitHierarchy group function

- README.md
- docker-compose.yml
This provides documentation on how to configure a local `client` development server to use the `server` instance running in the staging environment on AWS.
This is currently difficult to test end-to-end due to stability issues with the `staging.districtbuilder.azavea.com` server on AWS, as mentioned in #155.
- Start up a development server and set `BASE_URL`:
```#bash
BASE_URL=https://staging.districtbuilder.azavea.com ./scripts/server
```
- Confirm in the script output that the remote server is being used for the development proxy.
- Open the client at http://localhost:3003/
- Attempt to login and verify that the POST request is going to CloudFront by checking the `via` HTTP response header.
Closes #55
> Document using server in AWS staging with local proxy

- Jenkinsfile
- deployment/terraform/task-definitions/app.json.tmpl
- docker-compose.yml
- scripts/migration
- scripts/test
- scripts/update
- scripts/yarn
- src/server/Dockerfile
Updates the Docker `ENTRYPOINT` for the `server` image to `yarn`, allowing us to start the container in production with the command `run start:prod`. We no longer need to override the entrypoint in the Fargate task definition.
This was mentioned in #142 when overriding the entrypoint to run `yarn` instead of the parent image `node` entrypoint.
- Confirm that the [Jenkins build](http://urbanappsci.internal.azavea.com/job/PublicMapping/job/districtbuilder/job/PR-180/3/) passes.
- Run `scripts/update` locally and confirm that all updates succeed.
- Run `scripts/test` locally and confirm that all tests run and continue to pass.
- Run `scripts/server` locally and confirm that all application containers come up, that the application is running in development mode, and that the application is …
> Set server image entrypoint to yarn

- src/server/src/auth/services/auth.service.ts
This DRYs up property checking and logging for sent emails in the auth service.
The upstream `@types/nodemailer` module [uses an `any` type](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b0cce3cd2cbc053400175af3ea84007076c2a775/types/nodemailer/index.d.ts#L22) for the email object that is returned from `sendEmail` in `@nestjs/mailer`. That doesn't give us much to work with and leaves us with the options of either wrapping the `EmailService` defined by the module and defining our own types, or refactoring the email logging to make its expected types and error checking more explicit.
Given that we're only reading the returned email object in the auth service, defining our own types felt like overkill in this situation. We opted to increase the visibility of how we're handling the …
> Refactor logging for sent emails

- src/client/reducers/projectData.ts
- src/server/src/projects/controllers/projects.controller.ts
When fetching the region config during project creation, all columns of the region config were being used in the query. This wasn't obvious from the types, since `dto.regionConfig` is a `RegionConfigIdDto`, which only has an `id` field defined, but the JavaScript object itself contains the additional info at runtime. This works fine in development, but in staging, the formatted `version` column wasn't exactly matching up with the parameter being passed along in the `SELECT` query. The fix implemented here is to explicitly only use the `id` parameter. 
Snuck in one unrelated, and very small change to properly address an ignored `no-case-declarations` eslint error.
This is a trivial change, and the error is only present on staging, so I think simply merging it and verifying it works in …
> Fix project creation on staging

- src/client/actions.ts
- src/client/actions/districtDrawing.ts
- src/client/actions/projectData.ts
- src/client/components/Map.tsx
- src/client/components/ProjectSidebar.tsx
- src/client/reducers.ts
- src/client/reducers/districtDrawing.ts
- src/client/reducers/projectData.ts
- src/client/screens/ProjectScreen.tsx
This is a straightforward refactor to create a new `districtDrawing` reducer/actions to contain functionality related to drawing districts (they've been moved over from `projectData`).
Follow testing instructions in #183 and ensure all district drawing capabilities are still functional.
Closes #187
> Move district drawing out of projectData

- src/client/components/Loading.tsx
- src/client/components/Map.tsx
- src/client/components/ProjectSidebar.tsx
- src/client/reducers/districtDrawing.ts
- src/client/reducers/projectData.ts
- src/client/resource.ts
- src/client/screens/ProjectScreen.tsx
Seamlessly rerender the map after editing districts
This PR is kind of a grab bag of changes to achieve the desired effect (how this should work was informed by discussions with @jfrankl )
It includes a change to the loading state (now "Loading..." is shown while waiting for district definition saving and loading new GeoJSON, though that was broken out into a separate `Loading.tsx` component so it can easily be improved later; see https://github.com/PublicMapping/districtbuilder/issues/194)
Part of making the seamless refresh functionality work required a reducer state change to both persist the current GeoJSON and show a loading state during the refresh (see change to `resource.ts`).
I added f562a11 to try to mitigate flicker (see that commit description). It's still slightly flickery …
> Seamlessly rerender the map after editing districts

- src/client/components/Map.tsx
- src/client/components/ProjectSidebar.tsx
- src/client/constants/colors.ts
- src/client/screens/ProjectScreen.tsx
This displays in-progress population changes in the district sidebar as geounits are being selected. The selected district shows increases in population, while any districts that geounits are being pulled from (including the unassigned district) show decreases in population. These increases and decreases are color coded accordingly (green/red).
* Also fixed a problem with the unassigned district being counted as a normal district when calculating population deviations
* Also fixed a problem with cancel button not clearing selection
* This is only currently working for the top-most geolevel, which is the only one we can currently select. I spent a lot of time attempting to get it to work with districts comprised of other geolevels too (via manually POSTing district definitions), but ran …
> Display intermediate changes to population in sidebar

- src/client/components/Map.tsx
- src/manage/src/commands/process-geojson.ts
- src/server/src/districts/services/topology.service.ts
- src/shared/entities.d.ts
We need min and max zoom level information on the client-side in order to perform zoom level restrictions. This PR extracts that information from the metadata that `tippecanoe` produces, and adds it to our static metadata.
- Because the format of the static metadata is changing, your current projects/regions will be invalid, delete them:
- `./scripts/dbshell`
- `truncate table region_config cascade;`
- Run `process-geojson` for a region, and then run `publish-region` for the output
- Verify that the `static-metadata.json` file contains new min/max zoom level information for each geolevel
- Create a new project with the newly published region config
- Verify that things behave as normal (the interface for `IStaticMetadata` changed, so I need to update a few places on …
> Add zoom level metadata

- src/client/components/map/RectangleSelectionTool.ts
Small bug fix that @kshepard noticed related to the newly-implemented rectangle selection tool when making multiple, separate selections.
This fix should make the rectangle selection tool work the same as the prototype.
Bug fix is in 63a5616
**Before**
**After**
* Make a selection using the rectangle tool, making sure to select at least one feature (mousing over the not yet selected feature should deselect it)
* Make a separate selection, mousing over and off the originally selected feature and newly selected features (original should stay selected, new features should be selected/unselected as per prototype)
> Fix rectangle selection tool bug with multiple selections

- src/manage/src/commands/process-geojson.ts
- src/manage/tsconfig.json
- src/server/src/districts/entities/geo-unit-topology.entity.ts
- src/shared/entities.d.ts
There were two more pieces of information needed in order to properly be able to draw and save districts:
1) We need a slimmed-down geounit hierarchy, so when we're operating with district definitions, we are able to properly find all base geounits for a given entity. This is needed when performing sidebar calculations, and is also needed for determining how many child geounits belong to a given geounit (for use during generation of district definitions when a geounit item needs to be exploded).
2) We need information about all parent geounit hierarchical ids on the vector tiles. For example, when a user selects a block, we need to know the parent blockgroup and county indices, so we can set them properly in the district definition.
To accomplish these, a new file has been generated: …
> Add missing static data needed for constructing districts

- src/client/components/map/Map.tsx
The cancel button wasn't deselecting geounits. This was fixed in #196, but it looks like it must have accidentally been rebased out in a subsequent PR. This PR is simply reapplying that one change (and making use of the new constant).
- Select some geounits on the map
- Click the cancel button and verify that the geounits on the map are deselected (without the change in this PR, the selection hangs out on the map).
> Fix cancel not deselecting geounits

- src/client/actions/districtDrawing.ts
- src/client/actions/projectData.ts
- src/client/components/MapHeader.tsx
- src/client/components/ProjectSidebar.tsx
- src/client/components/map/DefaultSelectionTool.ts
- src/client/components/map/Map.tsx
- src/client/components/map/RectangleSelectionTool.ts
- src/client/components/map/index.ts
- src/client/reducers/districtDrawing.ts
- src/client/reducers/projectData.ts
- src/client/screens/ProjectScreen.tsx
- src/shared/entities.d.ts
Add zoom geolevel restrictions and auto-saving when switching geolevels
There is a small amount of weirdness introduced in `reducers/districtDrawing.ts` where we need state held in `reducers/projectData.ts` to call the API function to save the updated district definition, so instead we kick off an action, passing the missing data along to the reducer that has the rest of the data to make the API call (previously we were getting around this by having the necessary data where the action is dispatched at the call site but now it needs to be called in two places to accommodate the auto-saving). I suppose this is the price we pay for encapsulation, but it does add complexity. The other alternative is to recombine the two reducers into one.
FWIW I still think the auto-saving is confusing and …
> Add zoom geolevel restrictions and auto-saving when switching geolevels

- src/client/components/map/Map.tsx
- src/client/components/map/index.ts
Also switches to display the correct labels for the selected geounit, instead of always using the county labels, fixing a `TODO`.
Closes #215
> Fix displaying map labels when option is unselected

- package.json
- src/client/components/DemographicsChart.tsx
- src/client/components/DemographicsTooltip.tsx
- src/client/components/ProjectSidebar.tsx
- src/client/constants/colors.ts
- yarn.lock
Adds a small bar chart with a tooltip to the race column of the project side bar
- Go to the project map screen. Behold the new chart & tooltip.
Closes #117
> Sidebar race demographics

- src/client/components/ProjectSidebar.tsx
- src/client/components/map/DefaultSelectionTool.ts
- src/client/components/map/Map.tsx
Updates the sidebar intermediate calculation to support cross-geolevel district definitions
- Select many different geounits across several geolevels and save them
- Verify that each time, the intermediate calculation matches up with the value that's returned after saving the district
Closes #202
> Update sidebar intermediate calculations to support multiple geolevels

- src/client/components/map/Map.tsx
- src/client/components/map/index.ts
- src/manage/src/commands/process-geojson.ts
Ports over the prototype code to abbreviate demographic labels.
- Rebuild & republish data for a state, then create a new project for that state
- Labels should be abbreviated
Closes #190
> Use humanized numbers for demographic labels

- src/manage/src/commands/process-geojson.ts
I'm suggesting a couple of changes to the way human-readable labels are generated from the prototype.
1. Change the way we determine the suffix to use for the label. The existing method was using `.length` to determine which label to use. This works for integers, but breaks down for decimal numbers. We don't expect to have decimals for population, but this covers us in case they show up unexpectedly, and makes this more robust in case we do. I instead use `log10` to more reliably determine the 000s bin.
2. Change the way we show hundreds of units, e.g. from 0.1m to 100k. The existing approach displays hundreds of thousands as tenths of millions. I've heard, and agree with, feedback that doing so makes it hard to compare between geounits, e.g. 90k vs. 0.1m is a 10k difference but the …
> Update human readable label processing

- package.json
- src/client/App.css
- src/client/components/DemographicsChart.tsx
- src/client/components/ProjectSidebar.tsx
- src/client/index.css
- src/client/screens/ProjectScreen.tsx
- src/client/theme.ts
- yarn.lock
The project view was scrolling. Only the table of districts in the sidebar should scroll. This PR fixes that issue and updates Theme UI.
I updated to a more recent version of Theme UI and am using the `ThemeUIStyleObject` TS definitions to save out reusable style definitions. See `ProjectSidebar.tsx`.
As discussed with @maurizi, I replaced the custom React components in `ProjectScreen.tsx`, which were being used exclusively for style purposes, with inline `sx` styles. In the future, we want to use the inline `sx` prop to style singular elements. For repeated styles, use something like:
```
import { ThemeUIStyleObject } from "theme-ui";
...
const style: ThemeUIStyleObject = {
number: { textAlign: "right" }
};
```
- Run the update script
- Go to a project with a large number of districts
- …
> Fix sidebar, update Theme UI

- src/client/components/map/Map.tsx
- src/client/components/map/index.ts
Updates the render order for map layers, placing labels on top.
I'm getting a confusing TypeScript error, which I am currently [ignoring](https://github.com/PublicMapping/districtbuilder/compare/develop...feature/jdf/layer-order#diff-12e430e5de057c50e51970797f34c617R77). @pcaisse I'd appreciate your help on understanding this and suggesting a potential fix.
- Load application
- View labels
- The labels should appear as they do in the attached screenshot, clear and "on top" of the other layers
Closes #249
> Fix map layer order, labels on top

- src/client/components/map/Map.tsx
When we receive a new GeoJSON file, it seems that we are updating the map twice using two nearly
identical blocks of code. I tested the application with one removed and I do not detect a change.
I removed the variation that seemed to be less flexible (used hardcoded names rather than variables).
- Confirm that the geojson updates as expected when the districts change
> Remove duplicated code

- src/client/components/ProjectSidebar.tsx
- src/client/components/map/Map.tsx
- src/client/screens/ProjectScreen.tsx
- src/manage/src/commands/process-geojson.ts
- src/server/src/districts/entities/geo-unit-topology.entity.ts
- src/shared/functions.ts
We need to be able to determine the child geounit ids for any given geounit. This is needed during selection when changing between geolevels. In order to accommodate this, the static files have been altered to reference their child geolevels, rather than all of them referencing the base geolevel.
I updates `Map.tsx` to use this new file structure for selecting child geounits when switching geolevels. Unfortunately, I was not able to fully remove the code in the `HACK` block, because map features (or more specifically `GeoUnits`) are used in a couple places here: `featuresToUnlockedGeoUnits`, and the dispatched `editSelectedGeounits` payload. I could not find an easy way to construct the `GeoUnits` from the information at hand, and it looks like we'll need to create an issue to address …
> Static data intermediate index changes

- CHANGELOG.md
- deployment/terraform/app.tf
- deployment/terraform/variables.tf
For each ECS service that supports the application, ensure that the Fargate platform version is specified. The default platform version if left unset is `LATEST`, which currently resolves to 1.3.0, but will soon resolve to 1.4.0.
- With these changes applied to the staging environment (they are currently applied), review the **Platform version** column of the `ecsStagingCluster ` [service listing](https://console.aws.amazon.com/ecs/home?region=us-east-1#/clusters/ecsStagingCluster/services)
- Ensure that the value listed is 1.4.0 vs. `LATEST`
Fixes https://github.com/PublicMapping/districtbuilder/issues/166
> Explicitly set Fargate platform version for ECS services

- src/client/components/Field.tsx
- src/client/screens/CreateProjectScreen.tsx
- src/client/theme.ts
- yarn.lock
Styles the Project creation page and fixes a disabled button issue.
- The wireframes show a disabled card for the districts, rather than hiding the whole card as above. If you would like me to do this, let me know!
- This is responsive, just because it's another form like "Sign up" that someone might want to fill out on a phone. I recognize that the meat of the app won't be usable that way, but seemed worthwhile here.
- I noticed some issues with the buttons I'd styled previously: the cursor was wrong and hover was showing for disabled buttons. Those issues are resolved here.
- I added some reusable `text` variant to our theme: `variant: "text.h1"` & the like. Some of them feel way too big and might not be useful, but I figured going by the established text scale still made sense. IDK, …
> Style Project Creation

- src/client/components/map/MapTooltip.tsx
It was possible for the mouse to get on top of the map tooltip, absorbing pointer events, and allowing text selection. This fixes the problem.
- Load up the map page
- Move your mouse really fast and try to catch it on top of the tooltip
- Realize that you can no longer do so
> Remove tooltip pointer events from map tooltip

- src/client/components/map/index.ts
Visually distinguish between geolevel lines, through width and opacity.
I want to refine this further after we implement #231 and fix the block simplification.
- Switch between counties, blockgroups/tracts, and blocks; confirm that each geolevel has its own style
> Add geolevels-specific line styles

- src/client/components/MapHeader.tsx
Fix labels
The option values were defaulting to the text contained inside the
`<option>` so once that was formatted differently (capitalized) the ids
no longer matched.
This sets the value explicitly to be the label id.
This is a small fixup from #303 
Select a label and ensure it's shown on the map correctly
Closes #331
> Fix labels

- CHANGELOG.md
- Jenkinsfile
- deployment/terraform/app.tf
- deployment/terraform/task-definitions/app.json.tmpl
- deployment/terraform/variables.tf
- docker-compose.ci.yml
- scripts/infra
- src/server/package.json
- src/server/src/app.module.ts
- src/server/src/common/constants.ts
- src/server/src/rollbar/rollbar-exception.filter.ts
- src/server/src/rollbar/rollbar.module.ts
- src/server/src/rollbar/rollbar.service.ts
- src/server/yarn.lock
Integrates Rollbar for server-side exception reporting and deploy reporting.
Server-scoped access tokens have been created for production and staging environments in Rollbar.
* Confirm the presence of a deploy notification in #district-builder, such as [this one](https://azavea.slack.com/archives/C6UD5FG3T/p1598035482037000).
* Confirm the presence of test error items in the Rollbar console, such as [this one](https://rollbar.com/Azavea/DistrictBuilder/items/6/).
* Verify that Rollbar account configuration, notifications, and teams / users reflect organizational standards and project needs.
Closes #73
> Add support for Rollbar

- src/client/actions/root.ts
- src/client/components/map/Map.tsx
- src/client/reducers/districtDrawing.ts
- src/client/reducers/projectData.ts
- src/client/screens/ProjectScreen.tsx
Fixes two issues:
- Resets project screen state stored in Redux when unmounting the `ProjectScreen` component 
- Fixes a warning about calling `setState` on an unmounted component
- ~[ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible~
- Follow the steps in #269 on `develop` to recreate the original issue
- Verify it is fixed on this branch
- Observe the lack of warnings in the console
Closes #269
Closes #233
> Reset project state

- CHANGELOG.md
- deployment/terraform/app.tf
- deployment/terraform/task-definitions/app.json.tmpl
- deployment/terraform/variables.tf
This PR adds `districtbuilder_state_count` in an effort to introduce a tunable parameter for scaling task memory.
Because Fargate has specific [supported configurations](https://aws.amazon.com/fargate/pricing/), my math takes a conservative approach where we put **1024 MiB** on the table, **3** states eat it up, and the next state will add another **1024 MiB**.
- Set `districtbuilder_state_count` to `3`. 
- Cycle Terraform.
```bash
~ memory                   = "2048" -> "3072" # forces replacement
```
- Set `districtbuilder_state_count` to `4`. 
- Cycle Terraform.
```bash
~ memory                   = "2048" -> "4096" # forces replacement
```
- Set `districtbuilder_state_count` to `1000`. 
- Cycle Terraform. 
- See that memory is capped to `8GB (1 vCPU)`.
```bash
~ memory …
```
> Provide math for scaling task memory with additional states

- src/client/components/map/MapTooltip.tsx
- src/manage/src/commands/process-geojson.ts
- Switch back to excluding voting info by default (we only have it for VA)
- Copy feature names into vector tiles if present
- Only include demographic info in map labels
- ~[ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible~
- `/scripts/manage process-geojson data/PA.geojson -o data/output-pa -n 12,4,4 -x 12,12,12`
Closes #281
> Update process-geojson script for latest data updates

- src/client/components/map/RectangleSelectionTool.ts
Fix selecting a single geounit with the rectangle select tool w/o dragging
- ~[ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible~
- Using the rectangle select tool, click and release over a geounit w/o dragging the cursor. On `develop` it will not be visually selected, on this branch it will be.
Closes #236
> Fix selecting a single geounit with the rectangle select tool w/o dragging

- src/client/screens/CreateProjectScreen.tsx
Order options from fewest districts to most districts, with custom always as the final option.
I used a spread operator to get access to the `sort` method. I was getting a typescript error without it. Please let me know if I did this right or if there is a preferable method.
- Create new map
- Select a state
- Confirm that the district types are in order from fewest to most districts
Closes #320
> Reorder district types

- src/client/components/map/Map.tsx
- src/client/components/map/index.ts
Increases the max zoom level of the map while maintaining the max zoom level for tiles.
To determine whether to enable a geolevel at a certain zoom level, we were checking that the current zoom level is smaller than the maxzoom for that geolevel. I needed to remove this to allow us to enable a geolevel even if we were zoomed past the maxzoom. Maxzoom, in this case, is about tile availability, not layer visibility.
To set the new maxzoom level for the map, I am adding 4 to the tile max zoom. This is a number that looked good to me for Philadelphia, but we might need to adjust after testing with additional states. I think a better long term solution would be to add this value to the state config, so we can adjust it on a case-by-case basis. I wasn't sure how to do that, but if people feel …
> Increase max zoom level

- src/client/components/DemographicsTooltip.tsx
- src/client/components/ProjectSidebar.tsx
- src/client/components/map/MapTooltip.tsx
- src/client/components/map/RectangleSelectionTool.ts
- src/client/components/map/index.ts
- src/client/functions.ts
- src/client/screens/ProjectScreen.tsx
A variety of performance improvements to the Project screen:
- Moved dynamic CSS properties out of Theme-UI `sx` property to avoid recalculating styles
- Added memoization in a few places
- Added a  separate throttle to the map tooltip for its _contents_ to provide smooth motion w/o needing as many recalculations of data
- Fixed up some event handlers that were getting disabled/enabled on every render
- ~[ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible~
Note that there is still a significant performance hit when the chrome dev tools are open (partially but not fully caused by https://github.com/PublicMapping/districtbuilder/issues/348). This seems to go away when the dev tools are closed so I'm not that worried about it.
I …
> Improve map screen performance

- package.json
- src/client/actions/districtDrawing.ts
- src/client/actions/projectData.ts
- src/client/components/MapHeader.tsx
- src/client/components/ProjectSidebar.tsx
- src/client/components/map/DefaultSelectionTool.ts
- src/client/components/map/Map.tsx
- src/client/components/map/MapTooltip.tsx
- src/client/components/map/RectangleSelectionTool.ts
- src/client/components/map/index.ts
- src/client/functions.ts
- src/client/reducers/auth.ts
- src/client/reducers/districtDrawing.ts
- src/client/reducers/projectData.ts
- src/client/s3.ts
- src/manage/src/commands/process-geojson.ts
- src/server/src/districts/entities/geo-unit-topology.entity.ts
- src/server/src/districts/services/topology.service.ts
- src/shared/entities.d.ts
- src/shared/functions.ts
- yarn.lock
Fix feature id conflict and avoid fitting map when splitting up a geounit
Includes moving frontend-only functions out of shared functions (see 4b6a55a) and upgrading prettier to support new operators used in the PR (namely optional chaining `?.`; see 5a0e4d1). FWIW I upgraded Prettier to the newest version (2.1+) and it reformatted tons of files so I decided to just upgrade to the latest minor release (looks like we'll have to add some configuration in the future to maintain our current formatting).
* Go to a project using DE test data
* Select the first (northernmost) county
* Switch to tracts
* All tracts in the county should be selected _without fitting the map bounds_
* Assign all tracts to a given district
* Check that all tracts (including tract 0) were be assigned
Closes #307 …
> Fix feature id conflict and avoid fitting map when splitting up a geounit

- src/server/src/districts/districts.module.ts
- src/server/src/districts/services/topology.service.ts
- src/server/src/healthcheck/healthcheck.controller.ts
- src/server/src/healthcheck/healthcheck.module.ts
- src/server/src/healthcheck/topology-loaded.indicator.ts
- src/server/src/projects/projects.module.ts
- src/server/src/region-configs/region-configs.module.ts
Adds an indicator to the healthcheck for whether all the layers in the topology service have loaded
Still loading:
Fully loaded:
The level of detail provided here may be too much, especially as we ramp up the number of states, but I thought it might prove helpful to err on the side of being too detailed for now given that we plan to launch with a small number.
- http://localhost:3005/healthcheck should return a 503 status code after starting the service while it is still downloading and processing TopoJSON
- http://localhost:3005/healthcheck should start to return `true` for individual layers as they finish downloading
- http://localhost:3005/healthcheck should return a 200 status code once all layers have finished downloading
Closes #254
> Healthcheck topology service

- src/client/components/MapHeader.tsx
- src/client/components/map/Map.tsx
- src/client/components/map/MapMessage.tsx
The following criteria have been implemented in order to address some user friction around working with zoom level restricted geolevels:
* When a user selects a restricted geolevel and zooms out past the min-zoom, show
an explanatory message on the map
* Also when this happens, the blocks geolevel button is still
active and indicates blocks are still selected (rather than being grayed out)
* When zoomed out, if a user selects a non-restricted geolevel the restricted
geolevel button is deactivated
* If a user has a restricted geounit selected, the user can zoom out past the
min-zoom (rather than be limited to it) and the selection is maintained
- Browse to a project
- Zoom in and out, selecting different geolevels, and making various selections
- Ensure the criteria described in the issue …
> Improve UX for zooming with restricted geolevels

- src/client/screens/RegistrationScreen.tsx
- src/client/screens/ResetPasswordScreen.tsx
Removes the confirm password fields from registration and password reset screens, as per issue #312 
Closes #312
> Remove confirm password fields

- CHANGELOG.md
- README.md
- deployment/terraform/app.tf
- deployment/terraform/cdn.tf
- deployment/terraform/dns.tf
- deployment/terraform/iam.tf
- deployment/terraform/variables.tf
- src/server/src/common/constants.ts
These changes support us migrating DNS records from GoDaddy to AWS Route 53, and using `districtbuilder.org` DNS records for the application. The application will now be hosted at `app.staging.districtbuilder.org` and `app.districtbuilder.org`.
Production records have not been altered yet. Staging NS records have been added to GoDaddy for testing.
- Verify that the staging application is functioning at https://app.staging.districtbuilder.org/
- Verify that all `districtbuilder.org` records have been copied from GoDaddy to the `districtbuilder.org` domain in Route 53.
Connects #326
> Migrate DNS records to districtbuilder.org hosted zones

- package.json
- public/index.html
- src/client/GTM.ts
- src/client/store.ts
- yarn.lock
Adds GTM, as well as `redux-beacon` and wired up a few basic tagging events.
I went and added `redux-beacon`, because it didn't look like the vanilla GTM setup was really going to give us anything useful. I only wired up a few events for now so we'll be able to track what page a user loads and when they save a district. It will be straightforward to add more events as desired.
- See the issue for where to find credentials for logging in to Google Tag Manager
- Open the `DistrictBuilder App` container
- Click the `Preview` button
- Load up the DistrictBuilder app in another tab. Enabling the `Preview` mode will give you a little window like in the screenshot above.
- Browse around the app and ensure you are seeing some events triggered (as is seen in the screenshot)
- …
> Add Google Tag Manager

- src/client/components/ProjectSidebar.tsx
- src/client/components/map/RectangleSelectionTool.ts
When using the rectangle select, geounits are highlighted when they fall inside the rectangle but are not un-highlighted when the rectangle moves and they fall outside. This leaves a trail of highlighting everywhere the rectangle has been causing shapes to be highlighted that shouldn't be. This PR fixes that, and also adds another unrelated, but tiny change: removing the unused `Pol.` column in the sidebar.
The reason it wasn't working is because `geoUnitsForLevel` was being shadowed in the `forEach`, and was then essentially being compared with itself in the code within the block, so there would never be a difference. I initially just removed it from the `forEach`, but then decided to remove the iteration of geolevels completely, since this should really only be a relevant codepath for a …
> Fix rectangle highlight trail and hide Pol. column

- src/client/components/map/MapTooltip.tsx
We don't want to add "county" after the feature name for city-counties
- Hovering over city-counties on a VA project should omit the "County" in the label
Closes #281
> Account for independent city-counties in map tooltip label

- src/client/components/ProjectSidebar.tsx
When I removed the `Pol.` column, I only managed to removed it from the header. This also removes the associated column.
Trivial change, I'm just going to merge it when the build passes.
> Fix bug with removed Pol. column

- src/client/GTM.ts
- src/client/actions/districtDrawing.ts
- src/client/actions/projectData.ts
- src/client/api.ts
- src/client/components/ProjectSidebar.tsx
- src/client/components/map/Map.tsx
- src/client/components/map/MapMessage.tsx
- src/client/components/map/MapTooltip.tsx
- src/client/functions.ts
- src/client/reducers.ts
- src/client/reducers/districtDrawing.ts
- src/client/reducers/project.ts
- src/client/reducers/projectData.ts
- src/client/s3.ts
- src/client/screens/ProjectScreen.tsx
- src/client/types.d.ts
Fix sidebar flicker + various refactors
This PR contains a lot of refactors, some of which turned out to not be strictly necessary but seemed valuable enough to include anyway (eg. making `getSidebarRows` into a component). The most notable example of this is using `reduceReducers` to combine district drawing state with project state. Having them be separate has required some kludgy workarounds in the past (see the now defunct `saveDistrictsDefinition`) in order to share data between them. I thought at one point that doing a single state update was important to avoid flicker, but that later turned out not to be true. In any case, this is a positive change (IMO) and will give us flexibility to avoid similar kludges in the future.
This also includes a large refactor of the `projectData` …
> Fix sidebar flicker

- src/client/components/ProjectSidebar.tsx
- src/client/theme.ts
Fixes a horizontal scrollbar for the sidebar in the Map view. I also styled disabled states for buttons to be more clearly disabled. The hover state had been fixed in a previous PR, so I reduced opacity and changed the color to generally be gray.
Firefox
Chrome
Disabled primary button
- Jeff and I noticed that the Political affiliations column was left in the table, so I also removed that here.
- The min-width of the sidebar needed to be slightly wider.
- `git pull`
- View the login page
- In `LoginScreen.tsx`, locate `<Button type="submit">Log in</Button>`. Add a `disabled` property to this button and you'll see the new styles for the primary button type. View all of the button variants in their disabled state:
- secondary
- ghost (change the background of the containing Box to '#000')
- …
> Style disabled for buttons better and fix sidebar width in Firefox

- CHANGELOG.md
- deployment/terraform/app.tf
- deployment/terraform/variables.tf
To resolve failed ECS health checks due to the application not being ready I've added a parameter to allow us to set a base grace period for health checks that gets multiplied by the number of states were loading.
Resolves #392 
Adjust the `health_check_grace_period_per_state` in the staging tfvars file and then see the resulting Terraform plan.
```bash
$ docker-compose -f docker-compose.ci.yml run --rm terraform
bash-5.0# export GIT_COMMIT=6d9dec8 
bash-5.0# ./scripts/infra plan
. . .
Terraform will perform the following actions:
~ resource "aws_ecs_service" "app" {
cluster                            = "arn:aws:ecs:us-east-1:273766372266:cluster/ecsStagingCluster"
deployment_maximum_percent         = 200
deployment_minimum_healthy_percent = 100
desired_count                      = 1 …
```
> Add ability to tune health check grace period for ECS service

- src/server/src/rollbar/rollbar-exception.filter.ts
These are "normal" exceptions that don't necessarily indicate an error with the website, and as such it would be wasteful to report them to Rollbar
I grepped the server codebase for all errors we're throwing to determine if we needed to whitelist any exception not already called out in #388 but I didn't see any.
- I added a `console.log` above the call to `this.rollbar.error` to verify exceptions were being filtered appropriately
Closes #388
> Whitelist a few exception types from being reported to Rollbar

- src/client/components/map/Map.tsx
- src/client/components/map/index.ts
Adds a custom basemap from Mapbox Studio.
To use a Mapbox Studio basemap, I had to change the way we define a style in the application. Instead of generating a style json, we are now using a style from Mapbox Studio, and we use `addSource` and `addLayer` to add additional elements. We were using that technique in some places already, so now it is more consistent. I made a `generateMapLayers` function to move this outside of the crowded `Map.tsx` file, but let me know if you'd prefer a different approach.
I am using a filter to only show labels for the selected region. Right now this will work for any state, but when we support other types of regions, we'll need to make some minor changes. I figure there are a lot of little things like that.
I think this is in a good enough place to …
> Add basemap

- src/server/src/districts/services/topology.service.ts
S3 data was being cached on startup only. If a new region was added, it would still be selectable and would work, but the data needed to be pulled from S3 on each operation. This makes it so if we need to pull a new data layer, we cache it for later use.
There are a couple different ways to test this PR, so do what you like best:
* Process/publish a new region
* or Manually insert a new region row into your db
* or (fastest way) find the constructor in `topology.service.ts` and comment out all of the contents (lines 29-39), this is what does the initial cache.
Then load a project with a new region that will need to be pulled down. It'll be slow the first time, since it fetches it from S3. Then reload the page, or save districts, and it should be fast all subsequent times.
> Cache new layers that are encountered after load

- src/client/components/ProjectSidebar.tsx
- src/client/components/map/MapTooltip.tsx
- src/client/screens/CreateProjectScreen.tsx
The data processing pipeline now passes through the "County" suffixes, so we no longer need to add them to the label after the fact. I also performed some additional minor text changes:
* On map page, change button text from Approve to Accept for pending changes
* On create map page, change button text from Create Project to Create Map
* On create map page, change header text from New Project to New Map
* On create map page, under Custom, change "Define other types of districts" to "Define a custom number of districts"
- Make sure you have loaded one of the new region files that has county suffixes passed through
- Verify that you are not seeing doubled-up county suffixes
- Verify the minor text changes described in the overview are present
> Update for county suffixes

- src/client/components/map/MapTooltip.tsx
When hovering away from the map, the tooltip was still persisting. This fixes it.
The reason this was happening seemed to stem from the fact that `setFeature` was being called directly in this case rather than through `throttledSetFeature`, and there was a race condition where a throttled request would come through afterwards and make the tooltip visible. The fix here routes everything through `throttledSetFeature` so this won't happen.
- Load up a project
- Zoom in so the extent of the geounits is flush with the map bounds (this is how to reproduce the bug)
- Hover over the map and outside of the map and verify that the tooltip disappears when it should
> Fix tooltip persisting on hover away

- src/client/components/MapHeader.tsx
- src/client/theme.ts
Fix for outlined buttons on the map getting a weird button color on hover.
- I also removed some extraneous styles and put the icon buttons closer to one another (I'd had a 1px gap before that looked a little strange in retrospect).
- `git pull`
- Go to the map page
- Interact with the outlined buttons in the toolbar, the text should remain gray and not turn white on hover / active.
Closes #XXX
> Fix outlined button text on hover

- src/client/components/MapHeader.tsx
- src/client/components/map/index.ts
- src/client/screens/ProjectScreen.tsx
A user can enable block mode without zooming in. This makes it more clear that the block editing mode is available. Previously, when this button was disabled by default, it sent mixed signals—maybe this feature isn't built yet, or maybe I don't have access to it for a difficult-to-change reason. Depending on a tooltip to straighten that out wasn't enough.
Now a user can immediately click on the blocks button if they want. And they'll receive an appropriate warning to let them know the takeoffs of block editing. 
- Create a new project
- In the new project, confirm that the "blocks" button visually appears enabled
- Click on the "blocks" button; you should see the blocks modal; click cancel
- Select a county on the map
- Confirm that the "blocks" button looks disabled
- Hover over the …
> Blocks button enabled by default

- src/client/App.css
- src/client/components/DemographicsTooltip.tsx
- src/client/components/map/MapTooltip.tsx
- src/client/theme.ts
Style cleanup on the map tooltip. Tighten line-height to make it easier to compare bars in race chart, set fixed size so the size of the tooltip doesn't change as much, making it easier to quickly scan as it changes. I made the colors match for the map tool tips and tooltips that appear elsewhere in the application. I also removed the repositioning when the tooltip approaches the side of the screen (more on that in the notes).
@maurizi I removed the tooltip repositioning in this PR. I wanted to address that since the repositioning was a feature I had requested and I believe you implemented. While this feature made sense to me in abstract, in practice I found it annoying to have the tooltip jump around unexpectedly. I think you did a great job implementing it, and I wanted to be clear that …
> Style pass on map tooltip

- CHANGELOG.md
- src/client/actions/districtDrawing.ts
- src/client/components/map/DefaultSelectionTool.ts
- src/client/components/map/Map.tsx
- src/client/components/map/RectangleSelectionTool.ts
- src/client/components/map/index.ts
- src/client/functions.ts
- src/client/reducers/districtDrawing.ts
- src/shared/entities.d.ts
Allow for selecting partially locked districts.
Selecting/deselecting locked counties
Partial selection with locked blocks (messaging will be added to improve the UX of this in https://github.com/PublicMapping/districtbuilder/issues/417)
There were a couple of existing bugs that I ran into which had to be smoothed out to get everything working:
* For the rectangle selection tool, `getFeaturesInBoundingBox` only returned features at the currently selected geolevel, though since we made the change to allow for working with multiple levels at once, we need to get all features from all levels (that's what the new `getAllSelectedFeatures` does)
* `isGeoUnitLocked` wasn't quite working as advertised and would quit recursing too early if the district definition was jagged which could result in …
> Allow for selecting partially locked districts

- CHANGELOG.md
- deployment/terraform/config.tf
- deployment/terraform/storage.tf
- deployment/terraform/variables.tf
It appears as though something changed with Terraform's ability to detect out-of-band grants, or perhaps a CloudFront service level change led to different behaviors than before (they recently added real-time logs). That's left us with a handful of CloudFront logs in S3 from May, but nothing between May and now.
When logging to S3 from CloudFront is configured via the AWS console, a specific set of grants that allow CloudFront to interact with an S3 bucket are added. These grants appear to get wiped away by Terraform unless they are explicitly defined in the Terraform configuration.
The changes in this PR aim to persist the two grants (one is the AWS canonical user ID, and the other is the CloudFront canonical user ID) in the Terraform project.
- Disable CloudFront logging for the staging …
> Fix S3 permissions to allow CloudFront logging

- CHANGELOG.md
- Jenkinsfile
- deployment/terraform/task-definitions/app.json.tmpl
- src/server/ormconfig.js
- src/server/src/main.ts
Reduces the logging level, disables SQL query logging, and removes color from log output for non-development (i.e. ECS) environments.
There is still a little apparent cruft from context like the `[Nest]` blocks. Because there are a few components that create logs in this application, I think the `[Nest]` blocks are actually helpful for distinguishing what are Nest application logs and what are not, like TypeORM logs.
The timestamps are actually extraneous here since ECS already timestamps logs, but we'd need to extend the NestJS logger and implement our own custom logger with our own logging format if we wanted to get rid of those. That's totally doable but felt like overkill in this situation.
Updated task definition has been deployed to staging when this PR was marked ready for review. …
> Reduce noise in log output

- CHANGELOG.md
- docker-compose.yml
Upgrades the `docker-compose.yml` `database` service definition to use PostgreSQL 12.2 and PostGIS 3.
RDS supports PostgreSQL 12.2 and 12.3, so we'll be able to have version parity between development and staging / production.
- Run the following commands to backup the PostgreSQL 11 database and restore it to PostgreSQL 12:
```#bash
git checkout develop
docker-compose exec -T database bash -c 'pg_dumpall -U $POSTGRES_USER' > dump.sql
git checkout feature/cek/postgresql-12-development
docker-compose up -dV database
docker-compose exec -T database bash -c 'psql -U $POSTGRES_USER' < dump.sql
```
- Run `./scripts/update` to build all of the application containers.
- Run `./scripts/migration` and confirm that no migrations need to be run.
- Run `./scripts/server` and verify that you are able …
> Upgrade development database to PostgreSQL 12.2 and PostGIS 3

- CHANGELOG.md
- src/client/components/ProjectHeader.tsx
- src/client/components/ProjectSidebar.tsx
- src/client/theme.ts
Makes a larger click area and adds a hover state to the lock button in the sidebar. I also added a slight transition for button hover states and applied our `:focus` state to the logo link in the project header. 
- I added a new `icon`button variant for these. 
- The width of the sidebar had to get a bit wider in order to fit the new width of the button.
- `git pull`
- Enter a map
- Hover on rows in the sidebar. Notice that the lock icon appears.
- Hover on a lock icon to see its `:hover` state. Click to see the `:active` state.
- Note there is more padding about the the icon so it's easier to click.
- Take a look at this in Firefox. There shouldn't be a horizontal scroll bar in the sidebar.
Closes #424
> Bigger click area and hover state for lock button

- CHANGELOG.md
- deployment/terraform/app.tf
- deployment/terraform/athena.tf
- deployment/terraform/iam.tf
This PR adds the ability to query ALB logs with Athena by codifying the following AWS guides:
- [Access logs for your Application Load Balancer → Enable access logging](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#enable-access-logging)
- [Querying Application Load Balancer Logs → Create ALB Table](https://docs.aws.amazon.com/athena/latest/ug/application-load-balancer-logs.html#create-alb-table)
Connects #428 
See that the results of this basic query look right (`client_ip` has been redacted).
```sql
SELECT *
FROM stg_alb_logs LIMIT 5;
```
[d2063156-1045-4c1a-86a8-238bef2c1db2.csv.zip](https://github.com/PublicMapping/districtbuilder/files/5270179/d2063156-1045-4c1a-86a8-238bef2c1db2.csv.zip)
> Add the ability to query ALB logs with Athena

- CHANGELOG.md
- src/client/components/map/RectangleSelectionTool.ts
A bug was introduced in PR #420 that caused the set of highlighted geounits to be continuously reset when dragging the rectangle, resulting in the tooltip never showing the aggregated counts of all highlighted geounits.
Before:
After: 
- Interact with the rectangle selection tool and ensure you see aggregated counts while you're dragging
> Fix problem with highlighted resetting

- CHANGELOG.md
- load-tests/README.md
- load-tests/docker-compose.yml
- load-tests/pa-50-districts.js
- src/server/src/main.ts
> Keep-alive, when enabled, enables the load balancer to reuse back-end connections until the keep-alive timeout expires. To ensure that the load balancer is responsible for closing the connections to your instance, make sure that the value you set for the HTTP keep-alive time is greater than the idle timeout setting configured for your load balancer.
The [default keep-alive timeout](https://nodejs.org/api/http.html#http_server_keepalivetimeout) for the Node http.Server is 5 seconds. The [default idle timeout](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb#idle_timeout) for the ALB is 60 seconds. 
The ALB is opening connections for reuse, the Node http.Server closes that connection, and then the ALB tries to communicate over the closed connection which …
> Set keep-alive timeout higher than ALB idle timeout

- .eslintrc.js
- CHANGELOG.md
- package.json
- src/client/components/ProjectSidebar.tsx
- src/client/components/map/Map.tsx
- src/client/components/map/MapTooltip.tsx
- src/client/components/map/RectangleSelectionTool.ts
- src/client/components/map/index.ts
- src/client/functions.ts
- src/client/s3.ts
- src/client/screens/ProjectScreen.tsx
- src/client/types.d.ts
- src/client/worker-functions.ts
- src/client/worker.mock.js
- src/client/worker.ts
- src/react-app-env.d.ts
- src/shared/functions.ts
- tsconfig.json
- yarn.lock
Calculate sidebar updates in real-time as rectangle tool is dragged, via use of web workers
* This is based off of #395, and much of the base web worker setup has remained intact
* Unfortunately, I needed to squash everything here down, since it was a long-running branch that weathered a large amount of PRs, and the constant rebasing and merging wreaked havoc on the commit log. However, I'll add some key notes here for various changes I needed to make.
* Added short circuit to rectangle selection tool when features are exactly the same
* ProjectSidebar memoization wasn't working correctly, because `useMemo` wasn't properly able to determine equality of the dependencies. I overrode a comparator here and used lodash's `isEqual`, which worked. But then I ended up instead moving the …
> Use web workers for real-time demographic updates

- src/client/components/ProjectHeader.tsx
We want to do a production release soon, but don't want to deploy the `Share` button, since we have some updates we want to make to it first. This removes the button from the page. We can revert this commit after deploying.
- Load the map page and ensure the `Share` button doesn't show up, and the page remains functional
> Temporarily remove share button

- src/client/reducers/districtDrawing.ts
@tgilcrest noted this issue on Slack:
> Something else I noticed:
> Accept
> Undo Accept
> Make another selection
> Undo the selection
> Redo
> Undo
> Redo
> Redo (5) combines Select (3) and Accept (1) into the same action. So any subsequent undo/redo (6,7) will do both.
> I would expect redo (5) to just make the selection (3) again, and it should not be possible not be possible to Accept via redoing, > because the Accept (1) action should have been "overwritten" in the history of actions by the Select (3). (edited) 
> ![image](https://user-images.githubusercontent.com/4432106/95340680-70bb6780-0883-11eb-86f4-357492e9abd3.png)
This fixes it by clearing the stored project state when we replace the undo stack with `pushState`
- ~[ ] Description of PR is in an appropriate section of …
> Clear current project district definition & geojson data when adding a new undo state

- CHANGELOG.md
- src/client/components/MapHeader.tsx
- src/client/components/ProjectHeader.tsx
- src/client/components/ProjectSidebar.tsx
- src/client/components/ProjectSidebarHeader.tsx
- src/client/components/map/AdvancedEditingModal.tsx
- src/client/components/map/Map.tsx
- src/client/screens/ProjectScreen.tsx
- src/server/src/projects/controllers/projects.controller.ts
- src/shared/entities.d.ts
Updates the UX of the project screen when in readonly mode, as per issue #455 
- The project page should continue to function as normal when editing your own project
- The project page should match the changes outlined in #455 when viewing someone else's project, whether or not you are logged in
Closes #455
> Update Project Screen read-only view

- CHANGELOG.md
- README.md
- src/manage/README.md
- src/manage/src/commands/process-geojson.ts
- src/manage/src/commands/publish-region.ts
- src/manage/src/commands/update-region.ts
When we receive updates to the data, we'd like to be able to easily push updates to S3. In order to ensure this goes smoothly, the new data must be sorted in the exact order as the old data. In addition, any structural changes to the data (e.g. blocks shifting from one county to another) must signal an error, as this would cause a hierarchy difference which would require a more involved migration. The `process-geojson` command has been updated to take an optional published region reference, which will be pulled down and used to sort the new data and check for inconsistencies. A new command, `update-region` has also been added, which will push this processed data up to the desired S3 location without making any database changes.
On the left is my project before updating the data. On the …
> Update data tooling

- CHANGELOG.md
- deployment/terraform/task-definitions/app.json.tmpl
- docker-compose.yml
We set this in the CLI for processing files, in order to deal with processing large files in memory. When loading up Texas, we also
need this set on the server, or else it fails to load the topojson into memory.
* Insert Texas into your DB
* `./scripts/dbshell`
* `INSERT INTO "region_config"("name", "country_code", "region_code", "s3_uri", "version") VALUES ('Texas','US','TX','s3://global-districtbuilder-dev-us-east-1/regions/US/TX/2020-10-12T16:56:43.962Z/','2020-10-12T16:56:43.962Z');`
* `./scripts/server`
* It may take a minute to load, but you shouldn't see any memory errors in the server log
* You should be able to create a map with Texas data
> Specify max-old-space-size on server

- CHANGELOG.md
- src/client/components/Field.tsx
- src/client/screens/CreateProjectScreen.tsx
This PR adds some descriptive copy underneath labels on the Create Map page.
- I made these descriptions accessible using `aria-describedby` rather than putting them directly in the label and tested with Mac OS's [Voiceover](https://webaim.org/articles/voiceover/) software.
- Fixed an accessibility issue with the radio selects by adding a fieldset container around them and changing their label to `<legend>`.
- `git pull`
- Log in, click "New map" button
- Note new descriptive copy under each label
Closes #430
> Add microcopy to Create Project fields

- CHANGELOG.md
- deployment/terraform/database.tf
Add support for [name_prefix](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_parameter_group#name_prefix) and the [create_before_destroy](https://www.terraform.io/docs/configuration/resources.html#create_before_destroy) lifecycle customization so that a new parameter group is created and applied before disposing of the old one when making modifications that require a new resource.
Connects #340 
I bumped the `rds_engine_version` and `rds_parameter_group_family` variables in the `.tfvars` file. Then, I ran Terraform to create a new parameter group to use in the PostgreSQL 12 upgrade.
<details>
<summary>Details</summary>
```bash
------------------------------------------------------------------------
An execution plan has been generated and is shown below. …
```
> Make it possible to swap out the RDS DB parameter group

- CHANGELOG.md
- src/client/components/MapHeader.tsx
- src/client/components/Tour.tsx
- src/client/components/map/RectangleSelectionTool.ts
- src/client/functions.ts
- src/manage/README.md
- src/manage/src/commands/process-geojson.ts
We would like to configure a region for Dane County, WI, and more generally would like to be able to configure single-county regions. This updates the processing script to be able to supply a prefix inclusion filter, to allow only blocks with matching FIPS code prefixes to be processed. Because the region is only a single county, we also don't need to allow selection of the "county" geolevel in the UI (the tour was also updated to reflect this change). Similarly, due to its smaller size, we can safely always display all blocks, so special handling of the base geolevel can be lifted.
I didn't go overboard with logic in attempting to handle every scenario related to when a geolevel needs special handling. The normal case that we were already handling was for when the base geolevel is …
> Add support for single county region

- src/client/components/MapHeader.tsx
Fixes the disabled Block button looking strange by retaining a right border on the Block Groups button.
- `git pull`
- Go into a map. The Counties button should be selected. 
- Click on a county. The Blocks button should be disabled.
- Interact with the Block Groups button to see that the hover looks right.
- Now click "Cancel" or "Accept.
- Click the Blocks button and zoom in to select a block. The Block Groups and Counties buttons should be disabled.
Closes #447
> Ensure that disabled block button doesn't lose left border

- deployment/terraform/variables.tf
Ensure that these defaults reflect the current state of the DistrictBuilder AWS environments.
Connects #341
---
**Testing**
Review the changes and ensure that they align with the [RDS configuration](https://console.aws.amazon.com/rds/home?region=us-east-1#database:id=districtbuilder-production;is-cluster=false;tab=configuration).
> Update PostgreSQL for RDS engine default to 12.x

- CHANGELOG.md
- src/server/src/projects/entities/create-project.dto.ts
There was an error when creating a new map: `property regionConfig should not exist`. This was happening, because `forbidNonWhitelisted` validation was turned on in this commit: https://github.com/PublicMapping/districtbuilder/commit/f9238245471b413b81b724dc38cd35590056226b, but the `regionConfig` property didn't have a validation decorator, so wasn't whitelisted. The fix implemented here adds a simple validation decorator to `regionConfig`, just verifying that it's present.
- Attempt to create a new map. This wasn't working beforehand, but should succeed now.
Closes #494
> Fix region config validation error

- CHANGELOG.md
- src/client/actions/districtDrawing.ts
- src/client/actions/projectData.ts
- src/client/components/ProjectHeader.tsx
- src/client/components/ProjectSidebarHeader.tsx
- src/client/components/map/Map.tsx
- src/client/components/map/MapMessage.tsx
- src/client/components/map/MapTooltip.tsx
- src/client/reducers/districtDrawing.ts
- src/client/reducers/projectData.ts
- src/client/reducers/undoRedo.ts
- src/client/screens/ProjectScreen.tsx
This change makes undo/redo work with effects so that we can go backwards and forwards to previously saved map states. 
This was really quite hard to get working... I've added longer comments around the trickier parts of this to try to make things more clear.
The big change in terms of what state we represent is to have both a `state` and optionally `effect` represented to undo/redo saves. We also now need to keep track of `districtsDefinition` in our `UndoableState` to allow for undoing/redoing of saves. Most of the rest of the code is state/effect management in the reducers as you might suspect.
There were several non-obvious things that tripped me up along the way to getting this working, such as how we were always clearing the selected geounits after a save (this worked fine until we …
> Allow saving with undo/redo

- src/server/src/projects/controllers/projects.controller.ts
We want headers on the CSV export. An [example at the Census Bureau](https://www.census.gov/geographies/mapping-files/2018/dec/rdo/2018-state-legislative-bef.html) uses `BLOCKID` and `DISTRICT`, so that's what we're going with here.
I made the "BLOCKID" column dynamic, in case blocks aren't the base geounit. For example, if precincts are the base geounit, it will be set to "PRECINCTID".
- Load up a map
- Click the export to CSV button
- Ensure the CSV has headers of: "BLOCKID,DISTRICT"
Closes #502
> Add CSV export headers

- src/client/actions/projectData.ts
- src/client/components/ProjectSidebar.tsx
- src/client/components/map/Map.tsx
- src/client/components/map/index.ts
- src/client/reducers/districtDrawing.ts
- src/client/reducers/projectData.ts
- src/server/migrations/1606339829204-update_locked_districts.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/shared/entities.d.ts
This persists locking districts to the backend, including as part of undo/redo
Saving:
Undo/redo
Closes #405
> Persist locking districts

- src/client/screens/HomeScreen.tsx
There was a mention of "14 days" in the email verification copy, but it's not tied to any logic and isn't actually the case, so we're removing it. 
- Log in with a user that has an unverified email
- On the home page, notice that the copy no longer refers to the "14 days" time frame.
Closes #518
> Update email verification copy

- CHANGELOG.md
- src/client/actions/districtDrawing.ts
- src/client/components/map/FindMenu.tsx
- src/client/components/map/Map.tsx
- src/client/reducers/districtDrawing.ts
- src/client/reducers/projectData.ts
Add find non-contiguous option to find menu
Closes #517
> Add find non-contiguous option to find menu

- CHANGELOG.md
- package.json
- src/client/api.ts
- src/client/screens/HomeScreen.tsx
- src/server/migrations/1607960574923-add_last_updated_to_projects.ts
- src/server/src/projects/entities/project.entity.ts
- src/shared/entities.d.ts
- yarn.lock
Adds last updated column to the `projects` table and displays this information on the user's home page map list by making use of `timeago`. Not listed in the A.C., but I also went ahead and sorted the maps by descending last updated timestamp in order to help users find their most recently edited maps.
* In planning, we agreed to not allow null last updated timestamps, and to just set all existing timestamps to `NOW`: that's what has been done here.
* I came across `UpdateDateColumn`, which made my life a lot easier (was trying to do it manually first). This decorator will automatically set the value to the current timestamp on all updates. We should definitely use it for all future last updated columns.
- `./scripts/update`, `./scripts/server`
- Visit the homepage, and all your maps …
> Add last updated date to map list

- CHANGELOG.md
- src/client/components/ProjectSidebar.tsx
- src/server/src/auth/guards/jwt-auth.guard.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/projects/entities/project.entity.ts
District lock status was showing up in the sidebar and the map in read-only mode, where it wasn't desired.
Read only:
Owner view:
The sidebar was straightforward, but getting the map layer to not show the locked status was a little trickier than expected. The least invasive and future-proof approach seemed to be stripping the data at the source: the Project `getOne` function in the controller. However in order to get this to work, I needed to add a new Auth guard that would allow user information to be available in that function if present. This is because using the standard Auth guard will deny unauthenticated requests, and using no auth guard will not pass along any user information to the function. Once that was worked out, the new logic is simply removing the locking information from …
> Don't show district lock status on read-only maps

- src/server/src/projects/controllers/projects.controller.ts
The project list endpoint was only filtering by user id when the URL exactly matched `/api/projects`. We recently began passing a sort parameter to this URL, and the match was no longer succeeding, causing user id filtering to not occur. This changes the match logic to use the route path rather than the URL for matching, since that doesn't include parameters.
- This is a trivial change that I'm going to merge as soon as CI passes
> Fix project user filtering

- CHANGELOG.md
- src/client/components/ProjectHeader.tsx
We want to remove the "Copy this map" button from owned maps in order to unclutter the UI. We'll eventually have this functionality available from the map list page as a "Duplicate" function.
- Load a map that you own, and ensure you don't see a "Copy this map" button
- Open this same map in a private/unlogged-in window and verify that the button is displayed
Closes #530
> Remove "Copy this map" button from owned maps

- CHANGELOG.md
- src/server/src/districts/services/topology.service.ts
- src/server/src/healthcheck/topology-loaded.indicator.ts
During a previous deployment, we encountered an issue where a change to the `RegionConfig` entity caused the service to be unable to load the topojson layers, but the healthcheck did not report a problem.
By adding a new field to the `RegionConfig` entity, I was able to recreate the original issue:
```diff
diff --git a/src/server/src/region-configs/entities/region-config.entity.ts b/src/server/src/region-configs/entities/region-config.entity.ts
index 8cba8b3..8636751 100644
--- a/src/server/src/region-configs/entities/region-config.entity.ts
+++ b/src/server/src/region-configs/entities/region-config.entity.ts
@@ -32,4 +32,7 @@ export class RegionConfig implements IRegionConfig {
@Column({ type: "boolean", default: false })
hidden: boolean;
+
+  @Column({ type: "boolean", default: false }) …
```
> Fix health check when unable to load RegionConfig data

- docker-compose.yml
- src/manage/README.md
- src/manage/src/commands/process-geojson.ts
Made a few small changes while reprocessing all regions for less simplification + quantization:
* Increased max Node memory by a couple GBs, since Texas hit the limit
* Fixed quantization parameter short-name
* Allow bypassing quanitzation by supplying a value of zero
* Use streaming to write GeoJSON, since Texas hit the JS string length limit
- I don't think this needs a whole lot of testing, since I've just processed all regions. I'm mostly looking for a code spot check, and if optionally process a small region.
> Various minor changes to processing script

- CHANGELOG.md
- src/client/actions/projectData.ts
- src/client/api.ts
- src/client/components/ExportMenu.tsx
- src/client/components/ProjectListFlyout.tsx
- src/client/reducers/projectData.ts
- src/client/screens/HomeScreen.tsx
This adds a GeoJSON export option to the export menu on the map page, and also brings over the now three export options to the map list page, so it can be done directly from there.
* The GeoJSON isn't available on the project page. Even though it is available on the map page, I chose to keep it simple by using the same code path in both places, and thus requesting GeoJSON on the map page, even though we technically do already have it available. I think reducing the complexity is worth the second or so wait when a user exports GeoJSON.
* I spent some time attempting to properly style the flyout on the project list page, but couldn't quite get it right, and ultimately decided to revert my styling attempt, and kick it over to the design team for efficiency sake.
- Test …
> Allow exporting map GeoJSON

- CHANGELOG.md
- src/client/components/map/FindMenu.tsx
- src/client/reducers/projectData.ts
Keeps position in the Find menu in place after accepting changes when possible.
This is a little harder than it might initially seem (my first attempt at this was to simply leave the `findIndex` state as-is after changes are save, but that runs into issues where the index might no longer be valid).
- Create a few unassigned spots and non-contiguous districts. Ensure the find position is preserved for both find options, when possible
Closes #555
> Don't reset find index after accepting changes

- CHANGELOG.md
- src/client/components/ProjectSidebar.tsx
- src/server/src/districts/entities/geo-unit-topology.entity.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/shared/entities.d.ts
~Fixes issue of the compactness field being dropped, which seems to have happened whenever the first district had a null value.~
~This manifested in compactness scores being dropped, but I think would be an issue for any nullable field.~
Edit:
The initial approach didn't work out well, and was reworked in https://github.com/PublicMapping/districtbuilder/pull/556/commits/1e3e09130376c6d889535870000e50b4ee21569f to make the `compactness` field numeric-only and add a new `contiguity` field in the export.
- Load up a map with no unassigned blocks
- On `develop` the Shapefile export should not have a `compactness` column - on this branch it should
Closes #554
> Rewrite null values in SHP export to prevent them from being dropped

- CHANGELOG.md
- src/client/App.tsx
- src/client/actions.ts
- src/client/actions/organization.ts
- src/client/api.ts
- src/client/components/SiteHeader.tsx
- src/client/reducers.ts
- src/client/reducers/organization.ts
- src/client/screens/HomeScreen.tsx
- src/client/screens/OrganizationScreen.tsx
- src/server/migrations/1611668130609-initial_organization_entity.ts
- src/server/src/app.module.ts
- src/server/src/organizations/controllers/organizations.controller.ts
- src/server/src/organizations/entities/organization.entity.ts
- src/server/src/organizations/organizations.module.ts
- src/server/src/organizations/services/organizations.service.ts
- src/shared/entities.d.ts
This adds a skeleton frontend & backend for displaying an Organization page
@jfrankl I saw in the Abstract wireframes that this had a similar header to the main Home screen, so I made the Home screen header into a reusable `SiteHeader` component (this also brought along the Support option, which _wasn't_ in the wireframes). I can revert this easily enough if you think the headers on those pages are going to end up looking different.
- `scripts/migration`
- Add a new Organization using `scripts/dbshell` (e.g. `INSERT INTO organization (name, slug) VALUES ( 'Mikes Map Competition', 'mikes-maps' );`)
- You should be able to access the Organization page for your organizations slug, whether or not you are logged in.
Closes #224
> Organization page stub

- src/client/functions.ts
Fix label for new Dane County Ward geounits to say "Wards" instead of "ward" in the geounit selector.
Also makes the labelling function a little more generic to better support adding more types of geounits in the future.
- Add a new row to your `region_config` table using this for the `s3_uri` column: `s3://global-districtbuilder-dev-us-east-1/regions/US/WI/2021-02-08T15:19:22.145Z/`
- On `develop` the geounit label will be `ward`, on this branch the label will be `Wards`
Connects to #564
> Fix label for Ward geounits

- CHANGELOG.md
- src/client/actions/projectData.ts
- src/client/components/ProjectListFlyout.tsx
- src/client/reducers/projectData.ts
- Add actions for duplicating a project
- Add reducers for duplicating a project
- Fix reducer to reload projects on successful duplication
- Add changelog entry
Allows for a user to create a copy of one of their existing projects from the context menu on the project's list record in the homepage view. 
- Navigate to the homepage at http://localhost:3005
- Click on the context menu for an existing project, and select 'Duplicate Map'
- Expect: A new project is created, with the name "Copy of {PROJECT}"
Closes #563
> Allow for duplication of a map project from home screen

- CHANGELOG.md
- scripts/load-region-configs
Add script to load region configs
This adds region configs for PA, MI, and an "atypical" one in Dane County. PA and MI are good for development since they're rather large states so we can hopefully see potential performance manifest themselves in dev first. 
* Run `scripts/load-region-configs` and 3 rows should be added
* Run it again and no rows should be added but it should succeed
> Add script to load region configs

- CHANGELOG.md
- src/client/api.ts
- src/client/components/CopyMapModal.tsx
- src/client/screens/CreateProjectScreen.tsx
- src/client/screens/StartProjectScreen.tsx
- src/server/migrations/1612973895673-project_chamber.ts
- src/server/src/chambers/chambers.module.ts
- src/server/src/chambers/entities/chamber-id.dto.ts
- src/server/src/projects/entities/create-project.dto.ts
- src/server/src/projects/entities/project.entity.ts
- src/server/src/projects/projects.module.ts
- src/shared/entities.d.ts
Adds a foreign key onto the Project entity to associate it with an optional Chamber that is selected by the user when a project is created.
- [ x ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible
- Ensure that you have your local dev environment set up with a region and a chamber associated with that region
- Create a new project with a region that has an associated chamber
- `./scripts/dbshell`
- `SELECT * FROM project`
- _Expect:_ the last project in the list has a chamber_id value associated with it equal to the ID of the chamber you selected on the frontend
Closes #559
> Add chamber field to project entity

- .eslintrc.js
- CHANGELOG.md
- src/server/.eslintrc.js
- Allow if statements
- Don't allow console.log statements
- Add a console.log statement to a file within `client/`
- `./scripts/yarn client lint`
- _Expect:_ Error thrown indicating that console.log statements are not allowed
- Add a console.log statement to a file within `server/`
- `./scripts/yarn server lint`
- _Expect:_ Error thrown indicating that console.log statements are not allowed
> Update ESLint rules

- CHANGELOG.md
- src/client/api.ts
- src/client/components/CopyMapModal.tsx
- src/client/components/ProjectName.tsx
- src/client/screens/CreateProjectScreen.tsx
- src/client/screens/OrganizationScreen.tsx
- src/client/screens/StartProjectScreen.tsx
- src/manage/src/commands/update-organization.ts
- src/manage/src/lib/dbUtils.ts
- src/server/migrations/1613651828605-ProjectTemplate.ts
- src/server/migrations/1613662669746-project_template_reference.ts
- src/server/src/app.module.ts
- src/server/src/organizations/controllers/organizations.controller.ts
- src/server/src/organizations/entities/organization.entity.ts
- src/server/src/project-templates/entities/project-template-id.dto.ts
- src/server/src/project-templates/entities/project-template.entity.ts
- src/server/src/project-templates/project-templates.module.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/projects/entities/create-project.dto.ts
- src/server/src/projects/entities/project.entity.ts
- src/server/src/users/entities/user.entity.ts
- src/server/src/users/services/users.service.ts
- src/shared/entities.d.ts
New organization template section:
Maps created from a template have a dropdown instead of a ✏:
About this template modal:
- `scripts/migration`
- Add project template(s) to your DB, either using SQL or w/ a YAML configuration and the `update-organization` command.
- Create a new map from an organization template on the Organization home screen (`/o/<organization.slug>`) - it should redirect you to the project screen 
- Maps created from templates should show a dropdown menu instead of a ✏ button next to the project name, allowing editing the project name (as normal) or opening a modal to show template details
Closes #227
> Organization project templates

- CHANGELOG.md
- src/client/screens/OrganizationScreen.tsx
Disables the 'Join Organization' and 'Use this Template' buttons in the OrganizationScreen component for users who have not verified their email, and adds a tooltip indicating that they need to verify their email first.
- [ x ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible
_With unconfirmed email_
_With confirmed email_
The JSX for this component here is getting pretty unwieldy. Might be worthwhile to refactor some of the boxes into separate components.
- Create a new user with an unverified email address
- Navigate to an organization's page (e.g., http://localhost:3003/o/mikes-maps if you are using Mike's YAML file)
- _Expect_: the Join Organization button and Use this Template button are disabled
- Verify the email for the …
> Restrict 'Join Organization' and 'Use this template' button to verified users

- CHANGELOG.md
- src/client/actions/organization.ts
- src/client/actions/projectData.ts
- src/client/api.ts
- src/client/reducers/organization.ts
- src/client/reducers/projectData.ts
- src/client/resource.ts
- src/client/screens/OrganizationScreen.tsx
- src/client/screens/PageNotFoundScreen.tsx
- src/client/screens/ProjectScreen.tsx
Displays an error screen on the Project or Organization pages if a user attempts to navigate to an entity (project / organization) that does not exist. 
I'm not entirely sure about how to handle the current toast notification that appears when a fetch error occurs. It seems like if nothing else, the copy should be updated here - since refreshing will not change the fact that the organization or project does not exist. But, I imagine that we want this to be displayed in the event that there is an unexpected failure when fetching a project that _does_ exist...
Also, we may need a little finessing on the style here @jfrankl 
- Attempt to navigate to a URL for a project that does not exist, e.g. [http://localhost:3003/projects/777](http://localhost:3003/projects/777)
- …
> Show error page for 404 errors on project and organization screens

- CHANGELOG.md
- src/client/components/ProjectSidebar.tsx
- src/client/functions.ts
- src/server/migrations/1614028839986-project_districts.ts
- src/server/src/districts/entities/geo-unit-topology.entity.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/projects/entities/project.entity.ts
- src/shared/entities.d.ts
- src/shared/functions.ts
Cached `district` field can be seen in debugger:
Note the `districts` is excluded from the main project detail endpoint and I also left it off of the `IProject` interface - instead access continues to go through the `/export/geojson` endpoint. This solves two issues:
- We can't import from `geojson` in the shared module yet (see #179) so I can't move the `DistrictsGeoJSON` type there
- Including the geojson on the list page would unnecessarily slow down things
There are definitely downsides to this approach though, and I think we could refactor this further to eliminate the need for the `/export/geojson` endpoint.
- Displaying and updating districts should continue to work as normal
Closes #567
> Project districts geometry

- CHANGELOG.md
- src/client/components/ConfirmJoinOrganization.tsx
- src/client/components/JoinOrganizationModal.tsx
- src/client/screens/OrganizationScreen.tsx
- src/server/src/auth/services/auth.service.ts
- src/server/src/users/controllers/users.controller.ts
- src/shared/entities.d.ts
- When a user has not joined an organization and they click on "Join Organization" on that organization's page, there is a confirmation modal that displays text and asks them to confirm joining the organization
- When a user has not joined an organization and they click on any "Use this template" button on that organization's page, there is a confirmation modal that displays text and asks them to confirm joining the organization.
-  The user cannot start a template map for an organization without joining
- [ x ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible
Does it make sense to possibly disable the 'Use Template' button and have a tooltip text indicating that the user must join and organization first? Like we did in #591 
- …
> Require users to confirm understanding before joining an organization

- docker-compose.debug.yml
- scripts/server
- src/server/package.json
Adds a `--debug` flag to `scripts/server` to run the backend in debug mode, with the standard `9229` Node.js debugging port exposed through Docker to the host.
I used VS Code's built-in debugger with the following configuration, but I believe other tools compatible w/ the Node inspector like the Chrome dev tools should also work:
```
{
// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
"version": "0.2.0",
"configurations": [
{
"type": "node",
"request": "attach",
"name": "Attach to Node",
"localRoot": "${workspaceFolder}/src",
"remoteRoot": "/home/node/app",
"port": 9229
}
]
}
```
- `scripts/server --debug`
- Attach a debugger to the backend
- Ensure …
> Add option to scripts/server to run in debug mode

- src/client/screens/OrganizationScreen.tsx
I assume this snuck in during a merge/rebase
Before:
After:
> Remove duplicate "Join organization" button

- CHANGELOG.md
- src/client/api.ts
- src/client/reducers/organization.ts
- src/client/reducers/projectData.ts
- src/client/screens/ProjectScreen.tsx
- src/server/src/projects/controllers/projects.controller.ts
- Fixes the backend to properly return 404 in all cases for invalid project URLS or missing IDs
- Got to a project
- Changing one character in ID in the URL, so you have a _valid_ UUID which is not in our database, and refreshing the page, should return a 404 from backend and displaying the Not Found component
- Replacing the ID in the URL, so you have an _invalid_ UUID, and refreshing the page, should return a 404 from backend and displaying the Not Found component
- Attempting to visit an organization for a slug not in our DB should result in displaying the Not Found component
- Neither of the above should display failure toasts
Closes #595
> Fix 404 page

- CHANGELOG.md
- src/client/screens/OrganizationScreen.tsx
We were already doing this for the "Join this organization" button, but now we also disable the "Use this template" button.
This is only the first half of #610, opening this now to avoid conflicts w/ @kevinearldenny 
Connects to #610
> Disable "Use this template" button if user email is unverified

- CHANGELOG.md
- src/client/components/OrganizationDropdown.tsx
- src/client/components/SiteHeader.tsx
- src/server/src/users/controllers/users.controller.ts
- src/shared/entities.d.ts
Displays a list of all of the organizations that a user is currently a member of in a dropdown menu in the `SiteHeader` component
- [] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible
- Login as a user who is a member of an organization
- Attempt to navigate to one of their organization's pages
Closes #589
> Display organizations dropdown in SiteHeader

- CHANGELOG.md
- src/client/actions/districtDrawing.ts
- src/client/components/ProjectEvaluateMetricDetail.tsx
- src/client/components/ProjectEvaluateSidebar.tsx
- src/client/components/ProjectHeader.tsx
- src/client/reducers/districtDrawing.ts
- src/client/screens/ProjectScreen.tsx
- src/shared/entities.d.ts
- Add new EvaluateMetric type
- Add ProjectEvaluateView
- Add ProjectEvaluateMetricDetail
- Build out actions for toggling evaluate mode and switching between metrics
- Click the evaluate button in the header
- _Expect_: Evaluate view displayed, with metrics listed in sidebar
- Click a metric in the sidebar
- _Expect_: Metric detail view displayed
Closes #603
> Build out scaffolding for Project Evaluate view

- src/client/components/JoinOrganizationModal.tsx
Removes seemingly unneeded useEffect that would hide the modal immediately after it was shown.
This was introduced in https://github.com/PublicMapping/districtbuilder/commit/32ffcb6cf0e8fdfd6391941503b49cc90fcdee57 though I can't figure out what it was intended to do.
- Log in as a verified user
- Go to an organization you are not a member of
- Try and join - on `develop` the modal will open and then immediately close, on this branch it will open and stay open
> Fix showing join organization for logged in users

- src/server/src/projects/controllers/projects.controller.ts
Realized this was accidentally being included in the project data, when the frontend ignores it and gets it through the existing `export/geojson` endpoint.
Probably best not to include it unnecessarily since this can be a potentially massive column.
This is an oversight from #567 
- The project page should continue to function
> Exclude the 'districts' column from Project detail response

- src/server/src/organizations/services/organizations.service.ts
This field was mistakenly omitted when converting from using `nestjsx-crud` to using TypeORM directly, and was breaking loading the logo on the organization screen.
Closes #XXX
> Fix showing organization logo

- CHANGELOG.md
- src/client/components/FeaturedProjectCard.tsx
- Adds functionality to link Featured Project cards displayed in the `OrganizationScreen` for navigating to the project detail view when clicked
- Adds a hover cursor to featured projects to identify link functionality
@tgilcrest @jfrankl There is the possibility of encountering an error here, if an admin has set a project as featured that has not  set the project's visibility as Visible or Published. If a user tries to navigate to a featured project that is Private, they currently receive a 404 error and "Project not found". We should probably add some logic in either:
a) (likely) The `OrganizationAdminProjectsTable` to not listed projects that have not been published yet
b) The `OrganizationScreen` to filter out unpublished projects
- Go to an organization with featured projects
- Click …
> Make featured maps in OrganizationScreen clickable

- CHANGELOG.md
- src/client/components/OrganizationTemplates.tsx
- src/client/components/TemplateCard.tsx
- src/client/screens/CreateProjectScreen.tsx
- src/client/screens/OrganizationScreen.tsx
- Refactors `OrganizationTemplates` and `TemplateCard` into a new component outside of `OrganizationScreen`
- Renders `OrganizationTemplates` component in `CreateProjectScreen` to allow users to create a project from a template
- I still haven't tested this with multiple templates / multiple organizations, but I see no reason why it shouldn't work, conceptually. May need to do a bit of styling fix-up, but I think it's in the right direction currently.
- There are gonna be some gnarly merge conflicts with #633 here on `OrganizationScreen`. Am wondering which way it will be easier to resolve these - since the refactor of `OrganizationTemplates` is in this branch, it might make sense to merge this one in first?
- With a user who has joined an organization that has at least one template - …
> Allow a user to create a project from an organization's template from the Create Project screen

- CHANGELOG.md
- src/client/components/FeaturedProjectCard.tsx
- src/client/components/OrganizationAdminProjectsTable.tsx
- src/client/reducers/organizationProjects.ts
- src/client/screens/OrganizationAdminScreen.tsx
- src/client/screens/OrganizationScreen.tsx
- src/client/types.d.ts
- src/server/src/project-templates/services/project-templates.service.ts
- src/shared/entities.d.ts
- Adds creator email to admin project table
- Adds a link to project screen from admin project table
- (Somewhat) fixes issue with the table flickering*
* Since we are currently using an endpoint on the `project_templates` controller (since the relationship linking a Project -> Organization is thru a template) but displaying projects in this table, this update operation is a bit tricky. I improved the flickering a bit by not setting `isPending` to `true` in [organizationProjects.ts](https://github.com/PublicMapping/districtbuilder/blob/dc58abc7194a80dbeb25e4959f308654a8f4f946/src/client/reducers/organizationProjects.ts), but there is still a slight flicker occurring when the table updates.
- Login with an admin user
- Navigate to Org Admin page
- Expect: Table fields …
> Admin page improvements

- CHANGELOG.md
- src/client/actions/regionConfig.ts
- src/client/api.ts
- src/client/components/evaluate/ProjectEvaluateMetricDetail.tsx
- src/client/components/evaluate/ProjectEvaluateSidebar.tsx
- src/client/components/evaluate/ProjectEvaluateSummary.tsx
- src/client/components/evaluate/detail/CountySplit.tsx
- src/client/components/map/Map.tsx
- src/client/components/map/MapTooltip.tsx
- src/client/components/map/index.ts
- src/client/components/map/labels.ts
- src/client/functions.ts
- src/client/reducers/regionConfig.ts
- src/client/screens/CreateProjectScreen.tsx
- src/client/screens/ImportProjectScreen.tsx
- src/client/screens/ProjectScreen.tsx
- src/server/src/region-configs/controllers/region-configs.controller.ts
- src/server/src/region-configs/region-configs.module.ts
- src/shared/entities.d.ts
- Displays the number of counties / top-level geounits that are split across multiple districts in `ProjectEvaluateSummary`
- Adds a new sidebar display, `CountySplit`, with a list of all counties / geo-units* by name and a marker identifying the counties that are split across multiple districts
- Updates the map view when the County Split metric is selected to display a layer of the counties that are split across multiple districts
- Adds a legend to the map
* For Dane County, do the blockgroups have a `name` property?
~** I'm encountering a slight bug here where the county names are lost if you close the metric and re-open it... I know that there is a React Hook-based solution I could employ here, but figured I'd get a draft PR up now for you to take a look~ Fixed 💯 , now ready for …
> Display Evaluate Mode metric view for County Splits

- CHANGELOG.md
- src/client/screens/OrganizationAdminScreen.tsx
- src/client/screens/OrganizationScreen.tsx
- Adds a 'View all' button to Org Screen visible only for org admins to link to the Org Admin screen
- Adds a link on the Org Admin screen to navigate back to the public Org page
- Login as an org admin user and navigate to org page
- Expect: Button appears enabling you to navigate to admin screen
- Login as a non-admin user and navigate to org page
- Expect: Button is not visible
Closes #653
> Add button to link to admin screen on org page

- CHANGELOG.md
- src/server/src/projects/controllers/projects.controller.ts
Allow admins to view projects created from project template for organizations they administer.
I took a half-hearted stab at writing an integration test to exercise the filtering login within project controller `@CrudAuth` but it seemed like it would take a while to get it working so I bailed.
* Make sure an organization is created with a project template
* Log in as a different user or create a new user
* Join the organization
* Create a project from the template
* Log back in as the org admin and go to `/o/<org_slug>/admin`
* You should see the private project created by the other user in the list
* Ensure you can view it but cannot edit the map
Closes #665
> Allow admins to view projects created from organization template

- CHANGELOG.md
- src/client/actions/organizationProjects.ts
- src/client/api.ts
- src/client/components/FeaturedProjectCard.tsx
- src/client/components/OrganizationAdminProjectsTable.tsx
- src/client/screens/OrganizationScreen.tsx
- src/client/types.d.ts
- src/server/src/project-templates/services/project-templates.service.ts
- src/shared/entities.d.ts
Prevents organization admins from featuring unpublished maps.
Also refactors to remove the client-only `OrgProject` type in favor of the shared (and more accurate) `ProjectNest` type.
- Go to the org admin page - all maps listed there previously should still be there, but the Feature/Unfeature button should only be visible if the map is published
Closes #635
> Dont allow featuring unpublished maps

- CHANGELOG.md
- src/client/screens/HomeScreen.tsx
Displays the import button on the home screen, even when a user has not created any maps yet.
@jfrankl @tgilcrest  Two things I'm a little uncertain about here:
1. What color should this button be? I have it as gray / `links.secondaryButton` currently, but this wasn't explicitly noted in the issue
2. Do we want any icon here? It looks a little weird with an icon on the 'Create a map' button, but not on this button.
- Create a new user account and login
- Expect: Import button displayed on home screen underneath 'Create a map button', which opens the import map dialog when clicked
Closes #643
> Display import map button on home screen when no maps have been created

- CHANGELOG.md
- src/client/screens/OrganizationAdminScreen.tsx
Refactors the organization admin screen to avoid the table flickering when featuring/unfeaturing a project.
- Go to the org admin screen, and feature/unfeature some projects. On `develop`, there will be a flicker where the table disappears momentarily, on this branch there will not.
Closes #640
> Refactor: Use local state to avoid table dissappearing during API update

- CHANGELOG.md
- src/client/screens/ImportProjectScreen.tsx
- Handle case where upload is cancelled while AJAX call is in-transit
- Make sure button is un-disabled after AJAX call completes
- Show spinner when CSV upload is in-transit
I decided against the implementation described (the button is always enabled, a spinner is shown on the button) in the issue in favor of something more in line with the original wireframes (the spinner is next to the file, the button is disabled until the upload is complete), for ease of implementation as well as to lay the groundwork for #629 
- Upload a valid CSV
- It should show a spinner while it is uploading
- Click redo while it is uploading - it should reset the UI, and remain reset when the API call completes
- If you fill in the # of districts before the file is done uploading, the Save …
> Fix race conditions on ImportProjectScreen

- CHANGELOG.md
- src/client/components/ConfirmJoinOrganization.tsx
- src/client/components/JoinOrganizationModal.tsx
- src/client/screens/OrganizationScreen.tsx
Fixes a bug around projects being created when a user clicks 'Use template' on a project template after having left an an organization, and then rejoins (as initially identified by @jfrankl in #662)
- Login with a non-admin user who is a member of an organization
- Navigate to the organization screen, and leave an organization
- Click the 'Use template' button on a project template
- Click 'Cancel' on the ensuing dialog
- Click Join Organization; expect the organization to be joined, and no project to be created
Closes #662
> Don't create a new map when joining an organization

- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/projects/entities/project.entity.ts
We want to track the most recently updated date for users projects, but organization admins setting the `isFeatured` flag should not be considered an update.
- On `develop`, toggling the Featured/Unfeatured flag will also update the `Project.updatedDt` field. On this branch it should not.
- Editing other project fields (name, districts, visibility, etc.) should continue to update the `updatedDt` field
Closes #668
> Whitelist isFeatured field from triggering change to Project.updatedDt

- CHANGELOG.md
- src/client/components/ProjectSidebar.tsx
- src/client/components/map/Map.tsx
- src/client/types.d.ts
- src/server/migrations/1617656641073-locked-districts.ts
Fixes a bug identified in #666 where the last district in the list cannot be locked by updating the IDs of districts in the list. Previously, the ø / unassigned district was associated with the first value in the locked districts list, when in reality it should never be lockable. By updating the indices of the locked districts in the sidebar and map to be n-1, all districts are now able to be locked. 
Also, the ability to lock the unassigned district was removed.
- Create a map with a full set of districts, and attempt to lock all of the districts individually. All of the districts should be lockable, and their lock state should be reflected in the map as well as the sidebar
Closes #666
> Update index of locked districts to make the last district lockable

- CHANGELOG.md
- src/client/components/ProjectHeader.tsx
Displays the export button on shared projects, like we had previously been including on an individual's created projects
- Create a project from an org template with a non-admin user and publish it
- Login as the org admin user, and go to the org admin page by clicking View All on the Org Page
- Select a project from another user
- Expect: Export menu is displayed in header and is fully functional
Closes #661
> Display export button on shared projects

- CHANGELOG.md
- src/client/actions/districtDrawing.ts
- src/client/components/map/PaintBrushSelectionTool.ts
- src/client/components/map/RectangleSelectionTool.ts
- src/client/components/map/index.ts
- src/client/reducers/districtDrawing.ts
Fix off screen geounits deselected when using rectangle tool
This includes a little bit of cleanup (see 04c4f71) and adding of comments (see d8cfe2d; selecting vs. highlighting always gets me confused when I haven't looked at this code for a little while so hopefully this will help with that).
The fix is in 17a6e8f.
Make sure the bug can't be reproduced.
Closes #667
> Fix off screen geounits deselected when using rectangle tool

- CHANGELOG.md
- src/client/components/map/Map.tsx
- Fix bug identified in #660 around toggling evaluate mode breaking project editing for lower-level geounits
- Hides editing tools when in evaluate mode
- Hides legend when not in evaluate mode
- Open a project, and select 'Block group' editing level
- Toggle editing mode and select a view (e.g., compactness)
- Expect: Cursor becomes the map pan tool when in evaluate mode
- Turn evaluate mode off
- Expect: You are able to edit the project at the Block group level after opening evaluate mode
Closes #660
> Fix evaluate mode toggle to no longer break project editing

- CHANGELOG.md
- src/server/src/projects/controllers/projects.controller.ts
If a map is currently featured and then set to private, `isFeatured` is set to false and the map is no longer displayed on the Organization Screen
- Login as an org admin and create a project
- Set a project as 'Published' from the Project screen
- Set that project to be featured from the Org admin page
- Go back to the project, and set it's visibility to 'Private'
- Go back to Org screen - expect that the project is no longer displayed there
Closes #684
> Set map as unfeatured if private

- src/server/src/healthcheck/healthcheck.module.ts
- src/server/src/region-configs/region-configs.module.ts
NestJS won't ensure the service class is a singleton unless it is imported via it's module.
Services should rarely (if ever) be directly imported.
I believe this problem has bitten us before.
Is it possible to add a lint rule or something similar to prevent this? Even something as simple as grepping for `imports:.*Service` would have caught this 😢 
On this branch your `server` console output should look like this:
```
server_1    | [Nest] 239   - 04/13/2021, 5:43:48 PM   [RouterExplorer] Mapped {/api/project_templates, GET} route +0ms                                                                     
server_1    | [Nest] 239   - 04/13/2021, 5:43:48 PM   [NestApplication] Nest application successfully started +7ms …
```
> Fix accidental duplicate loading of topology service

- CHANGELOG.md
- src/client/components/ProjectSidebar.tsx
- src/client/components/evaluate/ProjectEvaluateMetricDetail.tsx
- src/client/components/evaluate/ProjectEvaluateSidebar.tsx
- src/client/components/evaluate/detail/EqualPopulation.tsx
- src/client/components/map/Map.tsx
- src/client/components/map/index.ts
- src/server/src/districts/entities/geo-unit-topology.entity.ts
- src/shared/entities.d.ts
Adds Evaluate Mode view for Equal Population
- Add new screen
- Compute population deviation on backend and add to GeoJSON so we can style the map based on it
- Add diverging scale on map to display the deviation from the the expected population for a district
Scenario A - incomplete project
Holes in the map are no longer displayed 👍 
Each choropleth step is displayed properly 👍 
Scenario B - 'completed' project
~1) All areas which are not assigned to a district should ideally be no fill... any idea how we can do this?~
~2) It seems like the choropleth stops are getting a little messed up in some instances - but _only_ in the map, not the sidebar view. Namely, districts which are within the +/- 5% bucket appear to be getting knocked down a step?~
- Open a project, …
> Add Evaluate Mode view for Equal Population

- CHANGELOG.md
- src/client/components/map/Map.tsx
- src/client/components/map/PaintBrushSelectionTool.ts
- src/client/components/map/RectangleSelectionTool.ts
Toggles to the map pan ('grab') tool from the rectangle or paintbrush select tool when the spacebar is held.
- Prevent toggle when the user is actively selecting new elements with the rectangle tool
- Start selecting elements with the rectangle selection or paintbrush
- Hit spacebar - expect cursor to become map pan tool
- Hit spacebar again - expect cursor to return to rectangle select
- Continue selecting more elements, and hit the spacebar as you are selecting more elements. Expect - nothing happens
Closes #429
> Toggle map pan tool with spacebar

- CHANGELOG.md
- src/client/components/evaluate/ProjectEvaluateSidebar.tsx
- src/client/components/map/index.ts
Fixes the display for contiguity and compactness by rendering unassigned areas with a transparent fill. Although the issue was originally tagged for only Contiguity display, this issue was also occurring in Compactness as well (and was already fixed as part of #685 for equal population)
- Create a district, and then cut a hole in the district and add that back to the unassigned areas
- Open evaluate mode
- Expect: count of contiguous districts does not include unassigned area
- Expect: unassigned area is rendered as transparent fill in contiguity and compactness views
Closes #694
> Fix display for contiguity and compactness

- CHANGELOG.md
- src/server/.eslintrc.js
- src/server/eslint-local-rules.js
- src/server/package.json
- src/server/src/districts/entities/geo-unit-topology.entity.ts
- src/server/yarn.lock
Add local eslint rule to detect impropert use of NestJS services.
This is intended to prevent further occurrences of issues like #689, by checking statically to make sure we don't in the wrong module, which is a likely indicator that we are providing a service more than once (which when done with `TopologyService` has resulted in nearly doubling application memory requirements)
```
$ git diff | cat
diff --git a/src/server/src/healthcheck/healthcheck.module.ts b/src/server/src/healthcheck/healthcheck.module.ts
index 538ce94..8c7ca27 100644
--- a/src/server/src/healthcheck/healthcheck.module.ts
+++ b/src/server/src/healthcheck/healthcheck.module.ts
@@ -1,13 +1,13 @@
-import { Module, forwardRef } from "@nestjs/common";
+import { Module } from "@nestjs/common";
import { TerminusModule } from …
```
> Add local eslint rule to detect impropert use of NestJS services

- CHANGELOG.md
- src/client/components/CopyMapModal.tsx
- src/client/components/Field.tsx
- src/client/components/JoinOrganizationModal.tsx
- src/client/screens/RegistrationScreen.tsx
The password validation panel was being cut off by the modal's `overflow: hidden` property. I
removed `overflow: hidden` from the modal. I also reformatted the validation panel to take up less
space, which should help us avoid situations where it would expand to the edge of the browser
window.
I experimented with rendering this panel above and below the field, but in both cases it blocked and
prevented interaction with other important elements on the page. I think this solution will work
well in a majority of cases.
- If logged in, log out of DistrictBuilder
- Navigate to a map page
- Click on "Share" and then "Create an account"
- Click in the password input; a panel should appear explaining password requirements
- Confirm that the password requirements are a.) visible; b.) formatted …
> Make password validation visible in modal

- CHANGELOG.md
- src/client/components/OrganizationAdminProjectsTable.tsx
- src/client/screens/OrganizationAdminScreen.tsx
Fixes the sorting on the organization admin table to:
- Pre-sort by updated date, with most recent at the top (like the home screen)
- Preserves the sort order when updating the data
Also cleans up the type usage around `react-table`
- I cleaned up the `ProjectRow` type and moved use of it into the table component
- I got rid of the of some of the `@ts-ignore` comments by adding `as const` and switching from the "nested.object.keys" syntax to a helper function
- Play around with the org admin table - dates should sort correctly, and 
Closes #678
> Fix organization admin table sorting

- CHANGELOG.md
- src/server/src/organizations/controllers/organizations.controller.ts
- src/server/src/project-templates/services/project-templates.service.ts
Fixes two bugs 
- you couldn't leave an organization with an inactive project template, which bizarrely had a root cause of missing some fields from the custom SQL select we were using
- shows maps for project templates which are not active
Note the featured map despite no active project templates, and also we can actually leave the organization:
- Set up an organization with at least one template
- Create a map for that template, and publish it
- Using `scripts/dbshell` set `is_active` to `FALSE` on the project template assoicated with your map
- It should still appear on the organization admin screen.
- If you feature your map, it should still appear on the organization home screen
- Even with an inactive project template, you should be able to leave the organization
Closes #714 
Closes …
> Fix Organization bugs

- CHANGELOG.md
- src/server/src/rollbar/rollbar-exception.filter.ts
Our logic was a little flawed in that we required errors to be
`HttpException`s to be logged to Rollbar. However, we also want to know
about other types of unhandled exceptions.
This is slightly tricky in terms of types since in JavaScript, bizarrely, you can
actually throw _any_ type (does not need to be an `Error` or extend
`Error`). However, that seems to be enough of an edge case that we don't
have to worry about it.
In the specific case of the leaving-an-organization bug, that generated
a `QueryFailedError` which is why it was not sent to Rollbar.
I didn't super fully test this manually since it seems to be a very straightforward change. If you know of a way to get staging to throw an unhandled, non-whitelisted error, that would be a good test. To test in development, you could …
> Log non-HTTP errors to Rollbar

- CHANGELOG.md
- src/client/components/map/index.ts
We were properly displaying `lockedDistricts` as 0-indexed, but the click-handler code was still treating it as `1-indexed` as we did before #677.
- On `develop`, locking a district will appear to work, but interactions will as as though the district before it in the list is locked.
- On this branch, the visual lock indication should match behavior
Closes #728
> Fix off-by-one error in handling locked districts map interaction

- src/manage/src/commands/process-geojson.ts
Fix process-geojson command when `--voting` / `-v` flag is not passed.
This flag was intended to be optional and default to no data.
- `scripts/manage process-geojson ...` should work w/o passing the `-v` flag
> Fix process-geojson command when --voting flag is not passed

- CHANGELOG.md
- src/server/migrations/1620913550713-change_visibility_default.ts
- src/server/src/project-templates/services/project-templates.service.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/projects/entities/project.entity.ts
- Organization admins can no longer see Private maps
- Maps now have a "Published" visibility by default
- `scripts/yarn server run build`
- `scripts/migration`
- New projects should default to a "Published" visibility
- Organization admins should no longer be able to go to a project detail or see them on the admin screen, if the project visibility is set to "Private"
Closes #739
> Change map visibility settings

- src/client/components/ProjectSidebar.tsx
Fixes display of the sidebar for the Pol. column for regions w/o voting data
VA w/ political data:
PA w/o voting data:
- Ensure you have maps for a region w/ voting data (most recent VA) and a region w/o voting data (anything else)
- The sidebar should no longer be broken on non-VA maps
Closes #745
> Fix to stop display of the Pol. column for regions w/o data

- CHANGELOG.md
- src/client/components/DemographicsTooltip.tsx
- src/client/components/ProjectSidebar.tsx
- Adds an asterisk next to the demographics chart in sidebar for minority-majority districts
- Adds a footer to tooltip denoting a district as minority majority
@jfrankl This could use a bit of styling finesse here:
1. Making the asterisk displayed a little cleaner
2. Adding the icon to the tooltip footer
- Create a minority-majority district (e.g., the city of Philadelphia)
- Expect: an asterisk is displayed next to the district, and the tooltip that is displayed when hovering over the demographics chart includes an annotation in the footer
Closes #426
> Show minority majority districts in sidebar

- CHANGELOG.md
- src/client/actions/districtDrawing.ts
- src/client/components/MapHeader.tsx
- src/client/components/map/AdvancedEditingModal.tsx
- src/client/components/map/Map.tsx
- src/client/components/map/keyboardShortcuts.ts
- src/client/functions.ts
- src/client/reducers/districtDrawing.ts
I moved most of the business logic into a helper function, which is called both by `MapHeader.tsx` as it used to be, as well as by the redux ~action~ reducer, which allows the keyboard event handler to continue to be very simple.
Switching between geolevels using S / F should behave _exactly_ as it does when clicking the buttons in the header
Scenarios to check:
- A read-only map (I used an incognito window)
- A map where you haven't done block editing before, as well as one where you have
- How it behaves when there are pending changes
Closes #747
> Fix handling of switching into block editing when using keyboard shortcut

- CHANGELOG.md
- src/client/components/ProjectSidebar.tsx
- src/client/components/VotingMapTooltip.tsx
- src/client/components/VotingSidebarTooltip.tsx
- src/client/components/map/MapTooltip.tsx
- src/client/s3.ts
- src/client/types.d.ts
- src/client/worker-functions.ts
- src/client/worker.ts
- Adds new component `VotingMapTooltip` and displays within map tooltip in the same styling as existing demographics
- Migrates existing `VotingTooltip`to `VotingSidebarTooltip`
- Updates worker functions to load voting data simultaneously as demographics
I'm not entirely sure how DRY this implementation is, since these two tooltips have more or less the same function and there is a bit of processing repeated.
- Open a project with voting data ingested
- Hover over geounits in the map - expect voting data to be displayed underneath demographics
Closes #693
> Add voting info to map tooltip

- CHANGELOG.md
- src/client/components/DemographicsChart.tsx
- src/client/components/DemographicsTooltip.tsx
- src/client/components/map/MapTooltip.tsx
- src/client/constants/colors.ts
- Adds fields for `nativeAmerican` and `pacificIslander` to demographics chart
- Allows for the existing split (with `Other`) to still be read and displayed
I've noticed a few instances where `pacificIslander` is displayed as 0% - does it make sense to display this instead as "< 1%"?
- Process the attached geojson for Delaware: `./scripts/manage process-geojson data/input/de.geojson -o data/output/Delaware -n 12,4,4 -x 12,12,12 -d "population,white,black,asian,hispanic,native:nativeAmerican,pacific:pacificIslander"`
- Add it to the database: `./scripts/manage publish-region data/output/Delaware US DE Delaware`
- Create a new project for Delaware and view it; expect tooltip to be displayed as screenshot above
- Create a new project for PA; expect tooltip to be displayed as it was …
> Update race column to handle different race categories

- CHANGELOG.md
- src/client/components/map/KeyboardShortcutsModal.tsx
- src/client/components/map/Map.tsx
- src/client/components/map/keyboardShortcuts.ts
- src/client/screens/ProjectScreen.tsx
- Disables keyboard shortcuts related to editing in read-only mode
- Updates the display of the keyboard shortcut modal in read-only mode to only display the enabled shortcuts
- Open a read only map and attempt to use one of the disabled keyboard shortcuts
Closes #761
> Disable keyboard shortcuts in read only mode

- CHANGELOG.md
- src/client/components/map/Map.tsx
- src/client/components/map/index.ts
Cleans up the code for enabling/disabling layers for entering/leaving evaluate mode and its various subpages
- Ensure that on `develop` you are able to trigger the issues described in #769 and #770. On this PR they should be fixed, and there should be no regressions in Evaluate mode behavior
Fixes #770
Fixes #769
> Cleanup useEffect callback to handle switching evaluate modes

- CHANGELOG.md
- src/client/components/map/Map.tsx
Fixes #780
We were incorrectly hiding selected geounits based on the current geolevel.
_Currently selected_ geounits should always be shown regardless of the currently geolevel, so that when working at the county layer you can see pending block group changes, and vice versa.
- On the project screen,  select a county, switch to the blockgroup layer, and then switch back. You should continue to see your selections.
Closes #780
> Always display currently selected geounits

- CHANGELOG.md
- src/client/components/MapHeader.tsx
This option should not be shown in read-only mode
No ⚙ icon:
- Go to the project screen for a published map while not logged in. You shouldn't see the gear icon to open the menu where you can limit your selection to county
Closes #760
> Hide limit to county flyout menu in read-only mode

- CHANGELOG.md
- src/client/components/map/keyboardShortcuts.ts
Allow switching to the unassigned district when using keyboard shortcuts.
- Use `e` and `d` to switch between districts. Ensure you can switch to every district and the unassigned district
Closes #771
> Include unassigned district when switching using keyboard shortcuts

- CHANGELOG.md
- src/client/components/evaluate/ProjectEvaluateSidebar.tsx
- src/client/components/evaluate/ProjectEvaluateSummary.tsx
- src/client/components/evaluate/detail/EqualPopulation.tsx
- src/shared/entities.d.ts
Excludes empty or non-contiguous districts when calculating average compactness
- Go to the compactness detail on evaluate mode. Empty & non-contiguous districts should not be included in the calculation
Closes #772
> Fix calculation of average compactness

- CHANGELOG.md
- src/client/components/evaluate/ProjectEvaluateSidebar.tsx
- src/client/components/evaluate/detail/EqualPopulation.tsx
- Make text updates as specified in #767 
- Update flag on equal population
One copy Q for the Equal Population page - does it make sense to specify the threshold for the project in the header text? My inclination is yes, but just wanted to confirm @tgilcrest 
- Review all pages in Evaluate Mode to confirm that the text matches what is expected
Closes #767
> Cleanup text in evaluate mode

- CHANGELOG.md
- src/client/actions/districtDrawing.ts
- src/client/components/map/KeyboardShortcutsModal.tsx
- src/client/components/map/Map.tsx
- src/client/components/map/keyboardShortcuts.ts
- src/client/reducers/districtDrawing.ts
- src/client/screens/ProjectScreen.tsx
- Disables all keyboard shortcuts in evaluate mode expect 'Toggle evaluate mode'
- Closes keyboard shortcuts modal with "?"
- Open a project and go to evaluate mode
- Confirm that none of the keyboard shortcuts are available in evaluate mode besides `T` to toggle evaluate mode and `?` to toggle the modal
Closes #782
> Disable keyboard shortcuts in evaluate mode

- CHANGELOG.md
- src/client/components/ProjectHeader.tsx
- Displays the evaluate mode button for read only maps just like for a user's maps
- Go to a read only map; expect Evaluate button to visible in header
Closes #785
> Display evaluate mode button for read only maps

- CHANGELOG.md
- src/client/api.ts
- src/client/components/Field.tsx
- src/client/components/evaluate/ProjectEvaluateSidebar.tsx
- src/client/components/evaluate/detail/EqualPopulation.tsx
- src/client/components/map/Map.tsx
- src/client/components/map/index.ts
- src/client/screens/CreateProjectScreen.tsx
- src/server/migrations/1621459864489-add-configurable-population-deviation.ts
- src/server/src/project-templates/entities/project-template.entity.ts
- src/server/src/projects/entities/create-project.dto.ts
- src/server/src/projects/entities/project.entity.ts
- src/server/src/projects/entities/update-project.dto.ts
- src/shared/constants.ts
- src/shared/entities.d.ts
- Add `populationDeviation` field to Project defaulting to 5 for existing projects
- Add field to CreateProjectScreen for `populationDeviation`
- Leverage `populationDeviation` field for Evaluate Mode equal population view
- Update map symbology and legend for Evaluate Mode equal population view
- My gut feeling said to use decimal (0.05) instead of percentage (5) for _storing_ the data - but this would make things a little trickier to get the frontend to work as specified in the design and was explicitly specified in the issue so I went with the latter.
- I couldn't get the % to line up properly in `CreateProjectForm` - seems like there is probably an easy solution here @jfrankl 
- ~Do we need to update the symbology / legend in the map here as well?~ Forgot that I already planned for …
> Add configurable population deviation to project

- CHANGELOG.md
- src/client/components/ProjectSidebar.tsx
- src/client/constants/colors.ts
Fixes sidebar padding (#791) and revises race demographic colors.
For the race demographic colors, I found that the new colors were too bold, and the red “white” population color looked too similar to the “non-contiguous” alert icon and the Republican red political red. I reverted back to colors that are slightly more subtle, and removed the conflicting red.
- Confirm that the sidebar looks like the screenshots attached to this issue
Closes #791
> Style cleanup: fix padding and change race demographic colors

- CHANGELOG.md
- src/client/actions/organizationProjects.ts
- src/client/api.ts
- src/client/components/DemographicsTooltip.tsx
- src/client/reducers/organizationProjects.ts
- src/client/screens/OrganizationAdminScreen.tsx
- src/server/src/project-templates/controllers/project-templates.controller.ts
- src/server/src/project-templates/project-templates.module.ts
- src/server/src/project-templates/services/project-templates.service.ts
- src/shared/entities.d.ts
- src/shared/functions.ts
Adds a district-level CSV export to the organization admin screen.
[azavea.csv](https://github.com/PublicMapping/districtbuilder/files/6593855/azavea.1.csv)
- Go to the organization admin screen (and ensure there are projects listed there)
- Click the "Export maps" button and ensure the contents of the CSV are correct
Closes #794
> Export organization maps to csv

- .gitignore
- CHANGELOG.md
- README.md
- Vagrantfile
- deployment/ansible/district-builder.yml
- deployment/ansible/group_vars/all
- deployment/ansible/roles.yml
- deployment/ansible/roles/district-builder.devtools/tasks/main.yml
- deployment/ansible/roles/district-builder.docker/meta/main.yml
- deployment/ansible/roles/district-builder.docker/tasks/main.yml
- deployment/ansible/roles/district-builder.environment/meta/main.yml
- deployment/ansible/roles/district-builder.environment/tasks/main.yml
- docker-compose.yml
- scripts/setup
This project is really slow to work with on Mac OS due to issues with running Docker on Mac (see #43).
This PR adds a Vagrant environment that can be used on non-Linux hosts to provide a Linux-like environment in which Docker runs natively and much faster.
On `develop`, running the `update` script can take ~20 minutes. Inside Vagrant, it takes ~4.5 minutes.
* Checkout this branch and `vagrant up`
* SSH in to the Vagrant VM `vagrant ssh`
* Run `./scripts/update`
* Run `./scripts/server`
* Make a small change in some front-end file
* Make an account, then load dev data `./scripts/load-dev-data`
* Do other development-y things
> Add Vagrant Configuration

- CHANGELOG.md
- src/client/components/ProjectSidebar.tsx
- src/client/components/Tour.tsx
- src/client/components/evaluate/ProjectEvaluateSidebar.tsx
- src/client/components/evaluate/detail/Compactness.tsx
- src/client/components/evaluate/detail/EqualPopulation.tsx
- src/client/components/map/Map.tsx
- src/client/components/map/index.ts
- src/client/functions.ts
- src/client/screens/ProjectScreen.tsx
- Fixes the flag in ProjectSidebar to display correctly with a population deviation of 0
- Fixes choropleth steps for Equal Population metric for a population deviation of 0
- Fixes computation of EqualPopulation metric for evaluate mode for a population deviation of 0
- Distinguishes between the unique cases of a whole integer `avgDistrictPopulation`, and an average population that contains a fraction
Whole integer avgPopulation
Non-integer avgPopulation
- Create a map in PA with an even number of districts (e.g., 4), so the average population contains a fractional remainder
- Add a district that exactly matches the target population, or target population + 1 - expect it to be treated as equal population
- Add a district that is -1 the target population, expect to be treated as invalid
- …
> Fix sidebar and EqualPopulation metric for population deviation of 0

- CHANGELOG.md
- src/client/actions/organization.ts
- src/client/actions/organizationProjects.ts
- src/client/api.ts
- src/client/components/OrganizationExportMenu.tsx
- src/client/reducers/organization.ts
- src/client/reducers/organizationProjects.ts
- src/client/screens/OrganizationAdminScreen.tsx
- src/server/src/organizations/controllers/organizations.controller.ts
- src/server/src/project-templates/controllers/project-templates.controller.ts
- src/server/src/users/services/users.service.ts
Adds a second CSV export to the organization admin screen, for exporting users
[azavea-users.csv](https://github.com/PublicMapping/districtbuilder/files/6617606/azavea-users.csv)
- Go to the organization admin screen
- Both exports should function as expected
Closes #793
> Add organization user CSV export

- CHANGELOG.md
- scripts/load-dev-data
- src/client/actions/districtDrawing.ts
- src/client/components/DemographicsChart.tsx
- src/client/components/DemographicsTooltip.tsx
- src/client/components/MapHeader.tsx
- src/client/components/MapSelectionOptionsFlyout.tsx
- src/client/components/ProjectSidebar.tsx
- src/client/components/VotingMapTooltip.tsx
- src/client/components/VotingSidebarTooltip.tsx
- src/client/components/map/KeyboardShortcutsModal.tsx
- src/client/components/map/Map.tsx
- src/client/components/map/MapTooltip.tsx
- src/client/components/map/keyboardShortcuts.ts
- src/client/components/map/labels.ts
- src/client/constants/colors.ts
- src/client/functions.ts
- src/client/reducers/districtDrawing.ts
- src/client/screens/ProjectScreen.tsx
- src/shared/functions.ts
This PR adds support for regions with election data for both the 2016 & 2020 presidential elections.
Election year control for map data:
Map tooltip:
Sidebar tooltip:
Sidebar label tooltip:
New keyboard shortcut:
Toast for new keyboard shortcut:
We had originally written this in a more generic fashion, and I'm choosing in this PR to hardcode in support for the following three options instead, to make the code easier to work with:
- Unspecified election, keys are `democrat` / `republican` / `other party` (what we currently have, I assume the election is 2016)
- Both 2016 & 2020, keys are  `democrat16` / `republican16` / `other party16` /  `democrat20` / `republican20` / `other party20` (this is what the new IL data has)
- Just 2016, but explicitly specified by the key name (We don't have …
> Add support for multiple elections

- CHANGELOG.md
- src/client/components/map/Map.tsx
Prevents keyboard shortcuts from firing when changing the project name, or using the keyboard to choose an option in the labels dropdown.
I don't think we have any `textarea` elements on the project screen right now, but I figure future-proofing can't hurt - and I couldn't think of any other elements that could interfere w/ our keyboard shortcuts if they have focus.
- On this branch, you should be able to type in the prject name input, or use the keyboard to choose an option in the labels dropdown or election year dropdown
- When not focused on those, keyboard shortcuts should continue to work as normal
Closes #792
> Don't allow keyboard shortcuts to mess with form elements

- src/client/components/FeaturedProjectCard.tsx
- src/client/components/OrganizationDropdown.tsx
- src/client/components/PaginationFooter.tsx
- src/client/components/SiteHeader.tsx
- src/client/reducers/projects.ts
- src/client/screens/HomeScreen.tsx
- src/client/screens/PublishedMapsListScreen.tsx
- src/client/theme.ts
- Change "All maps" to "Community maps"
- Add "My maps" (the maps I've made) and "Community maps" to the primary navigation
- Make style more consistent across primary navigation
- Overhaul copy for the "My maps" empty state, to make it more inspiring and add a link to the community maps
- Clean up styles for pagination on "Community maps"
- Reduce number of maps on "Community maps" from 10 to 8, because we are displaying the maps in rows of 4 and a total number divisible by 4 looks better
- Improve spinner on loading maps, which previously doubled the size of the container card
- Create a new account, or use an account with no maps so you can view the empty state
- Take a look at the "My maps" and "Community maps" tabs
- Confirm that they look similar to the attached screenshots
> Clean up 'Community maps' view and 'My maps' views

- CHANGELOG.md
- src/client/components/ProjectSidebar.tsx
Adds a tooltip to the population deviation display in the project sidebar to help users to more easily identify the necessary changes to the district for compliance with the population deviation threshold.
- Create districts that are under the population threshold, within the population threshold tolerance, and above it
- Hover over population deviation displays - expect tooltips to be displayed for all districts
Closes #802
> Add tooltip for population deviation in project sidebar

- CHANGELOG.md
- src/client/components/ProjectSidebar.tsx
- src/client/components/map/Map.tsx
- src/client/screens/ImportProjectScreen.tsx
- src/client/screens/ProjectScreen.tsx
- src/server/migrations/1624298721363-region_config_archived_flag.ts
- src/server/migrations/1624394377454-alter_region_config_uniqueness_index.ts
- src/server/src/districts/controllers/districts.controller.ts
- src/server/src/districts/entities/geo-unit-properties.entity.ts
- src/server/src/districts/entities/geo-unit-topology.entity.ts
- src/server/src/districts/services/topology.service.ts
- src/server/src/project-templates/controllers/project-templates.controller.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/region-configs/controllers/region-configs.controller.ts
- src/server/src/region-configs/entities/region-config.entity.ts
- src/shared/entities.d.ts
Adds support for archiving regions.
Archived regions:
- Don't have topojson data kept in memory (so they are not resource intensive)
- Projects for archived regions can't be edited
- Downloading the full TopoJSON only to throw away the geometries isn't the most efficient way to go about things - if we find the startup times are not acceptable on production, a simple optimization would be to create new static files from our existing regions that contain the feature properties in the TopoJSON files as well as a pre-computed `HierarchyDefinition`.
- Set one of your `region_config` rows to be `archived, and restart `scripts/server`
- existing projects for that region should still be viewable, but no longer editable
- all evaluate mode subpages should function correctly
- …
> Add support for archived regions

- CHANGELOG.md
- src/client/api.ts
- src/server/src/projects/controllers/globalProjects.controller.ts
- src/server/src/projects/services/projects.service.ts
Filters out maps on the Community Maps page that have population left in the unassigned district. This is intended to keep uninteresting maps filtered out, making the page more useful.
Before:
After:
Note that by default the API will still return uncompleted maps, unless `completed=true` is passed as a query parameter.
- go to the community maps page
Closes #826
> Add completed filter to community maps page

- CHANGELOG.md
- src/client/components/MapHeader.tsx
Adds voting info to labels selector, which display vote totals for geounits when selected.
We may want to handle the formatting of the field names here - I wasn't able to devise an easy solution for this, and I guess the labels aren't _terrible_ currently (Democrat20, Other party20). I was thinking that it might make sense to change these labels further upstream in the geojson processing, but that likely requires some input from other stakeholders first.
- Go to a state with voting data and look in the labels dropdown - expect to see voting fields displayed
- Click a voting field, expect to see voting totals displayed
Closes #731
> Add voting info to labels selector

- CHANGELOG.md
- src/client/actions/districtDrawing.ts
- src/client/components/MapHeader.tsx
- src/client/components/MapSelectionOptionsFlyout.tsx
- src/client/components/PVIDisplay.tsx
- src/client/components/ProjectSidebar.tsx
- src/client/components/VotingSidebarTooltip.tsx
- src/client/components/evaluate/ProjectEvaluateMetricDetail.tsx
- src/client/components/evaluate/ProjectEvaluateSidebar.tsx
- src/client/components/evaluate/ProjectEvaluateSummary.tsx
- src/client/components/evaluate/detail/Compactness.tsx
- src/client/components/evaluate/detail/Competitiveness.tsx
- src/client/components/evaluate/detail/CountySplit.tsx
- src/client/components/evaluate/detail/EqualPopulation.tsx
- src/client/components/map/Map.tsx
- src/client/components/map/MapTooltip.tsx
- src/client/components/map/index.ts
- src/client/components/map/keyboardShortcuts.ts
- src/client/functions.ts
- src/client/reducers/districtDrawing.ts
- src/client/screens/ProjectScreen.tsx
- src/client/types.d.ts
- src/shared/entities.d.ts
- Adds a newly computed metric for Competitiveness, computed as the average PVI for all districts that have population
- Adds a new page for Competitiveness metric including a map and sidebar
- Add a dropdown to switch between 2016 / 2020 / combined PVI
Per my Slack conversation earlier with @maurizi , there is still some ambiguity about whether we want to allow a switch for PVI / election margin to display both metrics here. These will likely be very similar, 
- Create a map in a region that has voting data
- Create districts
- Go to evaluate mode - Competitiveness and review. Expect the PVI computations to match those included in the Project Sidebar
Closes #810
> Add evaluate mode view for competitiveness

- .eslintrc.js
- CHANGELOG.md
- docker-compose.yml
- src/client/components/DemographicsTooltip.tsx
- src/client/components/ProjectSidebar.tsx
- src/client/components/evaluate/ProjectEvaluateMetricDetail.tsx
- src/client/components/evaluate/ProjectEvaluateSidebar.tsx
- src/client/components/evaluate/detail/MajorityRace.tsx
- src/client/components/map/Map.tsx
- src/client/components/map/index.ts
- src/client/functions.ts
- src/client/types.d.ts
- src/shared/entities.d.ts
Adds an evaluate mode view for Majority Minority
- Majority race computed and displayed in sidebar
- Demographics chart included in sidebar
- Majority race and psuedo-choropleth (darker colors for greater share of majority race) included in map
I cribbed the colors from the wireframe, but I think we might be able to put a bit more thought into them. If a district is _not_ majority-minority (i.e., is majority white), the fact that it is displayed in green seems a little weird to me. I think we could probably improve the overall color scheme a bit to more effectively communicate the info that we want users to focus on @jfrankl @tgilcrest 
- Create a map with districts that are majority-minority
- Open evaluate mode - expect districts to be included in count in summary
- Open …
> Add Majority Minority evaluate view

- CHANGELOG.md
- src/server/src/rollbar/rollbar-exception.filter.ts
Adds user_id to server-side rollbar implementation, enabling for grouping of occurrences by user
It looks like there is already some sort of ip_address field being captured (as can be seen in the above screenshot). Is this value correct? It is strange that it doesn't seem to ever load if you go to the IP addresses tab, though:
- Find a way to make the server return a 500 error (I had to introduce a `throw new Error("foo");` to test this in development)
- Expect: rollbar error is logged and user ID is captured (if logged in)
Closes #789
> Add user ID to server-side rollbar logging

- CHANGELOG.md
- src/client/components/map/Map.tsx
- src/client/components/map/keyboardShortcuts.ts
- Add keyboard shortcut (`P`) to toggle expanded project metrics
- Add keyboard shortcut (`L`) to zoom to district
While working on #853 , I thought it would be nice to have a toggle for collapsing / expanding project metrics. While I was digging back into keyboard shortcuts, I realized that we didn't currently have a shortcut for zooming to the currently selected district either which seems like it could be helpful 
- Open a project and hit the `P` key - expect expanded project metrics to be toggled
- Open a project and hit the `L` key on a populated district - expect the map to zoom to that district
> Add additional keyboard shortcuts

- CHANGELOG.md
- scripts/load-dev-data
- src/client/screens/ImportProjectScreen.tsx
- src/shared/entities.d.ts
- Add populationDeviation and Chamber selection to Import Project screen
- Create chambers in `./scripts/load-dev-data` so that chambers are available for PA and IL
- To test this, we need to have chambers in the DB - I thought we had these, but they seem to have been removed from `load-dev-data` at some point. I added back in SQL to create chambers for PA and IL
- I considered refactoring `CreateProjectScreen` and `ImportProjectScreen` to become one component, or to leverage shared functions across the two since they are now relatively similar - however, I decided against it with my rationale being mostly based around the fact that we are unlikely to use any of these components in other places, and we also don't currently have anything around Organization included as part of the Import …
> Add populationDeviation and Chamber selection to Import Project screen

- CHANGELOG.md
- package.json
- src/client/App.tsx
- src/client/actions/projects.ts
- src/client/api.ts
- src/client/reducers/projects.ts
- src/client/screens/PublishedMapsListScreen.tsx
- src/server/src/projects/controllers/globalProjects.controller.ts
- src/server/src/projects/services/projects.service.ts
- yarn.lock
- Add filter by state functionality to community maps page
- Add URL param filter to enable direct navigation to maps for a specific state
I'm struggling to figure out where the "0" that's being rendered when no maps exist is coming from - it shouldn't be there. We also may need a style pass on this, since there were no wireframes for the filter included in the issue
- Navigate to the community maps page and select a state with at least one completed map
- Expect: navigate to `maps?region={STATE}`, and maps for that state are displayed
- Navigate to a URL for a state
- Expect: Map for state are displayed
Closes #833
> Add filter by state functionality to community maps page

- CHANGELOG.md
- src/client/components/ProjectSidebar.tsx
- src/client/functions.ts
Support displaying political data in sidebar for states where 2016 political data is displayed as just `republican` or `democrat` instead of `republican16` / `democrat16`
1. On some level, this fix seems clunky to me. Is there any way that we could just rename the columns in the data so that the year is always included? 
1. Are there any other potential data structures that we need to be aware of? Is it possible that 2020 data could be added later for some states where we currently have the party-only structure? If so, this seems like it may be problematic.
- Go to a project in staging in a state with the data structure outlined above (e.g., Pennsylvania)
- Expect to see political data columns in expandable metrics viewer
Closes #855
> Update display logic for political data columns in sidebar to correspond with alt data structure

- CHANGELOG.md
- src/client/GTM.ts
- src/client/actions/projects.ts
- src/client/api.ts
- src/client/components/FeaturedProjectCard.tsx
- src/client/components/HomeScreenProjectCard.tsx
- src/client/components/map/ProjectDistrictsMap.tsx
- src/client/reducers/projectData.ts
- src/client/reducers/projects.ts
- src/client/screens/HomeScreen.tsx
- src/client/screens/PublishedMapsListScreen.tsx
- src/client/types.d.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/projects/services/projects.service.ts
- src/shared/entities.d.ts
Add maps to user project cards on home screen
- Add pagination to `/api/projects` endpoint
The CSS is a bit wonky currently, this might need a style pass.
Additionally, I'm not totally sold on my direction of editing the `/api/projects` endpoint - it seems like it might have been a better idea to refactor the `globalProjects` endpoint to support filtering to only the user's projects. Extrapolating this further - could we possibly combine both of these screens into a single screen, with an option to view user projects or global projects? It seems like there is a lot of redundancy here, and especially if we want to support filtering in global projects (#833 ) it would be nice to have this in user projects as well .
- With more than 4 projects, expect to see pagination …
> Add maps to list of user projects on home screen

- CHANGELOG.md
- src/client/App.tsx
Fixes breaking change introduced in https://github.com/PublicMapping/districtbuilder/pull/851/files#diff-653e49020a6d618fec5d77295bbc5526991eacdef0aedf041c8e0f1a57208d40R69-R71 where `/register` and `/forgot-password` ceased to work
- Attempt to navigate to the /register page
- Expect: Register page is rendered and working
Closes #868
> Fix breaking change for routing on `/register` and `/forgot-password`

- .gitignore
- CHANGELOG.md
- src/client/components/MapHeader.tsx
- src/client/components/ProjectHeader.tsx
- src/client/components/map/FindMenu.tsx
- src/client/components/map/Map.tsx
- src/client/screens/ProjectScreen.tsx
- Fixes the bug identified in #859 around the find menu not opening
- Toggles the paintbrush size slider when the paintbrush icon is clicked 
It seemed like putting this on the right side was the _easiest_ solution here, but I'm not necessarily sure if it's the best solution from a UX perspective. Perhaps @jfrankl might have a better solution for how to make this more visually apparent / usable
- Click the find menu; expect the find menu to appear
Closes #859
> Fix find menu button so it properly opens the find menu

- CHANGELOG.md
- src/client/actions/projectData.ts
- src/client/reducers/projectData.ts
- src/client/screens/HomeScreen.tsx
- src/client/screens/ProjectScreen.tsx
- src/server/src/projects/services/projects.service.ts
- Adds support back in for duplicating projects from the home screen, which was broken previously in #850 when `districtsDefinition` was removed from API response
- Updates UX for duplicating projects so that a user is redirected to a duplicated project after the duplication completes
- Leverages `isSaving` and `duplicatedProject` variables in Redux store to support
I don't _love_ the approach I took for handling the redirect - it seems like there may be a way to handle this with `Resource`, but it would require a bit of refactor at least and I'm not entirely sure that it's worthwhile. 
Also, I've noticed that locally the duplicate sometimes times out due to the region configs taking a while to load. I pushed to staging to confirm that this wasn't going to be a problem there, and it looks …
> Fix the duplicate project functionality on the home screen

- package.json
I've been encountering `eslint` issues that weren't replicable on CI / other developers machines.
This SO post (https://stackoverflow.com/a/63788215) suggested the `eslint` cache could be the issue, and indeed adding these changes to our `package.json` seems to have fixed the issue.
- this line from `scripts/update` would fail on `develop` w/ spurious lint issues, now it succeeds `docker-compose run --rm --no-deps client bash -c "yarn install && yarn compile && yarn build"`
> Clear eslint cache before running react-scripts start/build tasks

- CHANGELOG.md
- src/client/screens/ImportProjectScreen.tsx
Displays an import file error if a user attempts to import a CSV containing rows from a state not currently supported in DistrictBuilder
@dmcglone Thoughts on what this text should be?
- Attempt to import a file for a state not included in local DB database (e.g., California)
- Expect: Error is displayed as shown above
Closes #852
> Add import file error for unavailable regions

- CHANGELOG.md
- src/server/src/healthcheck/healthcheck.controller.ts
We've been experiencing increased healthcheck failures lately from slow database response times, leading to application servers cycling out and occasional temporary site outages.
The 3 second timeout matches the timeout on the load balancer target group, which should help us at least keep the site up more during times of heavy load.
@colekettler had suggested exploring if the healthcheck query could be simplified, but it is already incredibly simple (`SELECT 1`), so my assumption is that the slowness of the response is not specific to the healthcheck but rather a side effect of some other performance issue.
I'm frankly unsure of how to test this, other than just assuming the documentation is correct.
Closes #867
> Increase healthcheck DB timeout to 3 seconds

- CHANGELOG.md
- scripts/load-dev-data
- src/client/actions/districtDrawing.ts
- src/client/api.ts
- src/client/components/ConvertMapModal.tsx
- src/client/components/map/Map.tsx
- src/client/reducers/districtDrawing.ts
- src/client/screens/ProjectScreen.tsx
- src/server/src/districts/controllers/districts.controller.ts
- src/server/src/districts/entities/geo-unit-topology.entity.ts
- src/server/src/districts/services/topology.service.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/projects/entities/crosswalk.entity.ts
- src/server/src/projects/entities/project.entity.ts
- src/server/src/projects/projects.module.ts
- src/server/src/projects/services/crosswalk.service.ts
- src/server/src/projects/services/projects.service.ts
- src/server/src/region-configs/controllers/region-configs.controller.ts
- src/server/src/region-configs/services/region-configs.service.ts
- src/shared/constants.ts
- src/shared/entities.d.ts
This adds a button to projects for archived 2010 regions, allowing them to be converted to new 2020 regions.
2010 map:
Converted map:
The conversion process _mostly_ worked for the state I tested (DE), but note the 5 clearly incorrectly assigned blocks (4 of which have 0 population?), which I'm assuming is a data quality issue with the crosswalk file we need to look into further.
Overall the file format was more complex than I had initially assumed, and our conversion process is going to be inherently lossy, as census block boundaries don't entirely align from 1 census to the next.
- Create a plan for a region that is on both our [2010 states list](https://docs.google.com/spreadsheets/d/1NW7P_W23OIFrMGKVvvQpaj2CbaXZfmxBFcgQU92i-08/edit#gid=0) currently on production as well as our [list …
> Convert 2010 census region maps to 2020 census regions

- CHANGELOG.md
- src/client/components/map/ProjectDistrictsMap.tsx
Show unassigned district on project minimap, in order to ensure state borders are visible.
Closes #873
> Show unassigned district on project minimap

- CHANGELOG.md
- src/client/components/MapHeader.tsx
- src/client/components/map/KeyboardShortcutsModal.tsx
- src/client/components/map/Map.tsx
- src/client/components/map/keyboardShortcuts.ts
- src/client/screens/ProjectScreen.tsx
- Fixes the bug identified in #860 where the paintbrush slider rendered over top of the keyboard shortcuts modal
- Finalizes the UX improvements to paintbrush slider that were began in #871 . It was never explicitly spec'd out when the paintbrush size slider should be displayed, and it previously was not displaying the paintbrush slider if a user selected the paintbrush tool via keyboard shortcuts
- Adds new keyboard shortcuts for incrementing / decrementing the size of the paintbrush tool
Keyboard shortcuts weren't explicitly asked for around the paintbrush size slider, but they certainly are fun to use 😀 
I kind of randomly went with `B` and `M` for the increment / decrement functionality - perhaps there might be better choices here, @jfrankl ? 
- Go to a project, select the paintbrush …
> Fix overlap between keyboard shortcuts and paintbrush slider

- CHANGELOG.md
- src/client/api.ts
- src/client/components/CopyMapModal.tsx
- src/client/reducers/projectData.ts
- src/client/reducers/projects.ts
- src/server/migrations/1628170922516-rename_project_fields_to_match_convention.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/projects/entities/create-project.dto.ts
- src/server/src/projects/entities/project.entity.ts
- src/server/src/projects/services/projects.service.ts
In the course of investigating #881 I encountered two issues:
- Duplicated projects lost their `projectTemplate` reference
- Archiving a project would cause the page it was on to lose items. Archiving all projects on the page would cause it to revert to the "No projects" state you see when you first join
I fixed the first by creating a new project duplicate endpoint (I explored adding the missing fields to the SQL query in `ProjectsService` but decided this way was less brittle, as we won't need to update it as we add new fields.
- On the Home Screen, duplicate a project that is visible & associated w/ and organization `ProjectTemplate`. The duplicate project should appear on the Organization Admin screen.
- Archive a project from the Home Screen - the list of projects should refresh but …
> Clean up Home Screen project handling

- CHANGELOG.md
- src/client/components/ImportFlagsModal.tsx
- src/client/screens/ImportProjectScreen.tsx
- src/server/migrations/1628016680955-region_census_year.ts
- src/server/migrations/1628016841545-region_census_year_defaults.ts
- src/server/src/districts/controllers/districts.controller.ts
- src/server/src/region-configs/entities/region-config.entity.ts
- src/server/test/districts.controller.e2e-spec.ts
- src/shared/constants.ts
- src/shared/entities.d.ts
Imports were returning such large numbers of errors that it was generating `PayloadTooLargeError` errors. It seems this was _mostly_ due to invalid block IDs from using 2020 block equivalency files for (likely exported from another tool, such as Dave's Redistricting) for a state for which we have 2010 data.
I addressed this specific case by marking an excessive number of invalid block IDs w/ the correct state FIPs as file-level error and include the expected census year in returned error.
In addition to that, I _also_ added a cut-off for the number of flags, displaying only the first 1000, and I cleaned up the flags modal to correctly scroll when there are  large number of flags.
- Set up a NJ region using 2010 data (`s3://global-districtbuilder-dev-us-east-1/regions/US/NJ/2020-09-09T14:19 …
> Clean up import error handling

- CHANGELOG.md
- src/client/reducers/projectData.ts
- src/server/migrations/1628182840067-project_version.ts
- src/server/migrations/1628546956803-project_version_default.ts
- src/server/src/project-templates/controllers/project-templates.controller.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/projects/entities/project.entity.ts
- src/server/src/projects/services/projects.service.ts
Adds cache-busting to the `districts` column by tracking the `version` of `RegionConfig` on the new `Project.regionConfigVersion` field, and regenerating the column when they are out-of-sync.
We only make use of district feature geometries outside the project screen for the most part, so it was relatively easy to contain needing to regenerate the `districts` column to the use of the GeoJSON export endpoint, with a few exceptions:
- I changed the definition of "completed" on the Community from having no population in the unassigned district to having no features in the unassigned district (you could have only blocks w/ no population left before and we'd consider it "complete").
- The organization admin CSV map export won't recalculate districts; if this is desired I'll open a follow-on …
> Districts cache busting

- CHANGELOG.md
- src/client/actions/districtDrawing.ts
- src/client/components/evaluate/ProjectEvaluateMetricDetail.tsx
- src/client/components/evaluate/ProjectEvaluateSidebar.tsx
- src/client/components/evaluate/ProjectEvaluateSummary.tsx
- src/client/components/map/Map.tsx
- src/client/reducers/districtDrawing.ts
- src/client/screens/ProjectScreen.tsx
- src/client/types.d.ts
Hides the competitiveness summary in the Evaluate sidebar when political data is missing for the region. Accomplishes this by adding a "showInSummary" attribute to the EvaluateMetrics so that they can be toggled on and off in the sidebar.
- Putting in a special-purpose check for competitiveness would have been very slightly easier, but the approach I took seemed like it would pay off in the long run if we need to toggle metric summaries for other reasons (e.g. on a per-organization basis), so I opted for the more general approach.
- I put the formatting in a separate commit because there was a lot of it relative to the substantive changes. I'm planning to squash before merging to keep the commit history uncluttered, but I would also be happy to leave them separate, which might make it …
> Hide competitiveness summary when there's no voting info

- src/server/src/projects/controllers/projects.controller.ts
Adding `Project.region_config_version` as part of #884 as a not-null field unintentionally broke project creation.
On `develop` you can't create new projects. On this branch you can.
> Fix creating projects

- CHANGELOG.md
- src/server/src/organizations/services/organizations.service.ts
We were not returning `districts_definition` as part of Organization project templates, which prevented them from being used when creating projects from them.
The existing use of `leftJoinAndSelect(...)` wasn't quite right - because the calls to this method came _before_ the later call to `select(...)`, these did not select any fields and functioned the same as `leftJoin(...)`. By switching to use `addSelect(...)` instead of `select(...)` we can omit the fields for all tables that use `leftJoinAndSelect(...)`. Similarly we can omit the `Organization` fields by using `select(...)`.
Add a `districts_definition` to an existing `project_template` row, or construct a `project_template` from an existing project using SQL:
```sql
INSERT INTO project_template
(name, number_of_districts, …
```
> Fix creating project from template with existing districts definition

- CHANGELOG.md
- deployment/terraform/app.tf
- deployment/terraform/cloud-config/base-container-instance.yml.tmpl
- deployment/terraform/config.tf
- deployment/terraform/container_service.tf
- deployment/terraform/iam.tf
- deployment/terraform/variables.tf
I made the following changes to support allocating over 30 GB of memory to the app server for the updated Census:
- Create an Auto Scaling group and launch template based on the [Terraform 0.12 branch](https://github.com/azavea/terraform-aws-ecs-cluster/tree/feature/jrb%2Fterraform-0.12) of our ECS cluster module.
- Make changes to work with the existing ECS cluster and security group resources.
- Stand up a second ECS service for the application server that uses the [EC2 launch type](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_types.html#launch-type-ec2).
- Make use of the [`awsvpc` network mode](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-networking-awsvpc.html) to preserve the existing target group, allowing a zero-downtime deployment. 
In …
> Create auto scaling group and stand up new app service

- CHANGELOG.md
- src/client/components/map/Map.tsx
Hides the minority majority evaluate layer when not on the majority race detail view
- Toggle evaluate mode, then the majority/minority race view, then leave evaluate mode. On `develop` the map layers will not reset correctly, on this branch they will.
Closes #903
> Hide minority majority evaluate layer when not on detail view

- CHANGELOG.md
- src/server/src/projects/services/projects.service.ts
It seems like some of our NJ data has invalid polygon data in it due to rounding points of a very small hole such that all corners are exactly equal.
This tripped up the simplification library, which caused the page to not load.
We probably can't find/fix every such data issue like this, so I made the simplification a bit more granular and have it just skip past any polygons it has issues with (and return them unsimplified).
Hopefully all the problematic polygons are similarly small, so it won't be an issue that we don't simplify them.
The specific MultiPolygon throwing off `simplify`:
```
{
"id":9,
"type":"Feature",
"geometry":{
"type":"MultiPolygon",
"coordinates":[
[
...
],
[
[
[
-74.33104881808818,
41.186675416504166
],
[
-74.33104881808818,
41.186675416504166
],
[
-74.33104881808818, …
```
> Fix community maps page

- CHANGELOG.md
- src/client/components/PaginationFooter.tsx
To simplify the UI, hides pagination when there is only one page.
- On My Maps, if you have 10 or fewer maps, you should not see the pagination; duplicate maps until you have 11 or more, at which point you should see the pagination
- Alternatively, on My Maps, if you have more than 10 maps: you should see pagination at the bottom of the page; delete maps until you have 10 or fewer, or start a new account; you should no longer see the pagination
> Hide pagination when only one page

- src/client/reducers/projects.ts
Without this fix, setting a state filter could show no results incorrectly because there aren't multiple pages of results.
Closes #XXX
> Reset pagination when setting community maps region filter

- src/client/reducers/projects.ts
Turns out it wasn't trivial - this caused the bug in #885 of duplicate requests on page load to return.
Reverts PublicMapping/districtbuilder#920
> Revert "Reset pagination when setting community maps region filter"

- src/server/src/projects/services/projects.service.ts
The previous fix to simplification in #911 caused a regression in performance
Instead of simplifying on a polygon-by-polygon basis, it seems we weren't actually returning simplified data at all anymore
Cleaning the data fixed the one case we knew of invalid polygon data, though I left the try/catch in place in case new data causes a similar issue.
- On `develop`, look at response size of the `globalProjects` endpoint in network tab of the developer tools, and compare it to this branch. You should see a reduction in size.
> Fix simplification regresssion

- CHANGELOG.md
- src/server/src/projects/services/projects.service.ts
Makes archived projects no longer displayed in the community maps view
- Create a completed project and archive it
- Go to the community maps page. It will still show up on `develop`, but should be hidden here
Closes #925
> Hide archived projects from community maps view

- src/client/components/MapHeader.tsx
Minor style cleanup for paintbrush size panel.
To reduce the size of this panel (so it wouldn't cover as much of the map), I made the following changes:
- Used smaller text
- Reduced slider width
- Reduced panel padding
- Switch to paintbrush drawing mode
- The panel should look similar to the attached screenshot
> Style cleanup for paintbrush size panel

- CHANGELOG.md
- src/client/components/map/ProjectDistrictsMap.tsx
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/projects/entities/project.entity.ts
- src/server/src/projects/services/projects.service.ts
Some of our projects on production are from before we were caching 'districts', and don't have a precomputed districts column for us to use.
Gracefully handle these cases in by simply not displaying a mini-map in the frontend and skipping simplification in the backend.
- Null out the `districts` column of your projects (I simply ran `UPDATE project SET districts = NULL` in a SQL shell).
- On `develop` the Home Screen will crash
- On this branch it should load, but not display the mini-map
> Properly handle Projects with a null districts column

- src/client/App.tsx
- src/client/components/SiteHeader.tsx
This reverts commit cac25cd1c9f5619c91c8109624b88fa401fe85a1.
We hid the page because it was too slow to load on production, I've created https://github.com/PublicMapping/districtbuilder/issues/934 to track this
> Revert "Temporarily hide Community Maps page"

- CHANGELOG.md
- src/client/components/DemographicsTooltip.tsx
- src/client/components/ProjectSidebar.tsx
Implements approved design for Majority-Minority race chart. This fell off my radar for the larger style pass. 
- Create a Majority-Minority district
- You should see a dashed line appear next to the chart in the sidebar
- Upon hovering the chart, you should see a dashed line next to "Majority-minority district"
> Style cleanup for Majority-Minority race chart

- CHANGELOG.md
- src/server/src/projects/controllers/projects.controller.ts
This is a regression introduced by #897 
Date objects are never equal to each other, so we were always recreating the geojson, which made it impossible to load projects for archived regions
- Create a project for a 2010 region
- Archive the region and add a new 2020 region for the same state. You should be able to convert your project to use the new 2020 region.
> Fix export geojson endpoint

- CHANGELOG.md
- deployment/terraform/container_service.tf
- src/server/src/districts/services/topology.service.ts
This fixes two separate issues that prevented us from starting to rollout new 2020 data:
- The new EC2-based deployment strategy was accidentally referencing the old container image, which was limited to 30Gb of memory due to Fargate compatibility. Fixed in https://github.com/PublicMapping/districtbuilder/commit/312ea4c61ce12dfff125ad135f0481da92e165ae
- We refactored topology service to load archived regions before loading active regions, but this broke in staging, which indirectly ended up calling `Object.freeze` on the `_layers` private member variable of `TopologyService` as part of the health check, which then broke loading topologies. Fixed in https://github.com/PublicMapping/districtbuilder/commit/8b97b0308b551f0213c463a73d34479c8ed3783b
This has already been tested on staging, but …
> Increase ECS memory and fix health check

- CHANGELOG.md
- src/server/src/districts/services/topology.service.ts
On occasion we have encountered issues downloading the required JSON files for the `TopologyService` to load, and adding more states / increasing application resources seems to have increased the frequency of this.
Retrying on errors should enable us to get past any transitory errors w/o having to redownload / parse all the states we have already loaded
Closes #XXX
> Retry on topology errors

- deployment/terraform/app.tf
- deployment/terraform/task-definitions/app.json.tmpl
- deployment/terraform/variables.tf
- docker-compose.yml
- src/server/src/healthcheck/healthcheck.controller.ts
Allows changing the timeout for the database healthcheck via environment / Terraform variables
I haven't updated the `.tfvars` files yet for staging / production
- Running `scripts/infra plan` should request a value for `healthcheck_db_timeout` and the plan should show it threaded through to the container
- Turning off your local database and then hitting [http://localhost:3005/healthcheck](http://localhost:3005/healthcheck) should timeout based on the passed in environment variable.
> Parameterize database healthcheck timeout

- CHANGELOG.md
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/projects/entities/project.entity.ts
Fixes the error identified [https://rollbar.com/Azavea/DistrictBuilder/items/66/?item_page=0&](here): 
```
TypeError: project.exportToCsv is not a function
```
I'm not sure entirely what's going on here, aside from that this was changed in #878 as part of a refactor. When I reverted these changes by moving the function back into the controller, the issue appears to have been resolved.
- Go to a project that is created by another user and click export
- Expect export is successful
> Fix CSV export for other user's projects

- CHANGELOG.md
- deployment/terraform/app.tf
- deployment/terraform/task-definitions/app.json.tmpl
- deployment/terraform/variables.tf
- docker-compose.yml
- src/server/src/healthcheck/healthcheck.controller.ts
I made the following changes in order to make it easier to tune different aspects of our health checks:
- Parameterized health check timing at the [target group level](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html).
- Refactored `HEALTH_CHECK_DB_TIMEOUT` → `TYPEORM_HEALTH_CHECK_TIMEOUT`.
See that Terraform is up-to-date.
```console
docker-compose -f docker-compose.ci.yml run --rm terraform
export GIT_COMMIT=96ec7f1
./scripts/infra plan
. . .
No changes. Infrastructure is up-to-date.
```
See that health checks in the EC2 and ECS console match what is codified in the .tfvars file:
<details>
</details>
<details>
</details>
> Add levers to tune LB health check configuration

- CHANGELOG.md
- src/server/src/main.ts
Fix CSV import by allowing JSON payloads of up to 50mb, instead of the default which was originally 100kb
- Attempt to upload the attached CSVs and create new projects for them. Note that PA requires 2020 data 
Closes #945
> Fix CSV import

- CHANGELOG.md
- src/client/components/evaluate/detail/Competitiveness.tsx
Disables the send to plan score button for any projects that have unassigned areas
- Create an incomplete project and go to Evaluate Mode -> Competitiveness
- Expect: the Send to Plan Score button is disabled
- Complete the project, then return to Competitiveness page
- Expect: the Send to Plan Score button is now enabled again
Closes #906
> Disable Send to Plan Score button for incomplete projects

- CHANGELOG.md
- src/server/src/projects/controllers/projects.controller.ts
Fixes an issue I encountered in the course of testing #957 
Also refactors the `getProjectWithDistricts` method to remove redundant SQL WHERE clauses.
- Attempt to submit PlanScore data for another users project. On `develop` this will fail w/ status code 401. On this branch it will return 200 (unless the PlanScore API is still down, in which case it will return 502).
> Allow retrieving the PlanScore for another users project.

- CHANGELOG.md
- src/client/App.tsx
- src/client/components/PaginationFooter.tsx
- src/client/components/SiteHeader.tsx
- src/manage/package.json
- src/manage/src/commands/create-random-projects.ts
- src/manage/yarn.lock
- src/server/migrations/1629680461750-project_index.ts
- src/server/src/projects/entities/project.entity.ts
Adds indexes to speed up accessing the `project` table, as well as a script to generate test data for the purpose of verifying the indexes work.
Also cleans up the pagination footer component to better handle large number of pages.
We'll likely want to manually apply this migration to production, so that we can use `CREATE INDEX CONCURRENTLY ...` (which isn't allowed in a transaction, and so can't be run in a migration).
We should be able to safely add the index before deploying this fix to production.
- Ensure you have at least 1 region & 1 user in your database
- **At the end of the day,** run `scripts/manage create-random-projects 15000`, and then wait **5+ hours**.
- You should be able to load the `/maps` page in a reasonable amount of time.
- If you revert the …
> Speed up community maps

- CHANGELOG.md
- src/client/components/PVIDisplay.tsx
- src/client/components/ProjectSidebar.tsx
- src/client/components/VotingSidebarTooltip.tsx
- src/client/functions.ts
We were incorrectly including other party vote totals in calculating vote share for PVI, which should instead use the two-party vote share to calculate vote totals.
_Edit_ Additionally, we were calculating the 16 / 20 combined averages incorrectly, fixed in https://github.com/PublicMapping/districtbuilder/pull/977/commits/4f9224540feb152a37b97f4f6e19c7513f833ade
On `develop` we incorrectly calculate PVI for AZ as R+8 when it should be ~R+4~ R+3.
Fixed PVI calculations, as well as omitting "other party" from the tooltip:
Changing the tooltip for PVI means there will be a discrepancy between what we show in the PVI tooltip (two party vote) and what we show on the map tooltip / other voting metric tooltips, where we will include thrid parties when calculating vote total percentage,
- …
> Fix PVI calculation

- CHANGELOG.md
- src/client/screens/HomeScreen.tsx
Updates copy on the home screen shown to users w/o any maps yet.
- Create a new user, you should be redirected to the home screen
- Observe the extra sentence. It should link to [this wiki page](https://github.com/PublicMapping/districtbuilder/wiki/Join-an-Organization)
Closes #983
> Update copy on Home screen

- CHANGELOG.md
- src/client/components/map/MapTooltip.tsx
Don't show political data for regions w/o it (like the Dane County hidden region)
- Create a map for a region w/o political data, like Dane County
- Hover over a blockgroup on the map - the tooltip should not show poltical data
- Maps for regions with political data, such as DE 2020, should continue to show it in the tooltip
Closes #972
> Don't show voting data in map tooltip for regions w/o it

- CHANGELOG.md
- src/client/components/map/Map.tsx
Hides the copy & convert to 2020 overlay / button for archived 2010 maps when  looking at another users map.
The button wouldn't work in this case anyways, so this should silence some Rollbar errors.
Visible in the logged in browser, not visble in the not logged in incognito window:
- Using `scripts/dbshell`, set a region for which you have projects to be `archived`
- If you go to a project of yours for that region, you should the copy / convert overlay (note that unless your archived region was for 2010 & you have a non-archived 2020 region configured for the same state, the convert button won't work)
- Go to that same project as another user, or while logged out. You should not see the overlay.
Closes #982
> Hide copy/convert button for other users maps

- CHANGELOG.md
- scripts/yarn
- src/server/migrations/1629680461750-project_index.ts
- src/server/package.json
PR #969 added indexes to the `project` table, but in production this table is quite large and we'd prefer not to lock it while building an index. PostgreSQL has support for creating indexes concurrently, but by default we couldn't use that in a migration, as migrations are wrapped in a transaction by TypeORM, and `CREATE INDEX CONCURRENTLY` cannot be run in a transaction.
Due to the above, we had planned to manually create these indexes in production and add a row to the `migration` table ourselves (#975), however a discussion w/ @KlaasH and a more careful reading of the docs showed a more standard option - rather than apply these manually , we're temporarily turning off transactions for migrations until after our next release by passing the `-t=false` option, at which point we'll make …
> Create indexes concurrently

- CHANGELOG.md
- scripts/load-dev-data
- src/client/actions/projectData.ts
- src/client/components/DemographicsTooltip.tsx
- src/client/components/ProjectSidebar.tsx
- src/client/constants/colors.ts
- src/client/functions.ts
- src/client/reducers/undoRedo.ts
- src/manage/dev-data/azavea.yaml
- src/server/src/project-templates/entities/project-template.entity.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/projects/entities/project.entity.ts
- src/server/src/projects/entities/update-project.dto.ts
- src/shared/constants.ts
- src/shared/entities.d.ts
- src/shared/functions.ts
In the first of what we anticipate to be a number of such requests, Dane County has asked to support both "Other" and "Multiracial" as demographics, in addition to the demographics we already have for WI.
To support this, I've removed our hardcoded list of fields we support to instead be based on what is configured in the `static-metadata.json` configuration file we create when preprocessing data.
We still have a hard-coded list that we use for sorting though, instead of relying solely on the sort order in `static-metadata.json` (any fields not on the hard-coded list, like "Multiracial", will sort to the end of the grouping).
Note the "Other" and "Multiracial" columns:
Pinning works for the new column:
Existing region still working as expected:
- Using `scripts/dbshell`, run `TRUNCATE …
> Use JSON configuration to control fields displayed in metrics table

- CHANGELOG.md
- src/client/api.ts
- src/client/screens/PublishedMapsListScreen.tsx
Updates the region config dropdown in the community maps page by region code
- Go to community maps page and click on the dropdown
- Expect regions to be sorted by region code
Closes #993
> Sort region configs by region code

- deployment/README.md
After switching to the new EC2-based ECS deployment system, the process for reloading tasks has changed somewhat.
Follow the README instructions to reload data for a region on staging (for example you could temporarily revert MA 2020 data to an older version from the [tracking spreadheet](https://docs.google.com/spreadsheets/d/1khiNAQp4UnfkgfvRSbfjDU9CU2zJrJ0pMRUeF5a4cuM/edit#gid=645349603) w/o political data.
If you follow the steps correctly, when you're finished a map for the region you updated should update when you view it to show the new data (if you use the example above, you'll see the political data for your MA maps go away).
Closes #947
> Update deployment README section on restarting services

- CHANGELOG.md
- package.json
- src/server/package.json
- src/server/src/projects/services/projects.service.ts
- src/server/yarn.lock
- yarn.lock
Set the tolerance to .001 instead of .005 for small units with an area than less than 1 (?) for the simplification used to improve performance for mini-maps that inadvertently caused rendering issues for DC and other small regions.
- Create and complete projects for DC and RI
- Look at them in the community maps viewer; expect the mini-maps to render properly
Closes #994
> Reduce tolerance for simplification for small regions

- CHANGELOG.md
- src/client/api.ts
- src/client/components/AddReferenceLayerModal.tsx
- src/client/components/ConfirmJoinOrganization.tsx
- src/client/components/JoinOrganizationModal.tsx
- src/client/components/OrganizationTemplates.tsx
- src/client/components/TemplateCard.tsx
- src/client/screens/CreateProjectScreen.tsx
- src/client/screens/OrganizationScreen.tsx
- src/client/types.d.ts
- src/manage/src/lib/dbUtils.ts
- src/server/migrations/1632492690026-reference_layers_template_column.ts
- src/server/migrations/1632512688121-reference_layers_constraint.ts
- src/server/src/organizations/services/organizations.service.ts
- src/server/src/project-templates/entities/project-template.entity.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/projects/entities/create-project.dto.ts
- src/server/src/projects/projects.module.ts
- src/server/src/reference-layers/entities/reference-layer.entity.ts
- src/server/src/reference-layers/reference-layers.module.ts
- src/server/src/reference-layers/services/reference-layers.service.ts
- src/shared/entities.d.ts
Adds an option to associate a project template with a reference layer, and then copies that that reference layer to the project when creating a project from that template.
Part of this includes a larger refactor to how creating templates from projects works (https://github.com/PublicMapping/districtbuilder/commit/85618ae611be4c9625279b88d9eabf39506ee631), moving most of the logic for copying fields from template -> project from the client to the server.
I considered instead of copying reference layers, changing the ManyToOne relation to a ManyToMany and 
- Add a reference layer to an existing project, then update it to instead point to a project template:
`UPDATE reference_layer SET project_id = NULL, project_template_id = '<uuid_here>';`
- Create a project using the …
> Project template reference layers

- CHANGELOG.md
- src/client/screens/ImportProjectScreen.tsx
This regression was caused by the refactor in a13ff4 - by no longer explicitly listing fields we allowed extra fields to be included in the POST data.
- Export one of your maps, and attempt to import it. On `develop` the import will fail, on this branch it should succeed
Fixes #1027
> Fix map CSV import

- CHANGELOG.md
- scripts/load-dev-data
- src/client/actions/organization.ts
- src/client/api.ts
- src/client/components/OrganizationTemplateForm.tsx
- src/client/components/OrganizationTemplates.tsx
- src/client/components/TemplateCard.tsx
- src/client/reducers/organization.ts
- src/client/screens/CreateProjectScreen.tsx
- src/client/screens/ImportProjectScreen.tsx
- src/client/screens/OrganizationScreen.tsx
- src/server/src/districts/controllers/districts.controller.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/projects/entities/create-project.dto.ts
- src/server/src/users/controllers/users.controller.ts
- src/shared/entities.d.ts
Allows selecting a project template during organization import
A bit going on here to make this feature work.
The general workflow is:
- Upload a CSV, it gets validated against the primary state `RegionConfig`
- We also check to see if the user's organizations have project templates that match the CSV. If so we allow to select an organization/template
- After a template is selected, we _re_-upload the CSV to validate it against the `RegionConfig` for the template, which may be different (a county of the state in question, or one w/ different data or split census blocks).
- Use `scripts/load-dev-data` to setup your `region_config` table (`TRUNCATE region_config CASCADE;` is a quick way to nuke your current regions first)
- The `scripts/load-dev-data` test organization has two templates …
> Import w/ project template

- CHANGELOG.md
- scripts/load-dev-data
- src/client/api.ts
- src/client/components/MultiMemberForm.tsx
- src/client/components/ProjectSidebar.tsx
- src/client/components/Tour.tsx
- src/client/components/evaluate/ProjectEvaluateSidebar.tsx
- src/client/components/evaluate/detail/EqualPopulation.tsx
- src/client/components/map/Map.tsx
- src/client/components/map/index.ts
- src/client/functions.ts
- src/client/reducers/regionConfig.ts
- src/client/s3.ts
- src/client/screens/CreateProjectScreen.tsx
- src/client/screens/ImportProjectScreen.tsx
- src/client/types.d.ts
- src/manage/dev-data/azavea.yaml
- src/manage/src/commands/create-random-projects.ts
- src/manage/src/commands/update-organization.ts
- src/server/migrations/1635542647717-number_of_members.ts
- src/server/migrations/1635542832040-number_of_members_default.ts
- src/server/migrations/1636047799212-chamber_number_of_members.ts
- src/server/src/chambers/entities/chamber.entity.ts
- src/server/src/project-templates/entities/project-template.entity.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/projects/entities/create-project.dto.ts
- src/server/src/projects/entities/project.entity.ts
- src/server/src/projects/entities/update-project.dto.ts
- src/shared/entities.d.ts
Adds support for making a project use multi-member districts when creating / importing it.
Multi-member projects will have different population targets, based on the number of representatives per district (e.g. we're targeting equal population per _representative_, which thus far has been the same as equal population per district).
Creating a multi-member project:
Importing:
Evaluate mode Equal pop. detail:
The original issue didn't call for adding `multi-member` support to Project Templates or Chambers, but it was a relatively small part of this overall feature, and something we've discussed wanting to support.
Similarly, we hadn't fully considered how multi-member would affect Evaluate mode (which calculates equal pop. / district) or the Tour (which references the district target pop.). …
> Add support for multi member districts

- CHANGELOG.md
- src/client/components/evaluate/detail/Competitiveness.tsx
Fixes a few small problems problems w/ the PlanScore integration on the Competitiveness Evaluate screen:
- The "Send to PlanScore" button would get stuck in a sending state if PlanScore returned an error
- We only enabled the button when your map was fully done, which it turns out is more strict than PlanScore requires
- The styling made it a bit annoying to see the "View on PlanScore" link
Contrary to the reported issue I didn't encounter issues w/ PlanScore, other than their site being a bit slow.
To test out the Toast message I temporarily commented out the check disabling the "Send to PlanScore" button (PlanScore consistently returns an error when we provide all empty districts):
```diff
diff --git …
```
> Improve Planscore integration

- CHANGELOG.md
- src/client/actions/projectData.ts
- src/client/api.ts
- src/client/components/MultiMemberForm.tsx
- src/client/components/ProjectDetailsModal.tsx
- src/client/components/ProjectName.tsx
- src/client/functions.ts
- src/client/reducers/projectData.ts
- src/client/screens/CreateProjectScreen.tsx
- src/client/screens/ImportProjectScreen.tsx
- src/client/screens/ProjectScreen.tsx
- src/server/src/projects/controllers/projects.controller.ts
Allows editing name, pop. deviation, and multi-member settings via a new modal on the Project screen
- Create a new map or go to an existing map and use the "..." menu button in the header next to the project name to open the Map Configuration modal
- Saved changes should be reflected (sidebar updating, name changing, etc)
- Validation errors should be displayed in the form (e.g. deviation > 100)
- The "..." menu should _not_ be shown for a public map that is not yours (or while you are not logged in)
Closes #1025
> Add Map Configuration modal to project screen

- CHANGELOG.md
- src/server/src/region-configs/controllers/region-configs.controller.ts
The community maps page dropdown is currently showing duplicate states. This adds an option to ensure hidden regions are filtered out as part of the query request used to populate the dropdown (`api/region-configs/`).
New dropdown should not display duplicate options:
SQL query output by `.scripts/server` includes hidden filter, highlighted below:
- Run `./scripts/server` and navigate to the community maps screen: `http://localhost:3003/maps`
- Click on the "Filter by State:" dropdown and confirm there are no duplicates
- In terminal, confirm SQL query output by `.scripts/server` includes hidden filter in the WHERE clause (see query in the Demo section)
Closes #1047
> Fix duplicate regions in Community Maps dropdown

- CHANGELOG.md
- src/client/components/evaluate/ProjectEvaluateMetricDetail.tsx
- src/client/components/evaluate/ProjectEvaluateSidebar.tsx
- src/client/components/evaluate/ProjectEvaluateSummary.tsx
- src/client/components/evaluate/detail/Competitiveness.tsx
- src/client/components/evaluate/detail/CompetitivenessChart.tsx
- src/client/functions.ts
- src/client/types.d.ts
Update the Competitiveness metric on the Evaluate panel to instead display PVI breakdown by districts, according to the following format:
- By partisan breakdown i.e. “4 R / 5 D” or “5R / 1E (Even) / 2D” 
- Colored according to party color within Heading of `CompetitivenessMetricDetail`
- “N/A” if districts' PVI data is undefined
Expected display within `CompetitivenessMetricDetail`:
Expected display of Competitveness metric within `ProjectEvaluateView`:
Since the competitiveness metric now uses `pviByDistrict` (derived from `pviBuckets` passed down through props) instead of a competitiveness value as well as implements `formatPviByDistrict` for party labelling and coloring, we no longer need `value` and `party` to be updated for this metric. However, I’ve kept the …
> Update Competitiveness metric on Evaluate 

- CHANGELOG.md
- package.json
- src/client/components/evaluate/ProjectEvaluateSidebar.tsx
The copy describing county splits wasn't always reflecting the right terminology that matched the top level geo of the map. This PR changes the copy to use the same word as the "County Splits" title.
- Run `./scripts/server`
- Create a Dane County map using the Azavea's project template
- Click "Evaluate". You should see "Ward Splits" at the bottom under "Optional", as well as the word "ward" where there was the word "county".
- Create another map of anywhere but Dane County and click "Evaluate". The sidebar should now say "County Splits" and use the word "county".
Closes #1057
> Change "county" in County Split copy

- CHANGELOG.md
- Vagrantfile
Some computers were killing the server while trying to run the VM due to the allotted memory for the VM being too small. This PR increases the allotted memory.
I'm not sure what the ideal increase in memory is; this was enough for my computer to let the server run without seeming like an unnecessary amount of memory.
- Run `vagrant up`, then `vagrant ssh`, and then `./scripts/server`
- If you open up the VirtualBox UI you should see that your VM's base memory has increased to 8192 MB
- Let the server start up and let it run for a few minutes. If your server was repeatedly being killed (like mine) with the original memory allotment, it should run without being killed now
> Increase VirtualBox memory in Vagrantfile

- CHANGELOG.md
- src/client/types.d.ts
- src/manage/src/commands/create-random-projects.ts
- src/server/src/chambers/chambers.module.ts
- src/server/src/chambers/services/chambers.ts
- src/server/src/districts/entities/geo-unit-topology.entity.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/projects/entities/project.entity.ts
- src/shared/entities.d.ts
We'll need to run `UPDATE region_config SET version = NOW();` after deploying this, to trigger a cache invalidation for all cached districts geojson.
- Create a project for a region, (make sure to choose a chamber, instead of selecting "Custom" and entering a number of districts)
- Exporting the geojson for that project should show a new top-level `metadata` field with project-level properties
- If you update the project, or duplicate it from the homescreen flyout menu, the metadata should still be present
- If you duplicate another users project, the `creator` prperty in the `metadata` should be updated
Closes #1044
> Add project-level metadata property to geojson export

- CHANGELOG.md
- src/client/components/ProjectReferenceLayers.tsx
When viewing another user's map, the Reference Layer modal showed the same language as when viewing your own map about adding a layer. This PR changes that language to reflect the map's readonly status.
New language when viewing another person's map.
- Run `./scripts/server`
- Open another user's map
- Click on the Reference Layers modal at the bottom of the sidebar. It should say "This map has no reference layers. Copy the map to your account to add reference layers."
Closes #1032
> Change copy under Reference Layers on other users' maps

- CHANGELOG.md
- src/client/components/SupportMenu.tsx
This PR adds a link to DistrictBuilder's Medium blog to the app's Resources menu.
- Run `./scripts/server`
- Click on the "Resources" tab in the righthand corner of the screen. You should see "Blog" as an option in the dropdown menu.
- Click on "Blog". It should bring you to the DistrictBuilder Medium webpage.
Closes #1026
> Add link to Medium blog to Resources menu

- CHANGELOG.md
- src/client/components/evaluate/ProjectEvaluateSidebar.tsx
Updates the status value for the Equal Population metric used to toggle between a green check and error image in the ProjectEvaluateSummary and ProjectEvaluateMetricDetail. Ensures that the filter used to gather districts with geometries doesn’t include the transparent placeholder “district”.
- Ensure you have region configs for NY and import map: https://app.districtbuilder.org/projects/b9e492df-3acc-45bd-9b99-65810a48b29b 
- Confirm that green check mark displays in Equal Population summary 
- Confirm that green check mark displays in Equal Population detail
- In a different map, confirm image status still correctly displays as a red "x" when districts are outside of deviation threshold
Closes #1073
> Fix Equal Population status

- CHANGELOG.md
- src/client/screens/PublishedMapsListScreen.tsx
User data was not appearing on the Community Maps page when either navigated to directly or on page reload.
- Run `vagrant up` &#8594; `vagrant ssh` &#8594; `./scripts/server`
- Navigate to **localhost:3003/maps**. The header and the user data should appear to the left as they do on all other pages.
- Refresh the page. Verify that the header and user data do not disappear.
Closes #1006
> Fix disappearing user data on community maps page

- CHANGELOG.md
- src/client/screens/ImportProjectScreen.tsx
Initially the error message indicating that the user had chosen too few districts for the CSV provided was only displayed when the custom number of districts was too small. This PR adds the error message when the chosen chamber has too few districts, as well.
- Run `vagrant up` &#8594; `vagrant ssh` &#8594; `./scripts/server`
- Find a csv of a state with more districts than chamber districts. I used one [this one](https://app.districtbuilder.org/projects/b45854cb-b318-492b-9a12-3dd96da1f862), which has 22 districts compared to Illinois' 18 House of Representative districts.
- Navigate to **http://localhost:3003/import-project** and import your csv.
- Click the "House of Representatives" district choice. The error message should appear.
Closes #1028
> Display error message when there are too few districts in chamber

- CHANGELOG.md
- src/server/src/districts/controllers/districts.controller.ts
Upgrading Node.js on the backend uncovered a lingering performance issue in the CSV import in our use of `Math.max`, which we are using to detect the maximum district ID in the CSV. This caused the import to fail for larger states.
Per MDN, using `Math.max(...array)` on a large array is not recommended, and instead they suggest using reduce:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/max#getting_the_maximum_element_of_an_array
Switching to the form suggested by MDN for large arrays fixed the issue.
I searched the codebase for similar problematic uses of `Math.min` or `Math.max` and this was the only one case where we were using it on a very large array.
- Attempt to import a map for a larger state like PA or NJ. On `develop` it will fail, on this …
> Switch to a more performant way of calculating maximum district ID

- CHANGELOG.md
- src/client/screens/CreateProjectScreen.tsx
- src/client/screens/HomeScreen.tsx
- src/client/screens/ImportProjectScreen.tsx
- src/client/screens/OrganizationScreen.tsx
- src/client/screens/ProjectScreen.tsx
- src/client/screens/PublishedMapsListScreen.tsx
This PR changes the title for the landing page, organization, community maps, map/project view, new map, and import project pages to provide better search optimization and insight into page content.
This new title is visible in the browser tab.
I tried to condense and centralize the logic of this into one place so that title changed at the parent component level using a dictionary mapping paths to titles to find and change each component's relevant title on path change. However, I ultimately decided that this method wasn't going to work with React's "no side effects" architecture, as it required the parent components to have an idea of what was happening with the smaller components. So I went with what feels like a clunkier but more React-friendly method.
- Run `vagrant up` &#8594; …
> Add more descriptive titles to app pages

- CHANGELOG.md
- deployment/terraform/scheduled_tasks.tf
- src/server/package.json
- src/server/src/commands/reindex.ts
- src/server/src/districts/services/topology.service.ts
- src/server/src/main.ts
- src/server/test/districts.controller.e2e-spec.ts
Our largest table gets many frequent updates, leading over time to index bloat.
I have been manually running `REINDEX TABLE CONCURRENTLY project`, but we would prefer to do this automatically, not manually.
This PR aims to achieve that by creating a [stand-alone Nest.js application](https://docs.nestjs.com/standalone-applications) which runs `REINDEX`, and then calling that via a scheduled ECS task.
- This is both our first scheduled ECS task as well as our first stand-alone Nest.js application, so I didn't have any internal examples to draw on. Other than the documentation, I also used this [blog post](https://vthub.medium.com/running-ecs-fargate-tasks-on-a-schedule-fd1ca428e669) for inspiration.
- ~This builds on top of #1099, I'll rebase this and change the base branch the PR is …
> Run reindex on monthly schedule

- scripts/update
Run npm rebuild to rebuild native server deps during `scripts/update`.
Should fix issues running `server` code as part of `scripts/update`.
I referenced https://stackoverflow.com/questions/66729013/why-is-importing-bcrypt-causing-a-cannot-find-module-napi-v3-bcrypt-lib-node-e and https://github.com/yarnpkg/yarn/issues/756 when trying to diagnose this
- See if CI passes?
> Run npm rebuild to rebuild native server deps during scripts/update

- CHANGELOG.md
- src/client/components/ProjectDetailsModal.tsx
The list of multi-member districts was not appearing in the Map configuration modal when the screen height was too short. This PR adds a minimum height to the `multiMemberContainer` to ensure that it always displays regardless of screen size and adds scrolling to the modal body while leaving the title and save/cancel buttons in place.
Screenshot taken from a 1280x680 window zoomed to 100% in Chrome.
The added `modalBodyContainer` was given a max height of 100vh-16rem; this amount was determined via experimentation to be what looked best in conjunction with the modal styling when both a normal size and when too short. 
- Run `./scripts/server` and navigate to one of your map project pages.
- Open the Map Configuration modal and shrink the screen to be shorter than the modal's height. It …
> Add scrolling to map config modal for viewing multiMember list

- CHANGELOG.md
- src/server/src/reference-layers/controllers/reference-layers.controller.ts
Creates a fix for the reference layers DELETE endpoint so that the page no longer crashes and a reference layer can be successfully deleted. The `ReferenceLayersController` used the `deleteOneBase` method by the `@Crud()` decorator to generate a DELETE endpoint, which ultimately did not match the api call from the frontend:
```
server_1    | [Nest] 39  - 02/01/2022, 9:52:47 PM     LOG [RouterExplorer] Mapped {/api/reference-layer/:id/:projectId, DELETE} route
```
The inconsistency is most likely a regression error after recent Node updates. Attempting to call at this generated endpoint also incorrectly queries the database and still returns a 404 status error. The new DELETE endpoint now matches the frontend call as well as the expected params for the TypeORM entity:
```
server_1    | …
```
> Fix error deleting reference layers

- CHANGELOG.md
- src/client/components/MapSelectionOptionsFlyout.tsx
PR https://github.com/PublicMapping/districtbuilder/pull/1085 added support for picking which demographic group to use for the race chart & majority/minority metric, but we were too broad in allowing any demographic group to be selected - we'd like to restrict this to known groups of VAP / CVAP / "All population" (the default).
- Add a region to the `region_config` table for Alhambra (s3://global-districtbuilder-dev-us-east-1/regions/US/CA/2021-10-15T19:36:24.429Z/)
- Create a map for that region
- On `develop` you should see a large number of options in the ⚙️ menu under "Districts" > "Population".
- On this branch it should be just All Population, VAP, and CVAP
Closes #1121
> Restrict population options on map selection menu to all, vap & cvap

- CHANGELOG.md
- README.md
- Vagrantfile
- docker-compose.yml
- package.json
This PR replaces chokidar with vagrant-notify-forwarder plugin and adds a check for the plugin to the Vagrantfile as well as a note about installing the plugin to the README.
- From your project's root folder, run `vagrant plugin install vagrant-notify-forwarder`
- ssh into the VM and run `./scripts/update`, then `./scripts/server`
- Make a change to a file. Verify that the page hot reloads.
Closes #1125
> Remove use of chokidar and add Vagrant plugin to README

- CHANGELOG.md
- src/client/components/map/Map.tsx
- src/client/components/map/index.ts
The Majority-Minority evaluate screen was identifying and drawing the map choropleth incorrectly for the majority race. This issue was also seen in the `ProjectSidebar` when majority race was pinned.
The screen now correctly identifies that the first two districts listed are minority-coalition districts over 65%, rather than a majority Hispanic county. It also correctly identifies that the Asian populations in districts 3 and 4 make up less than 65% and are therefore filled with a lighter color.
- Start the server and navigate to a project screen
- Create a few new districts or use existing districts that match the following criteria: one with a majority race of over 65%, one with a majority race of under 65%, one with a majority-minority coalition over 65%, one with a majority-minority …
> Fix incorrect majority race assignment in map and evaluate

- CHANGELOG.md
- src/client/components/evaluate/detail/CompetitivenessChart.tsx
The PVI chart needed some stylistic enhancements. Along the way, I also found that charts with `yMax` values of less than 3 were displaying y ticks with decimal intervals that made those charts confusing to look at. This PR makes these changes, as well as addressing negative height errors that were appearing in the console during generation of the chart.
The chart with non-decimal labels that are to the left of the ticks, rather than above.
Charts with a `yMax` less than 3, such as this one, are now given `numTicks` equal to `yMax`, rather than a static 4.
The location and spacing of the tick labels has been set to be 10 pixels from the axis and the label to be 5 pixels from the labels using a variable called `leftTickLabelsOffset` that is declared alongside `leftAxisWidth`. This was done …
> Enhance formatting of PVI chart

- CHANGELOG.md
- src/client/actions/projects.ts
- src/client/api.ts
- src/client/components/HomeScreenProjectCard.tsx
- src/client/components/ProjectListFlyout.tsx
- src/client/components/TemplateFromProjectModal.tsx
- src/client/reducers/projects.ts
- src/client/screens/HomeScreen.tsx
- src/server/src/auth/services/auth.service.ts
- src/server/src/project-templates/controllers/project-templates.controller.ts
- src/server/src/project-templates/entities/create-project-template.dto.ts
- src/server/src/project-templates/entities/project-template.entity.ts
- src/server/src/project-templates/project-templates.module.ts
- src/server/src/project-templates/services/project-templates.service.ts
- src/server/src/projects/projects.module.ts
- src/server/src/reference-layers/controllers/reference-layers.controller.ts
- src/server/src/reference-layers/services/reference-layers.service.ts
- src/server/src/users/controllers/users.controller.ts
- src/shared/entities.d.ts
Adds support to create templates from projects.
- Ensure that you are the admin of at least one organization
- Create a new map in any region, and on the homescreen from the "..." menu for that project select "Copy to Template"
- Using the modal should create a new template in the selected organization. Creating a new project from the template should copy districts, pinned fields and reference layers
- Log in as a user that is not an organization admin. You should not see the "Copy to Template" option
Closes #997
> Create template from project

- CHANGELOG.md
- deployment/terraform/scheduled_tasks.tf
This should allow us to tell the difference between prod and staging for reindexing.
- this has to just be deployed everywhere?
Closes: #1129
> parameterize rules so both staging and prod can exist

- CHANGELOG.md
- src/client/api.ts
- src/client/components/map/ProjectDistrictsMap.tsx
- src/server/src/projects/services/projects.service.ts
This PR fixes the incorrect bounds generated for the Alaska mini-map displayed on the home screen. This error was initially caused by an issue with the `@turf/bbox` module—the output for `bbox` included incorrect longitudes coordinates for Alaska’s bounding box, assumed to be an issue with the geojson spanning the anti-meridian. For a more reliable fix, this PR instead uses the static bounds specified in `static-metadata.json`, similar to the main map for a project.
The notes of Issue #992 mention that, since the `static-metadata.json` is available in-memory as part of `TopologyService`, it might be worth creating a `bounds` property that can be sent back for mini-map generation. However, we recently got rid of archived topology layers within `TopologyService`, which means this would not …
> Fix bounds for AK mini-map

- CHANGELOG.md
- src/server/src/districts/services/topology.service.ts
`TopologyService` loads layers by first setting the default value of the key:value pair in `this._layers` to `null` for each region, which later updates to a promise to fetch layers. However, archived regions are filtered out before this loop so their values are left as the default `null`, which fails the health check and consequently broke staging. This PR updates the way in which `TopologyService` filters out regions with archived layers so that the initial regions that populate `this._layers` no longer contain archived regions.
- Wait for all region data to download in the server
- Call the health check endpoint in the browser: `localhost:3005/healthcheck`
- Confirm successful health check
Closes #1147
> Fix TopologyService health check

- CHANGELOG.md
- docker-compose.ci.yml
- scripts/cibuild
- scripts/update
- scripts/yarn
This aims to fix perennial issues where concurrent builds would cause mysterious Jenkins failures where dependencies that had been installed would then go "missing" later in the build
I believe our issue was caused by caching `node_modules` as a Docker volume on the host to enable faster re-builds.
In development this was fine, but on CI any concurrent builds could stomp on each others NPM dependencies. 
Using the `EXECUTOR_NUMBER` as part of the volume path is intended to avoid this, by giving each executor it's own set of `node_modules` folders to use.
I'm going to `ssh` into Jenkins after it builds this PR, and check to see if the new cache directory has the executor number in it.
I'm not going to try to recreate the concurrent build issue, because that sounds like more trouble than …
> Use separate node_modules cache per executor in CI

- CHANGELOG.md
- src/server/src/project-templates/services/project-templates.service.ts
- src/server/src/projects/services/projects.service.ts
Display of the mini-map for featured maps on the organization page was broken by the fix for #992 - which added a need for the `RegionConfig.url` column, which we weren't querying for the Organization screen.
While I was fixing the mini-maps, I also refactored our code so that we're employing the same `districts` simplification that we were already applying to the queries used for the community maps and home page to the query for the organization page as well.
- Ensure that an organization in your development environment has at last one featured map
- On `develop` you won't be able to load the mini-map for featured maps on the organization screen
- On the branch from this PR, the mini-maps should load
- When loading the organization screen, look at the log output from `scripts/server` to …
> Fix organization mini maps

- CHANGELOG.md
- src/client/components/HomeScreenProjectCard.tsx
- src/server/src/projects/services/projects.service.ts
This PR allows users to quickly see the type of districts, e.g. Alabama State Senate, US House of Representatives, etc, of each of their maps.
- Start the server and go to the 'My Maps' page
- Verify that each of your maps' district type is now being displayed on the same line as the number of districts
Closes #1005
> Add district type to project cards on 'My Maps' page

- CHANGELOG.md
- src/server/migrations/1646168889613-userCreationAndLoginDates.ts
- src/server/src/auth/controllers/auth.controller.ts
- src/server/src/auth/services/auth.service.ts
- src/server/src/users/entities/user.entity.ts
- src/server/src/users/services/users.service.ts
Adds a date to the database when a user first creates their account as well as a date for when the user last logs in. The `lastLoginDt` column updates at each log in.
- Create an account, log out, and then run `scripts/dbshell`
- Confirm new columns `createdDt` and `lastLoginDt` are part of the `user` table and populated with default date values (now) for your account
- Wait a few minutes then log back in
- Run `scripts/dbshell` again and confirm that the `lastLoginDt` column has an updated timestamp and `createdDt` remains unchanged
Closes #520
> Add Creation and Login Dates to User

- CHANGELOG.md
- src/client/screens/CreateProjectScreen.tsx
- src/client/screens/ImportProjectScreen.tsx
- src/manage/src/commands/create-random-projects.ts
- src/server/src/districts/controllers/districts.controller.ts
- src/server/src/districts/services/topology.service.ts
- src/server/src/organizations/services/organizations.service.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/region-configs/controllers/region-configs.controller.ts
- src/shared/entities.d.ts
This fixes a multi-part bug:
- We were incorrectly displaying inactive project templates / templates for archived regions on the Create & Import screens
- If you tried to create a project for an archived region, we would not detect or validate that (we do for import)
- Causing the server to try and load a region after application startup would instead cause it to crash, which was triggered by the previous bug, since trying to use the template would then cause it to try and load the archived region
We had a `// @ts-ignore` above one of the offending lines I had to change in https://github.com/PublicMapping/districtbuilder/pull/1185/commits/64c378ce0887f03ec29b74dd02b2794cebfb8137, which had that line not been ignored would have revealed the type error. 😡 
- Using `scripts/dbshell`, set one …
> Fix archived layers crash

- CHANGELOG.md
- src/client/actions/projectData.ts
- src/client/actions/projectModals.ts
- src/client/api.ts
- src/client/components/CopyMapButton.tsx
- src/client/components/ProjectHeader.tsx
- src/client/components/ProjectSidebarHeader.tsx
- src/client/components/SubmitMapModal.tsx
- src/client/components/map/Map.tsx
- src/client/components/map/SubmitMapButton.tsx
- src/client/functions.ts
- src/client/reducers/projectData.ts
- src/client/reducers/projectModals.ts
- src/client/screens/ProjectScreen.tsx
- src/client/theme.ts
- src/manage/dev-data/azavea.yaml
- src/manage/src/commands/update-organization.ts
- src/server/migrations/1648042252591-contest_fields.ts
- src/server/src/project-templates/entities/project-template.entity.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/projects/entities/project.entity.ts
- src/shared/entities.d.ts
Adds workflow for submitting a map for a contest.
Two new fields have been added to `ProjectTemplate`:
- `contestActive`: controls whether the "Submit" button is shown for maps connected to this template
- `contestNextSteps`: HTML to display in the Next steps modal displayed after submission (optional, modal not shown if not set)
Submission date is tracked on a new `Project.submittedDt` field, which also causes the submitted map to become read-only.
Submitting a map w/o next steps HTML set:
Submitting a map with next steps HTML set:
- Use `scripts/load-dev-data` to reload your test data (it should make a contest active on the PA House of Representatives template for the Azavea organization), or use `scripts/dbshell` to set up contest fields for a project template of your choice.
- Create …
> Submit map button

- CHANGELOG.md
- src/client/components/OrganizationAdminProjectsTable.tsx
- src/server/src/project-templates/services/project-templates.service.ts
- src/shared/entities.d.ts
This PR adds the `Submitted on` sortable column to the Organization admin projects table.
- On the app frontend, log in, go to your organization, create a project from a template
- Submit the map from the map UI
- Go to your organization page, next to "Featured maps", click on "View All"
- Make sure you see a table view of the projects and make sure each record has a `Submitted on` column
- For the project submitted, it should show a timestamp; otherwise, it should show a `-`
- Click on `Submitted on` column- it should be sortable
Closes https://github.com/PublicMapping/districtbuilder/issues/1182
> Add submitted column to the Organization admin projects table

- CHANGELOG.md
- src/manage/src/commands/publish-region.ts
- src/server/migrations/1649083635651-region_config_layer_size.ts
- src/server/package.json
- src/server/src/commands/set-topology-size.ts
- src/server/src/common/functions.ts
- src/server/src/districts/entities/geo-unit-topology.entity.ts
- src/server/src/districts/services/topology.service.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/region-configs/entities/region-config.entity.ts
- src/server/src/region-configs/services/region-configs.service.ts
- src/server/src/worker-pool.ts
- src/server/src/worker.ts
Since releasing `1.16.1` our production tasks have become much better at utilizing worker cache - _too_ good in fact, as we've seen several tasks run out of memory and get killed.
I determined a cache level that should always be safe from workers running out of memory and is able to hold all 50 states (13Gb on a 32Gb instance), however while this was only a few GB lower than the previous amount I found it was no longer able to reliably start the application without at least one worker running out of memory and needing to be recreated.
After some research (see https://en.wikipedia.org/wiki/Bin_packing_problem#Offline_algorithms) I determined the best way to ensure full cache utilization on startup would require knowing the region size ahead of time, so I added a new `layer_size_in_bytes` …
> Lower cache size and improve strategy for choosing workers

- CHANGELOG.md
- src/manage/src/commands/process-geojson.ts
I noticed when adding VAP & CVAP to TX and FL that it increased the file size much more than I was expecting (from 888Mb to 1.5Gb).
The demographic fields don't actually get loaded by the server (it uses the typed array buffers for this data), so they're taking up memory for no real purpose.
Previously we didn't think this was a huge deal, as we assumed the demographic fields were small in comparison to the geographic data, but tripling the number of demographic fields made their size much more noticeable.
Incidentally, it turns out the size of the demographic fields differs from state to state, and while there _are_ some states, in particular _Pennsylvania_ which we often use for testing, that have proportionately much more geographic data than demographic data and adding VAP & CVAP …
> Drop demographics and voting fields from the topology data

- CHANGELOG.md
- src/server/migrations/1629680461750-project_index.ts
- src/server/package.json
We temporarily disabled transactions when running migrations a few releases ago in order to create some indexes concurrently (which cannot be done when in a transaction).
This reverts commit fd83d58028422aa2c5198a112af48cb5990f8dec, re-enabling transactions when running migrations.
- Delete/recreate your database and run `scripts/migration` - it should succeed.
Closes #991
> Revert "Create project indexes concurrently by disabling migration transactions"

- CHANGELOG.md
- src/client/components/HomeScreenProjectCard.tsx
- src/client/components/map/SubmitMapButton.tsx
- src/client/screens/ProjectScreen.tsx
- src/server/src/projects/services/projects.service.ts
Some tweaks to the submit map process, plus a change to differentiate submitted maps on the home screen
- Submit a map connected to project template with an active contest and `contestNextSteps` text set
- You should not see a toast message
- Submit a map connected to project template with an active contest and `contestNextSteps` text not set (you could run `UPDATE project_template SET contest_next_steps = '';` using `scripts/dbshell`)
- You should see a toast message after submitting
- The home screen should show "✅Submitted" for your submitted projects instead of "Last updated"
Closes #1199
> Submit button tweaks / text changes

- src/server/src/worker-pool.ts
This checks for the existence of the cgroupv2 memory limit and if that
doesn't exist falls back to the cgroupv2 limit.  This also aligns us
with the limit that works on our current staging environment.
It should fail to start if this doesn't work.
Closes #1196
> Add compatibility with newer cgroups

- CHANGELOG.md
- src/server/src/projects/controllers/projects.controller.ts
- src/shared/constants.ts
- Improves Planscore error logging - we were catching some exceptions and not logging them, and we didn't define an error for timeouts
- Assuming the error is being caused by timeouts, I've doubled the interval for checking results, which will double the amount of time before we consider the upload timed out
- Apply the following diff to make most PlanScore uploads time out:
```diff
diff --git a/src/shared/constants.ts b/src/shared/constants.ts
index 63eeb753..3a5ba39a 100644
--- a/src/shared/constants.ts
+++ b/src/shared/constants.ts
@@ -163,5 +163,5 @@ export const MAX_UPLOAD_FILE_SIZE = 25_000_000;
export const MAX_IMPORT_ERRORS = 1_000;
-export const PLANSCORE_POLL_MAX_TRIES = 40;
+export …
```
> Fix planscore errors

- CHANGELOG.md
- src/manage/src/commands/process-geojson.ts
- src/manage/src/commands/serialize-topojson.ts
When deploying the CVAP data last night, I realized I needed to reprocess Florida.
This then revealed a few small typos w/ the wrong file extension in our processing scripts, which this PR fixes.
You can use this file for testing: 
[ri_vap_cvap_1620.zip](https://github.com/PublicMapping/districtbuilder/files/8640088/ri_vap_cvap_1620.zip)
Unzip and move it to `src/manage/data/ri_vap_cvap_1620.geojson`, and run the following commands:
- `mkdir -p src/manage/data/output-ri`
- `./scripts/manage process-geojson data/ri_vap_cvap_1620.geojson -d "population:population,white:white,black:black,hispanic:hispanic,asian:asian,native:native,pacific:pacific" -d "vap:VAP,vapwhite:VAP White,vapblack:VAP Black,vaphispanic:VAP Hispanic,vapasian:VAP Asian,vapnatam:VAP Native,vappacisl:VAP Pacific"  -d …
> Fix manage scripts typos

- CHANGELOG.md
- src/server/src/districts/services/worker-pool.service.ts
With the timeout checking done outside of the queue, timed out tasks have their worker thread recreated, but no new tasks can be queued because the timed out task will never complete or be rejected.
By moving the timeout into the body of the `workerQueue` task, when we return an error that task will be removed from the queue, allowing future tasks to be run instead of blocking forever.
Apply the following diff to cause attempts to edit projects to time out:
```diff
diff --git a/src/server/src/worker.ts b/src/server/src/worker.ts
index 817bcb8a..8110a701 100644
--- a/src/server/src/worker.ts
+++ b/src/server/src/worker.ts
@@ -248,6 +248,8 @@ async function merge({
demographics,
voting
}: MergeArgs): Promise<DistrictsGeoJSON | null> {
+  await new Promise(r => setTimeout(r, 120_000));
+ …
```
> Fix worker timeout check

- CHANGELOG.md
- src/server/src/districts/services/worker-pool.service.ts
Reduces the worker max cache size, to prevent OoM issues currently being encountered on production.
Since we seemed to be operating fine as-is on other instances sizes I tried to adjust the way we determine cache size to leave the amounts for development & staging roughly the same while reducing the production server cache size.
The purpose of https://github.com/PublicMapping/districtbuilder/commit/6f0b96abeba39f39bf75d799db75c686202de0c2 was to improve our logging when terminating workers:
https://github.com/PublicMapping/districtbuilder/blob/6f0b96abeba39f39bf75d799db75c686202de0c2/src/server/src/districts/services/worker-pool.service.ts#L172-L176
Without this change the `workerSize` for that worker index will have already been reduced by the time we recreate the worker.
We were also …
> Reduce max cache and fix max workers / region check

- CHANGELOG.md
- src/server/src/common/constants.ts
- src/server/src/districts/services/worker-pool.service.spec.ts
- src/server/src/districts/services/worker-pool.service.ts
#1206 introduced a bug that meant that we no longer limited regions to a subset of workers.
I attempted to fix this in #1213, but this fix prevented us from adding a region to more than a single worker (i.e. the server never attempts to load more regions after the initial application startup).
The actual fix here was quite simple, but since this has proved relatively tricky to test manually I spent some time writing up a test suite for the expected behavior, which also uncovered one other small bug (not cleaning up lingering `setTimeout` timers after a worker returns an error).
Test output:
```shell
$ ./scripts/yarn server test
[+] Running 1/0
⠿ Container districtbuilder-database-1  Running                                                                             0.0s
yarn run v1.22.18 …
```
> Fix adding regions to more than 1 worker

- CHANGELOG.md
- src/client/components/PaginationFooter.tsx
- src/client/screens/PublishedMapsListScreen.tsx
This PR adds a prop to the `PaginationFooter` component so that we configure the community maps UI to not show the last page button.
Note that the linked issue's original scope was changed in the first comment.
- Spin up app servers and frontend
- Log in to the home screen. Make sure the pagination footer shows the last page button
- Navigate to the "Community maps" page. Make sure the pagination footer does not show the last page button
Closes #1205
> Hide last page button on Community Maps screen

- deployment/terraform/config.tf
- deployment/terraform/scheduled_tasks.tf
- deployment/terraform/variables.tf
- deployment/terraform/versions.tf
- docker-compose.ci.yml
Bump AWS provider version to 3.53.0 which is the highest we can
go without replacing some of the modules (terraform 1.1 apparently makes this
easier to do).
Also mark some variables sensitive so they don't show up in output which
would help if we move from Jenkins to Github actions.
Closes: #917
- Confirm that everything is still working on both staging and prod
- View the nicely shorter infra plan changes view
> Upgrade terraform to 0.12-> 1.0.0

- CHANGELOG.md
- src/manage/package.json
- src/manage/src/commands/create-random-projects.ts
- src/manage/src/test/create-random-projects.spec.ts
- src/manage/yarn.lock
- src/server/src/districts/services/topology.service.ts
- src/server/src/main.ts
Fix the `create-random-projects` command, which was not working if you had a large number of states.
Since this is a less-utilized part of the application, I also added a small test suite to catch this bug as well as the other regression I've seen a few times with this command (failing to update it after adding a new required field to `Project`).
This is my first time using `pg-mem` but it's pretty cool!
I thought about just using mocks here, but actually hitting the "database" means we can check for regressions in this code due to changes in the database schema adding a required field - not something we would get if we mocked out the database-level.
- Run `scripts/manage create-random-projects`
Closes #1231
> Fix create random projects

- CHANGELOG.md
- src/client/components/map/ProjectDistrictsMap.tsx
- src/client/types.d.ts
- src/manage/src/commands/create-random-projects.ts
- src/manage/src/commands/vendor.d.ts
- src/manage/src/test/create-random-projects.spec.ts
- src/server/global.d.ts
- src/server/migrations/1654279860639-create_simplified_districts_on_project.ts
- src/server/migrations/1654551650115-update_simplified_districts.ts
- src/server/package.json
- src/server/src/districts/entities/geo-unit-topology.entity.ts
- src/server/src/project-templates/services/project-templates.service.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/projects/entities/project.entity.ts
- src/server/src/projects/services/projects.service.ts
- src/server/src/worker.ts
- src/server/yarn.lock
The production database was shutdown by AWS due to excess memory usage, with the potential cause being frequent queries that result in large temporary files being created, as described in [the issue comment](https://github.com/PublicMapping/districtbuilder/issues/1225#issuecomment-1137657992). In order to replicate this, I created ~1500 projects of a little over 50 regions and found similar queries resulting in a large amount of temporary files using `pgbadger` logging. While the temporary files in my local instance were noticeably smaller than those related to the production outage, the query is unique to simplifying the geojson districts on read and of similar frequency. It's assumed that multiple calls from users with a lot of projects of more complex geometries would log temporary …
> Fix excess memory usage on projects query

- docker-compose.yml
This is the version we've been mostly standardizing on. (Same versions that are in Debian stable)
- Any more intensive database tests before we consider it good to move on to staging next.
Related to #1234
> Update to Postgres 13 with PostGIS 3.1

- CHANGELOG.md
- doc/spec/README.md
This PR adds a `README.md` file under `doc/spec/` that includes API spec for `/api/globalProjects`
~It seems this API endpoint is behind auth. I am wondering if there is a way to get a bearer token for authentication before calling the endpoint. If yes, whether it is an endpoint or a set of steps to get this token, I think maybe we should have docs for such a way so that the API spec consumer can follow, since I read from the issue description that this endpoint is designed for public consumption. If this is already documented somewhere, it would be great to guide me to it and have the link included in this doc.~
- Make sure the API spec makes sense and the example response is sufficient.
Closes https://github.com/PublicMapping/districtbuilder/issues/1229
> Add API spec for globalProjects

- CHANGELOG.md
- src/server/package.json
- src/server/src/projects/controllers/projects.controller.spec.ts
- src/server/src/projects/controllers/projects.controller.ts
- src/server/src/projects/entities/update-project.dto.ts
- src/server/yarn.lock
- src/shared/entities.d.ts
Validation of updates to the `pinned_metric_fields` requires getting the StaticMetadata from the `TopologyService` for the region - but we don't load archived regions in the TopologyService, so when attempting to archive a region for a map w/ an archived region, we caused the `TopologyService` to attempt to load that region at runtime, which then caused the healthchecks to begin to fail.
Archived maps are _mostly_ read-only so this isn't a significant issue, but we still allow deleting of archived maps, which is done by updating the `archived` flag on the Project - which then triggered the above scenario.
Deferring loading from the TopologyService unless the `pinned_metric_fields` are present allows us to 
- Create a map
- Using `scripts/dbshell`, set the `regionConfig` associated with …
> Fix deletion of maps w/ archived regions

- .github/ISSUE_TEMPLATE/release.md
- .github/workflows/ci.yml
- .github/workflows/release.yml
This was done in the same way to match other Azavea projects (not public)
and to match the way Jenkins works for the project thus far as well.
Entering a sha with a valid image in ECR is therefore required.
This adds a release workflow that can only plan a production change.
Was considering having it be automated, but all projects I've come across require manual process for release.
Will be tested as part of this plan:
1.     Review and commit it with it just doing a terraform plan
2.     Test the pipeline to make sure it does what we expect
3.     Do a trivial other PR to add terraform apply
4.     Run release using same hash as before to confirm it works
5.     Deploy bugfix to production
Closes #1237
> Add Github Release workflow

- CHANGELOG.md
- deployment/terraform/cloud-config/base-container-instance.yml.tmpl
- deployment/terraform/iam.tf
This allows us to move away from using the bastion and
to connect to a host by just pressing Connect on the instance in AWS WebUI.
Also installed psql on the host so we can connect to database too.
It should be noted that these hosts can get recycled as part of deployments -
so that's the only process change that needs to happen.
I didn't remember that some users will use PGAdmin - that it also [possible](https://manumagalhaes.medium.com/ssm-port-forwarding-connect-to-rds-in-a-private-subnet-with-no-ssh-bonus-with-pgadmin-eefc79d1e8bd) but I haven't tested that yet. 
I have confirmed that I can connect to the database using the psql command.
- Try out how you usually use the bastion but connecting via SSM.
> Enable SSM to ec2 container hosts

- README.md
This PR adds documentation for how a person/group developing, forking or deploying DistrictBuilder in the future can create GeoJSONs that feed into the `process-geojson` script (the output of which can then be fed into the `publish-region` script). `process-region` is documented assuming you have input data in the correct format already - and the purpose of this PR is to document that format.
Assuming the user understands GeoJSON, the key point these new docs emphasize is what fields to include as `properties` in the GeoJSON corresponding to each geographic unit. The properties do not need to be exactly as listed, because the `process-geojson` script allows the user to select a subset of fields and rename fields. 
- Review updates in the [`Development …
> Updates to data processing script docs

- CHANGELOG.md
- deployment/terraform/database.tf
- docker-compose.ci.yml
Verbosity can always be overridden in the live database.
Took two other actions:
* Stopped copying logs to Cloudwatch - this has cost us a lot in the past (and is redundant to RDS logs)
* Added AWS session key (how we are transitioning to do ops tasks).
Tried plan on prod and it matches what has been working there.
If no other PRs overwrite what's running in staging right now, both changed values (logs and verbosity) can be confirmed just looking at the DB config and parameter groups.
Closes #1265
> Specify verbosity in parameter group and set to terse.

- CHANGELOG.md
- src/server/src/districts/services/topology.service.ts
As described in issue #1314, some endpoint is causing an archived RegionConfig to get added to the layers list, and since it happens to be a broken layer that crashes when you try to load it, it's causing lots of problems.
Ideally we'd know where that request is coming from and fix it (like we did in #1241), but having a check in `TopologyService.get()` will solve the bigger part of the issue, and will be a good thing to have as a failsafe even if we do find the source.
Since I don't know where the bad call is coming from, the best I can come up with for how to test this would be to modify the code locally to trigger it.  E.g. manually archive a `region_config` instance, then hard-code its ID into one of the calls in `projects.controller.ts` (in either the `createOne` or `duplicateOne` …
> Make TopologyService refuse to load archived RegionConfigs
